package correlator

import (
	"context"
	"testing"
	"time"

	"github.com/zugolO/ebpf-guard/pkg/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestIngest_SharesLearnerWithIngestPool verifies that ce.anomalyDetector (the
// detector used by the single-goroutine Ingest path) is wired onto the same
// shared BaselineLearner as the IngestAsync worker pool (issue #246, point 3).
//
// Only IngestAsync is driven here — ce.anomalyDetector.ProcessEvent is never
// called directly. Before the fix, ce.anomalyDetector held its own, never-fed
// BaselineLearner and IsLearningComplete() would stay false forever. After the
// fix it observes the aggregate sample count recorded by the worker pool.
func TestIngest_SharesLearnerWithIngestPool(t *testing.T) {
	const minSamples = 200

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cfg := DefaultCorrelationEngineConfig()
	cfg.EnableAnomaly = true
	cfg.AnomalyThreshold = 0.9
	cfg.LearningPeriod = time.Millisecond
	cfg.MinLearningSamples = minSamples
	cfg.IngestWorkerCount = 4
	cfg.EnableRateLimit = false
	cfg.EnableDedup = false

	engine := NewCorrelationEngineWithConfig(cfg)
	defer engine.Close()

	ad := engine.GetAnomalyDetector()
	require.NotNil(t, ad)
	require.False(t, ad.IsLearningComplete(), "should still be learning before any events")

	const totalEvents = minSamples * 3
	for i := 0; i < totalEvents; i++ {
		engine.IngestAsync(ctx, types.Event{
			Type: types.EventSyscall,
			PID:  uint32(i % 1024),
			Syscall: &types.SyscallEvent{
				Nr: int64(i % 10),
			},
		})
	}

	deadline := time.After(8 * time.Second)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-deadline:
			t.Fatal("timed out waiting for ce.anomalyDetector to observe the pool's aggregate learning progress")
		case <-ticker.C:
			if ad.IsLearningComplete() {
				return
			}
		}
	}
}

// TestDrainIngestPool_FlushesQueuedAlerts verifies that alerts generated by
// events dispatched via IngestAsync are visible via Flush() once
// DrainIngestPool returns — the ordering production shutdown now relies on
// (issue #245/#246: the ingest worker pool must be drained before the final
// pending Flush, not just inside the later Close()).
func TestDrainIngestPool_FlushesQueuedAlerts(t *testing.T) {
	rules := []Rule{
		{
			ID:        "drain_pool_rule",
			Name:      "Drain Pool Test Rule",
			EventType: types.EventTCPConnect,
			Condition: RuleCondition{
				Field:  "dport",
				Op:     OpEquals,
				Values: []string{"8888"},
			},
			Severity: types.SeverityWarning,
			Action:   ActionAlert,
		},
	}

	cfg := DefaultCorrelationEngineConfig()
	cfg.Rules = rules
	cfg.EnableDedup = false
	cfg.EnableRateLimit = false
	cfg.IngestWorkerCount = 4

	eng := NewCorrelationEngineWithConfig(cfg)
	defer eng.Close()

	ctx := context.Background()

	const count = 40
	for i := 0; i < count; i++ {
		eng.IngestAsync(ctx, types.Event{
			Type:    types.EventTCPConnect,
			PID:     uint32(i + 1),
			Network: &types.NetworkEvent{Dport: 8888},
		})
	}

	drainCtx, drainCancel := context.WithTimeout(ctx, 5*time.Second)
	defer drainCancel()
	eng.DrainIngestPool(drainCtx)

	alerts := eng.Flush()
	assert.Equal(t, count, len(alerts), "all alerts from events queued before DrainIngestPool must be present")
}

// TestDrainIngestPool_ThenClose verifies that calling DrainIngestPool followed
// by Close does not panic on a double-close of the ingest worker channels —
// both must be safe to call in sequence, as gracefulShutdown now does.
func TestDrainIngestPool_ThenClose(t *testing.T) {
	eng := NewCorrelationEngineWithConfig(DefaultCorrelationEngineConfig())

	ctx := context.Background()
	eng.IngestAsync(ctx, types.Event{Type: types.EventSyscall, PID: 1, Syscall: &types.SyscallEvent{Nr: 1}})

	drainCtx, drainCancel := context.WithTimeout(ctx, 5*time.Second)
	defer drainCancel()

	assert.NotPanics(t, func() {
		eng.DrainIngestPool(drainCtx)
		eng.Close()
	})
}
