package correlator

import (
	"bufio"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/zugolO/ebpf-guard/internal/bpf"
)

const portionManifest = "../../deploy/docker-test-setup/attacks/wave7-nr-portions.txt"

type nrPortion struct {
	id        string
	nrs       []int
	rules     []string
	muteRules []string
	rejected  []int
	reopened  []int
}

type portionFile struct {
	baseline []int
	excluded []int
	portions []nrPortion
}

// readPortionManifest parses wave7-nr-portions.txt the way the pipeline emitter
// parses it: line-oriented, `<scope> <kind> <value>`, comments after `#`.
func readPortionManifest(t *testing.T) portionFile {
	t.Helper()

	fh, err := os.Open(portionManifest)
	require.NoError(t, err, "the portion manifest is generated by tools/rules-audit/nr-portions.py")
	defer func() { _ = fh.Close() }()

	out := portionFile{}
	index := map[string]int{}

	sc := bufio.NewScanner(fh)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		scope, kind, value := fields[0], fields[1], fields[2]

		switch {
		case scope == "BASELINE" && kind == "NR":
			for _, tok := range strings.Split(value, ",") {
				n, err := strconv.Atoi(tok)
				require.NoError(t, err)
				out.baseline = append(out.baseline, n)
			}
		case scope == "EXCLUDED" && kind == "NR":
			n, err := strconv.Atoi(value)
			require.NoError(t, err)
			out.excluded = append(out.excluded, n)
		case strings.HasPrefix(scope, "P"):
			id := strings.TrimPrefix(scope, "P")
			pos, seen := index[id]
			if !seen {
				pos = len(out.portions)
				index[id] = pos
				out.portions = append(out.portions, nrPortion{id: id})
			}
			switch kind {
			case "NR":
				n, err := strconv.Atoi(value)
				require.NoError(t, err)
				out.portions[pos].nrs = append(out.portions[pos].nrs, n)
			case "RULE":
				out.portions[pos].rules = append(out.portions[pos].rules, value)
			case "MUTERULE":
				out.portions[pos].muteRules = append(out.portions[pos].muteRules, value)
			case "REJECTED":
				n, err := strconv.Atoi(value)
				require.NoError(t, err)
				out.portions[pos].rejected = append(out.portions[pos].rejected, n)
			case "REOPENED":
				n, err := strconv.Atoi(value)
				require.NoError(t, err)
				out.portions[pos].reopened = append(out.portions[pos].reopened, n)
			}
		}
	}
	require.NoError(t, sc.Err())
	require.NotEmpty(t, out.portions, "manifest carries no portion")
	return out
}

// effective — номера порции, которые она РЕАЛЬНО открывает: состав минус отвергнутые
// ИМЕННО В ЭТОЙ порции. Отказ принадлежит порции, где цена снята; более поздняя
// порция может открыть тот же номер (порция 4 открывает socket(41) после правки
// предиката, №516) — но только записью REOPENED, см. TestWave7ReopenedNumbersAreExplained.
func (p nrPortion) effective() []int {
	rej := map[int]bool{}
	for _, n := range p.rejected {
		rej[n] = true
	}
	var out []int
	for _, n := range p.nrs {
		if !rej[n] {
			out = append(out, n)
		}
	}
	return out
}

// The manifest states which rules each portion buys. That claim is a function
// of (the ruleset, the baseline allowlist, the portion's numbers) — so it is
// replayed here against the real rules/ tree through the same registry the
// agent prints at startup. A portion whose rule list drifts from the ruleset
// would make the A/B pair of item б3 measure a drop in muteness that the run
// cannot attribute to the numbers it opened.
func TestWave7PortionManifestMatchesRuleset(t *testing.T) {
	man := readPortionManifest(t)

	// The baseline is the PRE-б3 allowlist — the one item б2 measured the price
	// against — and it stays that list as portions get opened permanently.
	// Checking it against DefaultMonitoredSyscalls() outright would hold only
	// until the first portion ships: the default would then already contain the
	// portion's numbers, the portion would buy nothing, and the manifest would
	// have to be regenerated into a table of empty portions.
	//
	// What must hold forever: the default equals the baseline plus exactly the
	// numbers of the portions already opened, and never anything else.
	opened := map[int]bool{}
	for _, p := range man.portions {
		for _, nr := range p.effective() {
			opened[nr] = true
		}
	}
	var extra []int
	base := map[int]bool{}
	for _, nr := range man.baseline {
		base[nr] = true
	}
	for _, nr := range bpf.DefaultMonitoredSyscalls() {
		if !base[nr] {
			extra = append(extra, nr)
			assert.True(t, opened[nr],
				"number %d is in DefaultMonitoredSyscalls() but neither in the manifest's "+
					"baseline nor in any portion — it was opened without a measured price", nr)
		}
	}
	for _, nr := range man.baseline {
		assert.Contains(t, bpf.DefaultMonitoredSyscalls(), nr,
			"number %d is in the manifest's baseline but no longer in "+
				"DefaultMonitoredSyscalls(): the baseline is a historical constant and "+
				"a number cannot leave it", nr)
	}
	t.Logf("порций открыто постоянно: номеров сверх baseline %d (%v)", len(extra), extra)

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	open := append([]int{}, man.baseline...)
	mute := re.UnreachableSyscallRules(open)

	for _, p := range man.portions {
		require.NotEmpty(t, p.nrs, "portion %s opens no number", p.id)

		open = append(open, p.effective()...)
		after := re.UnreachableSyscallRules(open)

		// Покупает портия только ОТКРЫВАЕМОЙ частью. Правила, оставшиеся немыми по
		// решению (MUTERULE), не входят в купленное и обязаны остаться в `after`:
		// это держит TestWave7KeptMuteRulesStayMute, а здесь — равенство состава.
		opened := setDifference(mute, after)
		assert.ElementsMatch(t, p.rules, opened,
			"portion %s opens numbers %v: the manifest claims it buys %v, the ruleset says %v "+
				"(left mute by decision: %v)",
			p.id, p.effective(), p.rules, opened, p.muteRules)

		mute = after
	}

	// Every number is spent on a rule: a portion carrying a number that opens
	// nothing would be paid for and buy nothing.
	for _, p := range man.portions {
		assert.NotEmpty(t, p.rules, "portion %s buys no rule", p.id)
	}
}

// MUTERULE — правило порции, чьи номера ОТВЕРГНУТЫ, и потому оно остаётся немым
// по решению, а не по недосмотру. Утверждение проверяемое: открыв ВСЕ
// неотвергнутые номера ВСЕХ порций, такое правило обязано остаться немым. Если
// оно откроется другим путём, запись «остаётся немым по решению» станет ложью, а
// эмиттер метки 6.6.9 ждёт его в реестре немоты и объявит роль B провалившейся.
func TestWave7KeptMuteRulesStayMute(t *testing.T) {
	man := readPortionManifest(t)

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	// Проверка идёт ПО ПОРЦИЯМ, а не по итоговому состоянию: правило, оставшееся
	// немым в порции 3 по решению, законно открывается порцией 4 (повторное
	// открытие номера), и «немо в конце» стало бы ложной проверкой.
	open := append([]int{}, man.baseline...)
	kept := 0
	for _, p := range man.portions {
		open = append(open, p.effective()...)
		mute := map[string]bool{}
		for _, rid := range re.UnreachableSyscallRules(open) {
			mute[rid] = true
		}
		for _, rid := range p.muteRules {
			kept++
			assert.True(t, mute[rid],
				"правило %s записано как остающееся немым ПО РЕШЕНИЮ порции %s, но при открытых "+
					"неотвергнутых номерах до неё включительно оно ДОСТИЖИМО: запись лжёт, и "+
					"эмиттер 6.6.9 объявит роль B провалившейся, увидев его вне реестра немоты",
				rid, p.id)
		}
	}
	require.NotZero(t, kept,
		"ни одного MUTERULE: сторож остался бы зелёным на любом манифесте")
	t.Logf("правил, оставленных немыми по решению: %d", kept)
}

// «Не отменять строку REJECTED молча»: номер, отвергнутый в ранней порции и
// присутствующий неотвергнутым в более поздней, обязан нести в поздней строку
// REOPENED с причиной. Без неё манифест можно было бы перегенерировать так, что
// отказ по цене исчез бы, а следа решения не осталось.
func TestWave7ReopenedNumbersAreExplained(t *testing.T) {
	man := readPortionManifest(t)

	rejectedIn := map[int][]string{}
	reopens := 0
	for _, p := range man.portions {
		eff := map[int]bool{}
		for _, n := range p.effective() {
			eff[n] = true
		}
		reopened := map[int]bool{}
		for _, n := range p.reopened {
			reopened[n] = true
			reopens++
			assert.NotEmpty(t, rejectedIn[n],
				"порция %s: REOPENED %d, а ранее этот номер не отвергался — запись без предмета", p.id, n)
			assert.True(t, eff[n], "порция %s: REOPENED %d, но номер в ней не открывается", p.id, n)
		}
		for n := range eff {
			if len(rejectedIn[n]) > 0 {
				assert.True(t, reopened[n],
					"номер %d отвергнут в порции(ях) %v и открыт в порции %s БЕЗ строки REOPENED: "+
						"отказ отменён молча", n, rejectedIn[n], p.id)
			}
		}
		for _, n := range p.rejected {
			rejectedIn[n] = append(rejectedIn[n], p.id)
		}
	}
	require.NotZero(t, reopens, "ни одного REOPENED: сторож остался бы зелёным на любом манифесте")
}

// Порция может открыться ЧАСТЬЮ: цена снимается парой по КАЖДОМУ номеру, и
// номер, чья цена не прошла, помечается в манифесте строкой `P<n> REJECTED`.
// Порция 2 (30.09.2026) — первый такой случай: из пяти номеров открыты два.
// Сторож держит три следствия этого, каждое — на величине, а не на комментарии.
func TestWave7RejectedNumbersStayClosed(t *testing.T) {
	man := readPortionManifest(t)

	def := map[int]bool{}
	for _, nr := range bpf.DefaultMonitoredSyscalls() {
		def[nr] = true
	}

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	anyRejected := false
	for _, p := range man.portions {
		rejected := map[int]bool{}
		for _, nr := range p.rejected {
			rejected[nr] = true
			anyRejected = true
			// (1) Отвергнутый номер в аллоулист попасть не может: иначе его
			// цена записана как непройденная, а платится она всё равно.
			// Номер может быть в аллоулисте, если более поздняя порция открыла его
			// ЯВНО (REOPENED): тогда отказ ранней порции исполнен и снят решением.
			if !reopenedLater(man, p.id, nr) {
				assert.False(t, def[nr],
					"номер %d помечен в манифесте как REJECTED (порция %s), но он есть "+
						"в DefaultMonitoredSyscalls(): отказ по цене и открытие одновременно",
					nr, p.id)
			}
			assert.Contains(t, p.nrs, nr,
				"номер %d отвергнут в порции %s, но в её составе его нет", nr, p.id)
		}

		// Порция считается ПОСТАВЛЕННОЙ, если хоть один её номер уже в
		// аллоулисте. Дальше проверяем её только в этом случае: порция, ещё не
		// поставленная (у неё цена не снята), ничего не обязана.
		shipped := false
		for _, nr := range p.effective() {
			if def[nr] {
				shipped = true
				break
			}
		}
		if !shipped {
			continue
		}

		// (2) У поставленной порции каждый номер либо открыт, либо ОТВЕРГНУТ
		// ИМЕНЕМ. Молча выпасть номер не может — иначе состав порции в
		// манифесте разъезжается с тем, что реально несёт аллоулист.
		var openedNrs []int
		for _, nr := range p.nrs {
			if def[nr] && !rejected[nr] {
				openedNrs = append(openedNrs, nr)
				continue
			}
			assert.True(t, rejected[nr],
				"порция %s поставлена, но номер %d не открыт и не помечен REJECTED: "+
					"выпал молча", p.id, nr)
		}

		// (3) Открытая часть порции обязана покупать правило. Ровно этим
		// провалились 37 и 83: 4394 события за окно и ни одного нового правила.
		base := append([]int{}, man.baseline...)
		for _, q := range man.portions {
			if q.id == p.id {
				break
			}
			for _, nr := range q.effective() {
				if def[nr] {
					base = append(base, nr)
				}
			}
		}
		before := re.UnreachableSyscallRules(base)
		after := re.UnreachableSyscallRules(append(append([]int{}, base...), openedNrs...))
		bought := setDifference(before, after)
		assert.NotEmpty(t, bought,
			"порция %s открыта номерами %v и не покупает НИ ОДНОГО правила: "+
				"цена платится, немота не падает", p.id, openedNrs)
		t.Logf("порция %s: открыто %v, куплено правил %d (%v)", p.id, openedNrs, len(bought), bought)
	}
	require.True(t, anyRejected,
		"ни одного REJECTED в манифесте: сторож частичного открытия остался бы "+
			"зелёным на любом составе")
}

// nanosleep(35) is named in the manifest as excluded, and the exclusion is only
// honest while the rule that names it opens through some other number. If
// web_blind_sqli_heuristic ever became reachable ONLY through 35, the exclusion
// would silently be a rule left mute rather than a price not paid.
func TestWave7ExcludedNumbersLeaveNoRuleMute(t *testing.T) {
	man := readPortionManifest(t)
	require.NotEmpty(t, man.excluded)

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	open := append([]int{}, man.baseline...)
	for _, p := range man.portions {
		open = append(open, p.nrs...)
		for _, nr := range p.nrs {
			assert.NotContains(t, man.excluded, nr,
				"number %d is both opened by portion %s and declared excluded", nr, p.id)
		}
	}

	stillMute := re.UnreachableSyscallRules(open)
	for _, id := range stillMute {
		assert.NotContains(t, allPortionRules(man), id,
			"rule %q is named by a portion yet stays mute after every portion is open", id)
	}

	// The registry must still be able to say "mute": opening every portion
	// cannot be indistinguishable from a broken detector.
	withExcluded := append(append([]int{}, open...), man.excluded...)
	assert.Subset(t, re.UnreachableSyscallRules(open), re.UnreachableSyscallRules(withExcluded),
		"opening the excluded numbers as well must not make MORE rules mute")
}

// reopenedLater — открывает ли ПОЗДНЕЙШАЯ, чем from, порция номер nr записью REOPENED.
func reopenedLater(man portionFile, from string, nr int) bool {
	seen := false
	for _, p := range man.portions {
		if p.id == from {
			seen = true
			continue
		}
		if !seen {
			continue
		}
		for _, n := range p.reopened {
			if n == nr {
				return true
			}
		}
	}
	return false
}

func allPortionRules(man portionFile) []string {
	out := []string{}
	for _, p := range man.portions {
		out = append(out, p.rules...)
	}
	return out
}

func setDifference(before, after []string) []string {
	gone := map[string]struct{}{}
	for _, id := range before {
		gone[id] = struct{}{}
	}
	for _, id := range after {
		delete(gone, id)
	}
	out := make([]string, 0, len(gone))
	for id := range gone {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}
