package correlator

import (
	"bufio"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/zugolO/ebpf-guard/internal/bpf"
)

const portionManifest = "../../deploy/docker-test-setup/attacks/wave7-nr-portions.txt"

type nrPortion struct {
	id    string
	nrs   []int
	rules []string
}

type portionFile struct {
	baseline []int
	excluded []int
	portions []nrPortion
}

// readPortionManifest parses wave7-nr-portions.txt the way the pipeline emitter
// parses it: line-oriented, `<scope> <kind> <value>`, comments after `#`.
func readPortionManifest(t *testing.T) portionFile {
	t.Helper()

	fh, err := os.Open(portionManifest)
	require.NoError(t, err, "the portion manifest is generated by tools/rules-audit/nr-portions.py")
	defer func() { _ = fh.Close() }()

	out := portionFile{}
	index := map[string]int{}

	sc := bufio.NewScanner(fh)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		scope, kind, value := fields[0], fields[1], fields[2]

		switch {
		case scope == "BASELINE" && kind == "NR":
			for _, tok := range strings.Split(value, ",") {
				n, err := strconv.Atoi(tok)
				require.NoError(t, err)
				out.baseline = append(out.baseline, n)
			}
		case scope == "EXCLUDED" && kind == "NR":
			n, err := strconv.Atoi(value)
			require.NoError(t, err)
			out.excluded = append(out.excluded, n)
		case strings.HasPrefix(scope, "P"):
			id := strings.TrimPrefix(scope, "P")
			pos, seen := index[id]
			if !seen {
				pos = len(out.portions)
				index[id] = pos
				out.portions = append(out.portions, nrPortion{id: id})
			}
			switch kind {
			case "NR":
				n, err := strconv.Atoi(value)
				require.NoError(t, err)
				out.portions[pos].nrs = append(out.portions[pos].nrs, n)
			case "RULE":
				out.portions[pos].rules = append(out.portions[pos].rules, value)
			}
		}
	}
	require.NoError(t, sc.Err())
	require.NotEmpty(t, out.portions, "manifest carries no portion")
	return out
}

// The manifest states which rules each portion buys. That claim is a function
// of (the ruleset, the baseline allowlist, the portion's numbers) — so it is
// replayed here against the real rules/ tree through the same registry the
// agent prints at startup. A portion whose rule list drifts from the ruleset
// would make the A/B pair of item б3 measure a drop in muteness that the run
// cannot attribute to the numbers it opened.
func TestWave7PortionManifestMatchesRuleset(t *testing.T) {
	man := readPortionManifest(t)

	assert.ElementsMatch(t, bpf.DefaultMonitoredSyscalls(), man.baseline,
		"the manifest's baseline must be the allowlist the stand actually falls back to "+
			"(config-test.yaml sets no monitored_syscalls)")

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	open := append([]int{}, man.baseline...)
	mute := re.UnreachableSyscallRules(open)

	for _, p := range man.portions {
		require.NotEmpty(t, p.nrs, "portion %s opens no number", p.id)

		open = append(open, p.nrs...)
		after := re.UnreachableSyscallRules(open)

		opened := setDifference(mute, after)
		assert.ElementsMatch(t, p.rules, opened,
			"portion %s opens numbers %v: the manifest claims it buys %v, the ruleset says %v",
			p.id, p.nrs, p.rules, opened)

		mute = after
	}

	// Every number is spent on a rule: a portion carrying a number that opens
	// nothing would be paid for and buy nothing.
	for _, p := range man.portions {
		assert.NotEmpty(t, p.rules, "portion %s buys no rule", p.id)
	}
}

// nanosleep(35) is named in the manifest as excluded, and the exclusion is only
// honest while the rule that names it opens through some other number. If
// web_blind_sqli_heuristic ever became reachable ONLY through 35, the exclusion
// would silently be a rule left mute rather than a price not paid.
func TestWave7ExcludedNumbersLeaveNoRuleMute(t *testing.T) {
	man := readPortionManifest(t)
	require.NotEmpty(t, man.excluded)

	rules, err := LoadRulesFromDir("../../rules")
	require.NoError(t, err)
	re := NewRuleEngine(rules)

	open := append([]int{}, man.baseline...)
	for _, p := range man.portions {
		open = append(open, p.nrs...)
		for _, nr := range p.nrs {
			assert.NotContains(t, man.excluded, nr,
				"number %d is both opened by portion %s and declared excluded", nr, p.id)
		}
	}

	stillMute := re.UnreachableSyscallRules(open)
	for _, id := range stillMute {
		assert.NotContains(t, allPortionRules(man), id,
			"rule %q is named by a portion yet stays mute after every portion is open", id)
	}

	// The registry must still be able to say "mute": opening every portion
	// cannot be indistinguishable from a broken detector.
	withExcluded := append(append([]int{}, open...), man.excluded...)
	assert.Subset(t, re.UnreachableSyscallRules(open), re.UnreachableSyscallRules(withExcluded),
		"opening the excluded numbers as well must not make MORE rules mute")
}

func allPortionRules(man portionFile) []string {
	out := []string{}
	for _, p := range man.portions {
		out = append(out, p.rules...)
	}
	return out
}

func setDifference(before, after []string) []string {
	gone := map[string]struct{}{}
	for _, id := range before {
		gone[id] = struct{}{}
	}
	for _, id := range after {
		delete(gone, id)
	}
	out := make([]string, 0, len(gone))
	for id := range gone {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}
