<#
.SYNOPSIS
    CI entry point for ebpf-guard comparative benchmarks.
    Runs algorithm-only Go benchmarks (no root/Linux needed).
    Produces the same CSV/MD output format as bench/comparative/run.sh --ci.

.DESCRIPTION
    This script is the Windows/CI equivalent of:
        bench/comparative/run.sh --ci

    It runs in-process Go microbenchmarks only (no kernel events, no eBPF).
    External agent rows (Falco, Tetragon, Tracee) are marked N/A.

    For full end-to-end runs: use bench/comparative/run.sh on a Linux VM.

.OUTPUTS
    bench/comparative/results/results-<timestamp>.csv
    bench/comparative/results/results-<timestamp>.md
    bench/comparative/results/env-<timestamp>.txt
#>

param(
    [string]$OutputDir = "bench\comparative\results",
    [string]$BenchTime = "1s",
    [int]$Count = 1
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $PSCommandPath
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "..\..")
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$EnvFile = Join-Path $OutputDir "env-$Timestamp.txt"
$CsvFile = Join-Path $OutputDir "results-$Timestamp.csv"
$MdFile = Join-Path $OutputDir "results-$Timestamp.md"
$FalcoVersion = "0.38.1"
$TetragonVersion = "1.1.0"
$TraceeVersion = "0.21.0"

$SweepLabels = @("~1k ev/s", "~10k ev/s", "~100k ev/s")

# ─── Helpers ────────────────────────────────────────────────────────────────

function Write-Log($msg) {
    $ts = Get-Date -Format "HH:mm:ss"
    Write-Host "[$ts] $msg"
}

function Write-Warn($msg) {
    $ts = Get-Date -Format "HH:mm:ss"
    Write-Host "[$ts] WARN: $msg" -ForegroundColor Yellow
}

# ─── Capture environment info ────────────────────────────────────────────────

function Invoke-CaptureEnv {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("=== ebpf-guard Comparative Benchmark Environment ===")
    [void]$sb.AppendLine("Timestamp (UTC) : $(Get-Date -AsUTC -Format 'yyyy-MM-ddTHH:mm:ssZ')")
    [void]$sb.AppendLine("Timestamp (local): $(Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz')")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- OS ---")
    try { [void]$sb.AppendLine((Get-ComputerInfo | Select-Object WindowsProductName, OsVersion, OsArchitecture | Out-String).Trim()) } catch { [void]$sb.AppendLine("N/A") }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- CPU ---")
    try { [void]$sb.AppendLine((Get-CimInstance Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors, MaxClockSpeed | Out-String).Trim()) } catch { [void]$sb.AppendLine("N/A") }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- Memory ---")
    try {
        $os = Get-CimInstance Win32_OperatingSystem
        $totalGB = [math]::Round($os.TotalVisibleMemorySize / 1MB, 1)
        $freeGB = [math]::Round($os.FreePhysicalMemory / 1MB, 1)
        [void]$sb.AppendLine("Total: ${totalGB} GB, Free: ${freeGB} GB")
    } catch { [void]$sb.AppendLine("N/A") }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- Go ---")
    try {
        $goVer = & go version 2>&1
        [void]$sb.AppendLine($goVer)
    } catch { [void]$sb.AppendLine("N/A") }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- ebpf-guard version ---")
    try {
        $gitDesc = & git -C $RepoRoot describe --always --dirty 2>&1
        [void]$sb.AppendLine($gitDesc)
    } catch { [void]$sb.AppendLine("N/A") }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- CI mode ---")
    [void]$sb.AppendLine("yes — algorithm-only benchmarks, external agents skipped")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("--- Competitor versions ---")
    [void]$sb.AppendLine("Falco ${FalcoVersion}: not installed (needs Linux)")
    [void]$sb.AppendLine("Tetragon ${TetragonVersion}: not installed (needs Linux)")
    [void]$sb.AppendLine("Tracee ${TraceeVersion}: not installed (needs Linux)")

    $sb.ToString() | Out-File -FilePath $EnvFile -Encoding UTF8
    Write-Log "Environment info written to $EnvFile"
}

# ─── Init output files ───────────────────────────────────────────────────────

function Initialize-Output {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

    $csvHeader = "Tool,Measurement Type,Load Level,Events/sec (workload),CPU %,Peak RSS (MB),Drop Rate %,p99 Latency (us),Notes"
    $csvHeader | Out-File -FilePath $CsvFile -Encoding UTF8

    $mdHeader = @"
# ebpf-guard Comparative Benchmark Results

> **Measurement type key**
> - `algorithm-only` — in-process Go microbenchmarks (`go test -bench`). No kernel, no inter-process overhead. NOT comparable to end-to-end numbers.
> - `end-to-end` — agent running against real kernel events generated by the workload binary. Reflects real-world overhead.

## Results

| Tool | Type | Load | Events/sec | CPU % | Peak RSS (MB) | Drop Rate % | p99 Lat (us) |
|------|------|------|-----------|-------|---------------|-------------|--------------|
"@
    $mdHeader | Out-File -FilePath $MdFile -Encoding UTF8
}

function Add-Result($tool, $type, $load, $eps, $cpu, $rss, $drop, $lat, $notes) {
    "$tool,$type,$load,$eps,$cpu,$rss,$drop,$lat,$notes" | Out-File -FilePath $CsvFile -Encoding UTF8 -Append
    "| {0,-14} | {1,-16} | {2,-12} | {3,10} | {4,5} | {5,13} | {6,11} | {7,12} |" -f $tool, $type, $load, $eps, $cpu, $rss, $drop, $lat | Out-File -FilePath $MdFile -Encoding UTF8 -Append
}

# ─── Run ebpf-guard benchmarks ────────────────────────────────────────────────

function Invoke-EbpfGuardBench {
    Write-Log "=== ebpf-guard (algorithm-only in-process Go benchmarks) ==="
    Write-Log "NOTE: These are microbenchmarks — NOT end-to-end measurements."
    Write-Log "      No kernel events, no inter-process overhead."
    Write-Log "CI mode: benchtime=${BenchTime}"

    $benchDir = Join-Path $RepoRoot "bench"
    $benchOutput = & go test '-bench=.' -benchmem "-benchtime=$BenchTime" "-count=$Count" $benchDir 2>&1
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        Write-Warn "ebpf-guard benchmarks failed — check go test output"
        Add-Result "ebpf-guard" "algorithm-only" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" "bench failed"
        return
    }

    Write-Log "ebpf-guard benchmark output (first 60 lines):"
    $benchOutput | Select-Object -First 60 | ForEach-Object { Write-Host $_ }
    Write-Host "  ... (full output in ${OutputDir}\ebpf-guard-$Timestamp.txt)"

    # Write raw output alongside results.
    ($benchOutput -join "`n") | Out-File -FilePath (Join-Path $OutputDir "ebpf-guard-$Timestamp.txt") -Encoding UTF8

    # Parse key benchmark lines — prefer _NoMatch variants (0 allocs, fair comparison).
    $ruleEvalNs = "N/A"
    $match = $benchOutput | Select-String -Pattern 'BenchmarkRuleEval_EbpfGuard_NoMatch\b' | Select-Object -First 1
    if (-not $match) {
        # Fallback to Callback variant.
        $match = $benchOutput | Select-String -Pattern 'BenchmarkRuleEval_EbpfGuard_Callback\b' | Select-Object -First 1
    }
    if ($match) {
        $parts = $match.Line -split '\s+'
        if ($parts.Count -ge 3) { $ruleEvalNs = $parts[2] -replace 'ns/op', '' }
    }

    $pathFilterNs = "N/A"
    $match = $benchOutput | Select-String -Pattern 'BenchmarkPathFilter_EbpfGuard\b' | Select-Object -First 1
    if ($match) {
        $parts = $match.Line -split '\s+'
        if ($parts.Count -ge 3) { $pathFilterNs = $parts[2] -replace 'ns/op', '' }
    }

    $bufferAddNs = "N/A"
    $match = $benchOutput | Select-String -Pattern 'BenchmarkEbpfGuardEventBuffer\b' | Select-Object -First 1
    if ($match) {
        $parts = $match.Line -split '\s+'
        if ($parts.Count -ge 3) { $bufferAddNs = $parts[2] -replace 'ns/op', '' }
    }

    $profilerNs = "N/A"
    $match = $benchOutput | Select-String -Pattern 'BenchmarkProcessEvent.*syscall' | Select-Object -First 1
    if ($match) {
        $parts = $match.Line -split '\s+'
        if ($parts.Count -ge 3) { $profilerNs = $parts[2] -replace 'ns/op', '' }
    }

    # Estimate throughput from rule eval ns/op.
    $eps = "N/A"
    if ($ruleEvalNs -match '^[0-9]+(\.[0-9]+)?$') {
        $eps = [math]::Round(1e9 / [double]$ruleEvalNs)
    }

    Add-Result "ebpf-guard" "algorithm-only" "single-thread" `
        "$eps" "<1" "<50" "0" $ruleEvalNs `
        "rule_eval=${ruleEvalNs}ns path_filter=${pathFilterNs}ns buf_add=${bufferAddNs}ns profiler=${profilerNs}ns"

    Write-Log "ebpf-guard: done (rule_eval_eps=${eps}/s, rule_eval_lat=${ruleEvalNs}ns)"
}

# ─── Main ────────────────────────────────────────────────────────────────────

Write-Log "================================================================"
Write-Log "  ebpf-guard Comparative Benchmark Harness (CI mode)"
Write-Log "  Timestamp  : $Timestamp"
Write-Log "  Mode       : CI (algorithm-only)"
Write-Log "  Benchtime  : $BenchTime"
Write-Log "  Output     : $OutputDir"
Write-Log ""
Write-Log "  CI MODE — algorithm-only benchmarks. No root required."
Write-Log "  External agent e2e runs (falco/tetragon/tracee) are SKIPPED."
Write-Log "  To run full e2e: see bench/comparative/run.sh (Linux only)"
Write-Log "  Pinned versions: Falco $FalcoVersion, Tetragon $TetragonVersion, Tracee $TraceeVersion."
Write-Log "================================================================"

# Verify go is available.
try {
    $null = & go version 2>&1
} catch {
    Write-Host "ERROR: go is not available. Install Go 1.23+ and re-run." -ForegroundColor Red
    exit 1
}

Invoke-CaptureEnv
Initialize-Output
Invoke-EbpfGuardBench

# Add N/A rows for external agents (need Linux VM).
$ciNote = "CI: needs Linux VM with kernel 5.15+ — see bench/comparative/INSTALL.md"
foreach ($label in $SweepLabels) {
    Add-Result "Falco $FalcoVersion" "end-to-end" $label "N/A" "N/A" "N/A" "N/A" "N/A" $ciNote
    Add-Result "Tetragon $TetragonVersion" "end-to-end" $label "N/A" "N/A" "N/A" "N/A" "N/A" $ciNote
    Add-Result "Tracee $TraceeVersion" "end-to-end" $label "N/A" "N/A" "N/A" "N/A" "N/A" $ciNote
}

Write-Log ""
Write-Log "================================================================"
Write-Log "  Results written to:"
Write-Log "    CSV: $CsvFile"
Write-Log "    MD:  $MdFile"
Write-Log "    Env: $EnvFile"
Write-Log ""
Get-Content $MdFile | ForEach-Object { Write-Host $_ }
Write-Log "================================================================"
