// Package collector provides eBPF-based event collection from the kernel.
package collector

import (
	"bufio"
	"context"
	"encoding/binary"
	"fmt"
	"log/slog"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/zugolO/ebpf-guard/internal/exporter"
	"github.com/zugolO/ebpf-guard/pkg/types"
)

var gpuTrackedPIDsGauge = promauto.NewGauge(prometheus.GaugeOpts{
	Name: "ebpf_guard_gpu_tracked_pids_total",
	Help: "Current number of PIDs tracked by the GPU collector (processes with CUDA uprobes attached).",
})

// cudaLibraryPatterns lists substrings that identify CUDA libraries in /proc/[pid]/maps.
// Ordered from most specific to least specific to reduce false positives.
var cudaLibraryPatterns = []string{
	"libcuda.so",
	"libcudart.so",
	"libcuda-",    // versioned variants like libcuda-12.3.so
}

// gpuUprobeTargets maps CUDA symbol names to the BPF programs that should be attached.
// Each entry specifies whether the attachment is a uprobe (entry) or uretprobe (return).
type gpuUprobeSpec struct {
	symbol     string
	isRetprobe bool
}

var cudaDriverSymbols = []gpuUprobeSpec{
	{symbol: "cuMemAlloc_v2", isRetprobe: false},
	{symbol: "cuMemAlloc_v2", isRetprobe: true},
	{symbol: "cuMemFree_v2", isRetprobe: false},
	{symbol: "cuMemcpyDtoH_v2", isRetprobe: false},
	{symbol: "cuMemcpyDtoHAsync_v2", isRetprobe: false},
	{symbol: "cuMemcpyHtoD_v2", isRetprobe: false},
	{symbol: "cuMemcpyHtoDAsync_v2", isRetprobe: false},
	{symbol: "cuLaunchKernel", isRetprobe: false},
}

var cudaRuntimeSymbols = []gpuUprobeSpec{
	{symbol: "cudaMalloc", isRetprobe: false},
	{symbol: "cudaMalloc", isRetprobe: true},
	{symbol: "cudaFree", isRetprobe: false},
	{symbol: "cudaMemcpy", isRetprobe: false},
}

// gpuObjects holds eBPF objects for GPU collection (generated by bpf2go).
// Fields are populated by loadObjects once bpf2go codegen runs.
type gpuObjects struct {
	GpuEvents         *ebpf.Map     `ebpf:"gpu_events"`
	GpuAllocContexts  *ebpf.Map     `ebpf:"gpu_alloc_contexts"`
	TraceCuMemAllocEntry   *ebpf.Program `ebpf:"trace_cu_mem_alloc_entry"`
	TraceCuMemAllocRet     *ebpf.Program `ebpf:"trace_cu_mem_alloc_ret"`
	TraceCuMemFree         *ebpf.Program `ebpf:"trace_cu_mem_free"`
	TraceCuMemcpyDtoh      *ebpf.Program `ebpf:"trace_cu_memcpy_dtoh"`
	TraceCuMemcpyDtohAsync *ebpf.Program `ebpf:"trace_cu_memcpy_dtoh_async"`
	TraceCuMemcpyHtod      *ebpf.Program `ebpf:"trace_cu_memcpy_htod"`
	TraceCuMemcpyHtodAsync *ebpf.Program `ebpf:"trace_cu_memcpy_htod_async"`
	TraceCudaMallocEntry   *ebpf.Program `ebpf:"trace_cuda_malloc_entry"`
	TraceCudaMallocRet     *ebpf.Program `ebpf:"trace_cuda_malloc_ret"`
	TraceCudaFree          *ebpf.Program `ebpf:"trace_cuda_free"`
	TraceCudaMemcpy        *ebpf.Program `ebpf:"trace_cuda_memcpy"`
	TraceCuLaunchKernel    *ebpf.Program `ebpf:"trace_cu_launch_kernel"`
}

func (o *gpuObjects) Close() error {
	programs := []*ebpf.Program{
		o.TraceCuMemAllocEntry, o.TraceCuMemAllocRet, o.TraceCuMemFree,
		o.TraceCuMemcpyDtoh, o.TraceCuMemcpyDtohAsync,
		o.TraceCuMemcpyHtod, o.TraceCuMemcpyHtodAsync,
		o.TraceCudaMallocEntry, o.TraceCudaMallocRet, o.TraceCudaFree,
		o.TraceCudaMemcpy, o.TraceCuLaunchKernel,
	}
	maps := []*ebpf.Map{o.GpuEvents, o.GpuAllocContexts}

	var firstErr error
	for _, p := range programs {
		if p != nil {
			if err := p.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}
	for _, m := range maps {
		if m != nil {
			if err := m.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}
	return firstErr
}

// GPUEventRaw is the raw event structure from the BPF ring buffer.
// Layout must exactly match struct gpu_event in bpf/gpu_uprobe.bpf.c.
type GPUEventRaw struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	Op         uint8
	DevPtr     uint64
	HostPtr    uint64
	Size       uint64
}

// gpuEventRawSize is the wire size expected from the ring buffer.
// 4+8+4+4+4+4+16+16+1+8+8+8 = 85 bytes (packed, no padding).
const gpuEventRawSize = 85

// ToTypesEvent converts a raw BPF GPU event to the canonical types.Event.
func (e *GPUEventRaw) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventGPU,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		GPU: &types.GPUEvent{
			Op:      types.GPUOpType(e.Op),
			DevPtr:  e.DevPtr,
			HostPtr: e.HostPtr,
			Size:    e.Size,
		},
	}
}

// GPUCollector collects CUDA/GPU memory events using eBPF uprobes on libcuda.so
// and libcudart.so. It attaches to key CUDA Driver and Runtime API functions to
// detect data exfiltration via Device-to-Host memory copies in AI/ML workloads.
//
// Requirements:
//   - CAP_SYS_PTRACE capability for uprobe attachment
//   - NVIDIA CUDA libraries (libcuda.so or libcudart.so) in the target processes
//
// When no GPU workloads are present, the collector idles with zero overhead:
// the /proc scanner runs every 30s and finds no CUDA libraries to attach to.
type GPUCollector struct {
	logger          *slog.Logger
	objs            *gpuObjects
	links           []link.Link
	reader          *ringbuf.Reader
	loadError       error
	enabled         bool
	cudaPaths       map[uint32]string // pid → libcuda/libcudart path
	mu              sync.RWMutex
	scanInterval    time.Duration
	cleanupInterval time.Duration
	dropLogger      *dropLogger
	ctx             context.Context
	cancel          context.CancelFunc
	status          StatusReporter
	strategy        BackpressureStrategy
}

// NewGPUCollector creates a new GPU/CUDA event collector.
// The collector starts disabled. Call Start() to begin collection.
// If libcuda.so/libcudart.so are not present on the host, the collector idles
// harmlessly — it will simply never find any processes to attach to.
func NewGPUCollector(logger *slog.Logger, enabled bool) (*GPUCollector, error) {
	ctx, cancel := context.WithCancel(context.Background())

	return &GPUCollector{
		logger:          logger.With("collector", "gpu"),
		enabled:         enabled,
		cudaPaths:       make(map[uint32]string),
		scanInterval:    30 * time.Second,
		cleanupInterval: 60 * time.Second,
		dropLogger:      newDropLogger(5 * time.Second),
		ctx:             ctx,
		cancel:          cancel,
		status:          NoopStatusReporter{},
		strategy:        StrategyDrop,
	}, nil
}

// WithStatusReporter sets the StatusReporter used to signal up/down state.
func (c *GPUCollector) WithStatusReporter(r StatusReporter) *GPUCollector {
	c.status = r
	return c
}

// WithBackpressureStrategy sets the backpressure strategy for the event channel.
func (c *GPUCollector) WithBackpressureStrategy(s BackpressureStrategy) *GPUCollector {
	c.strategy = s
	return c
}

// Name returns the collector identifier.
func (c *GPUCollector) Name() string {
	return "gpu"
}

// Start attaches eBPF uprobes and begins sending events.
// Blocks until ctx is cancelled.
func (c *GPUCollector) Start(ctx context.Context, out chan<- types.Event) error {
	if !c.enabled {
		c.logger.Info("GPU collector disabled, skipping startup")
		c.status.SetUp("gpu", true)
		<-ctx.Done()
		return nil
	}

	c.logger.Info("starting GPU collector")

	if err := c.loadObjects(); err != nil {
		c.loadError = err
		c.status.SetUp("gpu", false)
		c.logger.Error("failed to load GPU eBPF objects, entering stub mode", slog.Any("error", err))
		<-ctx.Done()
		return nil
	}

	go c.discoveryLoop(ctx)
	go c.cleanupDeadPIDs(ctx)

	reader, err := ringbuf.NewReader(c.objs.GpuEvents)
	if err != nil {
		c.loadError = err
		c.status.SetUp("gpu", false)
		c.Close()
		c.logger.Error("failed to create ringbuf reader, entering stub mode", slog.Any("error", err))
		<-ctx.Done()
		return nil
	}
	c.reader = reader
	c.loadError = nil
	c.status.SetUp("gpu", true)

	go c.readLoop(ctx, out)

	<-ctx.Done()
	c.logger.Info("stopping GPU collector")
	return nil
}

// IsHealthy returns true if the collector loaded successfully.
func (c *GPUCollector) IsHealthy() bool {
	return !c.enabled || c.loadError == nil
}

// LoadError returns the error from a failed load, if any.
func (c *GPUCollector) LoadError() error {
	return c.loadError
}

// IsAttached returns true if at least one BPF uprobe is currently attached.
func (c *GPUCollector) IsAttached() bool {
	if c.objs == nil {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.links) > 0
}

// Close releases all eBPF resources.
func (c *GPUCollector) Close() error {
	c.logger.Info("closing GPU collector")
	c.cancel()

	if c.reader != nil {
		c.reader.Close()
		c.reader = nil
	}

	c.mu.Lock()
	for _, l := range c.links {
		l.Close()
	}
	c.links = nil
	c.mu.Unlock()

	if c.objs != nil {
		c.objs.Close()
		c.objs = nil
	}

	return nil
}

// loadObjects loads the eBPF objects generated by bpf2go.
// In production, bpf2go generates a loadGpuObjects() function from gpu_uprobe.bpf.c.
// Until that code is generated (requires `make generate`), this returns an error
// that places the collector in stub mode.
func (c *GPUCollector) loadObjects() error {
	return fmt.Errorf("GPU eBPF objects not yet compiled (run: make generate)")
}

// discoveryLoop periodically scans for processes using CUDA libraries and attaches uprobes.
func (c *GPUCollector) discoveryLoop(ctx context.Context) {
	ticker := time.NewTicker(c.scanInterval)
	defer ticker.Stop()

	c.scanAndAttach()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.scanAndAttach()
		}
	}
}

// cleanupDeadPIDs removes entries for processes that no longer exist.
func (c *GPUCollector) cleanupDeadPIDs(ctx context.Context) {
	ticker := time.NewTicker(c.cleanupInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.mu.Lock()
			for pid := range c.cudaPaths {
				if _, err := os.Stat(fmt.Sprintf("/proc/%d", pid)); os.IsNotExist(err) {
					delete(c.cudaPaths, pid)
				}
			}
			gpuTrackedPIDsGauge.Set(float64(len(c.cudaPaths)))
			c.mu.Unlock()
		}
	}
}

// scanAndAttach scans /proc for processes using CUDA libraries and attaches uprobes.
func (c *GPUCollector) scanAndAttach() {
	entries, err := os.ReadDir("/proc")
	if err != nil {
		c.logger.Warn("failed to read /proc", slog.Any("error", err))
		return
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pid, err := strconv.ParseUint(entry.Name(), 10, 32)
		if err != nil {
			continue
		}

		c.mu.RLock()
		_, alreadyAttached := c.cudaPaths[uint32(pid)]
		c.mu.RUnlock()
		if alreadyAttached {
			continue
		}

		cudaPath, libKind := c.findCUDALibInPID(uint32(pid))
		if cudaPath == "" {
			continue
		}

		if err := c.attachToPID(uint32(pid), cudaPath, libKind); err != nil {
			if c.logger.Enabled(c.ctx, slog.LevelDebug) {
				c.logger.Debug("failed to attach GPU uprobes",
					slog.Uint64("pid", pid),
					slog.String("cuda_lib", cudaPath),
					slog.Any("error", err))
			}
			continue
		}

		c.mu.Lock()
		c.cudaPaths[uint32(pid)] = cudaPath
		gpuTrackedPIDsGauge.Set(float64(len(c.cudaPaths)))
		c.mu.Unlock()

		c.logger.Info("attached GPU uprobes",
			slog.Uint64("pid", pid),
			slog.String("cuda_lib", cudaPath),
			slog.String("lib_kind", libKind))
	}
}

// findCUDALibInPID searches for CUDA libraries in a process's memory maps.
// Returns the library path and a kind string ("driver" or "runtime").
func (c *GPUCollector) findCUDALibInPID(pid uint32) (path, kind string) {
	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	file, err := os.Open(mapsPath)
	if err != nil {
		return "", ""
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Fields(line)
		if len(parts) < 6 {
			continue
		}
		libPath := parts[len(parts)-1]
		if !strings.HasPrefix(libPath, "/") || strings.Contains(libPath, "(deleted)") {
			continue
		}

		for _, pattern := range cudaLibraryPatterns {
			if strings.Contains(libPath, pattern) {
				if strings.Contains(libPath, "libcuda.so") || strings.Contains(libPath, "libcuda-") {
					return libPath, "driver"
				}
				return libPath, "runtime"
			}
		}
	}
	return "", ""
}

// attachToPID attaches uprobes to CUDA functions in a process.
// libKind is "driver" (libcuda.so) or "runtime" (libcudart.so).
func (c *GPUCollector) attachToPID(pid uint32, libPath, libKind string) error {
	if c.objs == nil {
		return fmt.Errorf("eBPF objects not loaded")
	}

	ex, err := link.OpenExecutable(libPath)
	if err != nil {
		return fmt.Errorf("open executable %s: %w", libPath, err)
	}

	var specs []gpuUprobeSpec
	if libKind == "driver" {
		specs = cudaDriverSymbols
	} else {
		specs = cudaRuntimeSymbols
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	opts := &link.UprobeOptions{PID: int(pid)}

	for _, spec := range specs {
		prog := c.programForSymbol(spec.symbol, spec.isRetprobe)
		if prog == nil {
			continue
		}

		var l link.Link
		if spec.isRetprobe {
			l, err = ex.Uretprobe(spec.symbol, prog, opts)
		} else {
			l, err = ex.Uprobe(spec.symbol, prog, opts)
		}
		if err != nil {
			c.logger.Debug("uprobe attach failed",
				slog.String("symbol", spec.symbol),
				slog.Bool("retprobe", spec.isRetprobe),
				slog.Any("error", err))
			continue
		}
		c.links = append(c.links, l)
	}

	return nil
}

// programForSymbol returns the eBPF program corresponding to a symbol name and
// whether it is a return probe.
func (c *GPUCollector) programForSymbol(symbol string, isRetprobe bool) *ebpf.Program {
	switch symbol {
	case "cuMemAlloc_v2":
		if isRetprobe {
			return c.objs.TraceCuMemAllocRet
		}
		return c.objs.TraceCuMemAllocEntry
	case "cuMemFree_v2":
		return c.objs.TraceCuMemFree
	case "cuMemcpyDtoH_v2":
		return c.objs.TraceCuMemcpyDtoh
	case "cuMemcpyDtoHAsync_v2":
		return c.objs.TraceCuMemcpyDtohAsync
	case "cuMemcpyHtoD_v2":
		return c.objs.TraceCuMemcpyHtod
	case "cuMemcpyHtoDAsync_v2":
		return c.objs.TraceCuMemcpyHtodAsync
	case "cuLaunchKernel":
		return c.objs.TraceCuLaunchKernel
	case "cudaMalloc":
		if isRetprobe {
			return c.objs.TraceCudaMallocRet
		}
		return c.objs.TraceCudaMallocEntry
	case "cudaFree":
		return c.objs.TraceCudaFree
	case "cudaMemcpy":
		return c.objs.TraceCudaMemcpy
	}
	return nil
}

// readLoop reads events from the ring buffer and forwards them to the output channel.
func (c *GPUCollector) readLoop(ctx context.Context, out chan<- types.Event) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		record, err := c.reader.Read()
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			c.logger.Error("failed to read from GPU ringbuf", slog.Any("error", err))
			continue
		}

		event, err := c.parseEvent(record.RawSample)
		if err != nil {
			c.logger.Error("failed to parse GPU event", slog.Any("error", err))
			exporter.RecordDropped("gpu", "parse_error")
			continue
		}

		if c.logger.Enabled(ctx, slog.LevelDebug) {
			c.logger.Debug("GPU event",
				slog.Uint64("pid", uint64(event.PID)),
				slog.Uint64("op", uint64(event.GPU.Op)),
				slog.Uint64("size", event.GPU.Size))
		}

		sendEvent(ctx, out, *event, c.strategy, func() {
			exporter.RecordDropped("gpu", "channel_full")
			c.dropLogger.record(c.logger, "gpu")
		})
	}
}

// parseEvent converts raw ring buffer bytes to a types.Event.
func (c *GPUCollector) parseEvent(raw []byte) (*types.Event, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("event too short: %d bytes", len(raw))
	}

	eventType := binary.LittleEndian.Uint32(raw[0:4])
	if eventType != uint32(types.EventGPU) {
		return nil, fmt.Errorf("unexpected event type: %d", eventType)
	}

	if len(raw) < gpuEventRawSize {
		return nil, fmt.Errorf("GPU event too short: %d bytes (need %d)", len(raw), gpuEventRawSize)
	}

	// The C struct is declared __attribute__((packed)) so there is no alignment
	// padding between fields. binary.Read on the Go struct would insert 4 bytes
	// after Type (to align Timestamp) and 7 bytes after Op (to align DevPtr),
	// reading 96 bytes instead of 85 and producing garbage field values.
	// Parse at the exact packed offsets instead.
	var rawEvent GPUEventRaw
	rawEvent.Type      = binary.LittleEndian.Uint32(raw[0:4])
	rawEvent.Timestamp = binary.LittleEndian.Uint64(raw[4:12])
	rawEvent.PID       = binary.LittleEndian.Uint32(raw[12:16])
	rawEvent.TGID      = binary.LittleEndian.Uint32(raw[16:20])
	rawEvent.PPID      = binary.LittleEndian.Uint32(raw[20:24])
	rawEvent.UID       = binary.LittleEndian.Uint32(raw[24:28])
	copy(rawEvent.Comm[:], raw[28:44])
	copy(rawEvent.ParentComm[:], raw[44:60])
	rawEvent.Op      = raw[60]
	rawEvent.DevPtr  = binary.LittleEndian.Uint64(raw[61:69])
	rawEvent.HostPtr = binary.LittleEndian.Uint64(raw[69:77])
	rawEvent.Size    = binary.LittleEndian.Uint64(raw[77:85])

	result := rawEvent.ToTypesEvent()
	return &result, nil
}

// GetAttachedPIDs returns the PIDs that currently have GPU uprobes attached.
func (c *GPUCollector) GetAttachedPIDs() []uint32 {
	c.mu.RLock()
	defer c.mu.RUnlock()

	pids := make([]uint32, 0, len(c.cudaPaths))
	for pid := range c.cudaPaths {
		pids = append(pids, pid)
	}
	return pids
}
