// Package collector provides eBPF-based event collection from the kernel.
package collector

import (
	"bufio"
	"bytes"
	"context"
	"debug/elf"
	"encoding/binary"
	"fmt"
	"log/slog"
	"os"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/zugolO/ebpf-guard/internal/bpf"
	"github.com/zugolO/ebpf-guard/internal/exporter"
	"github.com/zugolO/ebpf-guard/pkg/types"
)

var httpTrackedPIDsGauge = promauto.NewGauge(prometheus.GaugeOpts{
	Name: "ebpf_guard_http_plaintext_tracked_pids_total",
	Help: "Current number of PIDs tracked by the plaintext HTTP collector (web-server processes with libc read/recv uprobes attached).",
})

// defaultHTTPServerComms is the default allow-list of process names the
// HTTPCollector attaches to. Hooking libc read()/recv() on every process on
// the host would be prohibitively expensive and noisy (virtually everything
// calls read()); scoping to known web-server/runtime binaries keeps overhead
// bounded while still covering the plaintext-HTTP gap from issue #281.
var defaultHTTPServerComms = []string{
	"nginx", "apache2", "httpd", "node", "python", "python3",
	"php-fpm", "php-fpm7", "php-fpm8", "ruby", "java",
	"gunicorn", "uwsgi", "caddy", "traefik", "lighttpd",
}

// HTTPCollector collects plaintext (non-TLS) HTTP request/response bytes using
// eBPF uprobes on libc read/recv in known web-server processes. It complements
// TLSCollector: TLSCollector sees data before/after OpenSSL encryption, while
// HTTPCollector sees data for connections that never use TLS at all.
//
// Requirements:
//   - CAP_SYS_PTRACE capability for uprobe attachment
//   - Target process must be in the configured comm allow-list (default:
//     defaultHTTPServerComms) and must use libc read()/recv() to receive data
//
// Limitations:
//   - Only captures data that looks like an HTTP request/status line (filtered
//     in-kernel — see bpf/http_uprobe.bpf.c); other read()/recv() traffic in the
//     same process is never submitted to the ring buffer.
//   - Only captures first 256 bytes of each matching read()/recv() call.
//   - Does not see data read via readv/recvmsg/io_uring, or app-level TLS
//     libraries other than OpenSSL/libssl (handled separately by TLSCollector).
type HTTPCollector struct {
	logger          *slog.Logger
	objs            *httpObjects
	links           []link.Link
	reader          *ringbuf.Reader
	loadError       error
	enabled         bool
	serverComms     map[string]bool   // process names to attach to
	attachedPaths   map[uint32]string // pid -> exe path
	mu              sync.RWMutex
	scanInterval    time.Duration
	cleanupInterval time.Duration
	maxDataSize     int // bytes of plaintext exposed downstream (default 256)
	dropLogger      *dropLogger
	ctx             context.Context
	cancel          context.CancelFunc
	status          StatusReporter
	strategy        BackpressureStrategy
	ringBufSize     int // 0 = auto-detect
	lostTotal       atomic.Uint64
}

// httpObjects holds eBPF objects for plaintext HTTP collection (generated by bpf2go).
type httpObjects struct {
	HttpEvents       *ebpf.Map     `ebpf:"http_events"`
	HttpReadContexts *ebpf.Map     `ebpf:"http_read_contexts"`
	TraceReadEntry   *ebpf.Program `ebpf:"trace_read_entry"`
	TraceReadRet     *ebpf.Program `ebpf:"trace_read_ret"`
	TraceRecvEntry   *ebpf.Program `ebpf:"trace_recv_entry"`
	TraceRecvRet     *ebpf.Program `ebpf:"trace_recv_ret"`
}

// Close releases all eBPF resources.
func (o *httpObjects) Close() error {
	return closeHTTPObjects(o)
}

func closeHTTPObjects(objs *httpObjects) error {
	var errs []error
	if objs.TraceReadEntry != nil {
		errs = append(errs, objs.TraceReadEntry.Close())
	}
	if objs.TraceReadRet != nil {
		errs = append(errs, objs.TraceReadRet.Close())
	}
	if objs.TraceRecvEntry != nil {
		errs = append(errs, objs.TraceRecvEntry.Close())
	}
	if objs.TraceRecvRet != nil {
		errs = append(errs, objs.TraceRecvRet.Close())
	}
	if objs.HttpEvents != nil {
		errs = append(errs, objs.HttpEvents.Close())
	}
	if objs.HttpReadContexts != nil {
		errs = append(errs, objs.HttpReadContexts.Close())
	}

	for _, err := range errs {
		if err != nil {
			return err
		}
	}
	return nil
}

// HTTPEventRaw is the raw event structure from BPF (mirrors struct http_event
// in bpf/http_uprobe.bpf.c).
type HTTPEventRaw struct {
	Type        uint32
	Timestamp   uint64
	PID         uint32
	TGID        uint32
	PPID        uint32
	UID         uint32
	Comm        [16]byte
	ParentComm  [16]byte
	Direction   uint8
	DataLen     uint32
	CapturedLen uint32
	Data        [256]byte
}

// httpEventRawSize is the wire size of struct http_event (bpf/http_uprobe.bpf.c,
// __attribute__((packed))). It is DERIVED from the Go mirror above and is never
// written as a literal.
//
// №471 (25.09.2026, первый живой прогон коллектора за историю проекта). Здесь
// стояло `len(raw) < 340` с комментарием «same layout as TLS event» — но
// tls_event несёт ещё 37 байт информации о соединении (has_conn_info, saddr,
// daddr, sport, dport), а http_event весит ровно 325. Ring buffer отдавал
// 325-байтовые события, проверка длины отбивала КАЖДОЕ, и
// ebpf_guard_events_dropped_total{collector="http_plaintext",reason="parse_error"}
// рос при нуле в events_total. Ни одного события за всю историю — при живом
// хуке, живом ring buffer и совпадающей раскладке: `binary.Read` читает без
// выравнивания и разобрал бы эти 325 байт без правок. Величина, от которой
// зависит вердикт, обязана вычисляться из структуры, а не повторяться цифрой
// ([[verdict-input-must-be-computed-by-emitter]] в приборной форме).
var httpEventRawSize = binary.Size(HTTPEventRaw{})

// ToTypesEvent converts a raw plaintext HTTP event to the public types.Event.
func (e *HTTPEventRaw) ToTypesEvent() types.Event {
	var direction types.HTTPDirection
	if e.Direction == 0 {
		direction = types.HTTPDirectionRequest
	} else {
		direction = types.HTTPDirectionResponse
	}

	return types.Event{
		Type:       types.EventHTTPPlaintext,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		HTTPPlaintext: &types.HTTPEvent{
			Direction: direction,
			DataLen:   e.DataLen,
			// №444: the kernel already filled captured_len; dropping it here is
			// what made collectors.http_plaintext.max_data_size a no-op and left
			// consumers slicing Data[:DataLen].
			CapturedLen: e.CapturedLen,
			CapturedSet: true,
			Data:        e.Data,
		},
	}
}

// NewHTTPCollector creates a new plaintext HTTP event collector.
//
// The collector starts disabled. Call Start() to begin collection.
// If the collector fails to load (e.g., missing CAP_SYS_PTRACE), it enters
// "stub mode" where IsHealthy() returns false but the collector continues
// to run without crashing.
//
// serverComms is the list of process names (comm) to attach uprobes to. If
// empty, defaultHTTPServerComms is used.
func NewHTTPCollector(logger *slog.Logger, enabled bool, serverComms []string) (*HTTPCollector, error) {
	ctx, cancel := context.WithCancel(context.Background())

	if len(serverComms) == 0 {
		serverComms = defaultHTTPServerComms
	}
	commSet := make(map[string]bool, len(serverComms))
	for _, c := range serverComms {
		commSet[c] = true
	}

	return &HTTPCollector{
		logger:          logger.With("collector", "http_plaintext"),
		enabled:         enabled,
		serverComms:     commSet,
		attachedPaths:   make(map[uint32]string),
		scanInterval:    30 * time.Second,
		cleanupInterval: 60 * time.Second,
		maxDataSize:     256,
		dropLogger:      newDropLogger(5 * time.Second),
		ctx:             ctx,
		cancel:          cancel,
		status:          NoopStatusReporter{},
		strategy:        StrategyDrop,
	}, nil
}

// WithStatusReporter sets the StatusReporter used to signal up/down state.
func (c *HTTPCollector) WithStatusReporter(r StatusReporter) *HTTPCollector {
	c.status = r
	return c
}

// WithBackpressureStrategy sets the backpressure strategy for the event channel.
func (c *HTTPCollector) WithBackpressureStrategy(s BackpressureStrategy) *HTTPCollector {
	c.strategy = s
	return c
}

// WithRingBufSize sets the BPF ring buffer size in bytes for this collector.
// Zero (default) auto-detects the size from /proc/meminfo.
func (c *HTTPCollector) WithRingBufSize(sizeBytes int) *HTTPCollector {
	c.ringBufSize = sizeBytes
	return c
}

// WithScanInterval overrides the web-server discovery scan interval
// (collectors.http_plaintext.scan_interval). Non-positive durations keep the
// default. Finding №444: this value and max_data_size below were declared in
// config and silently dropped, exactly as collectors.tls's were before item 7
// of wave 6.4.B — the sibling file had to be fixed with it.
func (c *HTTPCollector) WithScanInterval(d time.Duration) *HTTPCollector {
	if d > 0 {
		c.scanInterval = d
	}
	return c
}

// WithMaxDataSize overrides how many captured plaintext bytes are exposed
// downstream (collectors.http_plaintext.max_data_size). The kernel caps
// capture at 256 bytes, so larger values do not capture more; smaller values
// truncate the buffer before it reaches rules, alerts and the store.
// Non-positive values keep the default.
func (c *HTTPCollector) WithMaxDataSize(n int) *HTTPCollector {
	if n > 0 {
		c.maxDataSize = n
	}
	return c
}

// applyMaxDataSize windows the captured plaintext to at most c.maxDataSize
// bytes and returns the effective captured length, by the same contract as
// TLSCollector.applyMaxDataSize: DataLen keeps the true read()/recv() length
// that `data_len` rules compare against, the window is carried by
// CapturedLen/CapturedSet, and an explicit zero capture zeroes Data instead of
// exposing stale ring-buffer bytes (№443/№444).
func (c *HTTPCollector) applyMaxDataSize(e *types.HTTPEvent) uint32 {
	capturedLen := e.CapturedLen
	if capturedLen > uint32(len(e.Data)) {
		capturedLen = uint32(len(e.Data))
	}
	e.CapturedSet = true
	if capturedLen == 0 {
		for i := range e.Data {
			e.Data[i] = 0
		}
		e.CapturedLen = 0
		return 0
	}
	if c.maxDataSize > 0 && capturedLen > uint32(c.maxDataSize) {
		capturedLen = uint32(c.maxDataSize)
		for i := capturedLen; i < uint32(len(e.Data)); i++ {
			e.Data[i] = 0
		}
	}
	e.CapturedLen = capturedLen
	return capturedLen
}

// Name returns the collector identifier.
func (c *HTTPCollector) Name() string {
	return "http_plaintext"
}

// Start attaches eBPF uprobes and begins sending events.
// Blocks until ctx is cancelled.
//
// If the collector is disabled (enabled=false in config), this returns immediately
// without loading any eBPF programs.
func (c *HTTPCollector) Start(ctx context.Context, out chan<- types.Event) error {
	if !c.enabled {
		c.logger.Info("plaintext HTTP collector disabled, skipping startup")
		c.status.SetUp("http_plaintext", true) // Mark as "up" but idle
		<-ctx.Done()
		return nil
	}

	c.logger.Info("starting plaintext HTTP collector")

	if err := c.loadObjects(); err != nil {
		c.loadError = err
		c.status.SetUp("http_plaintext", false)
		c.logger.Error("failed to load HTTP eBPF objects, entering stub mode", slog.Any("error", err))
		<-ctx.Done()
		return nil
	}

	go c.discoveryLoop(ctx)
	go c.cleanupDeadPIDs(ctx)

	reader, err := ringbuf.NewReader(c.objs.HttpEvents)
	if err != nil {
		c.loadError = err
		c.status.SetUp("http_plaintext", false)
		c.Close()
		c.logger.Error("failed to create ringbuf reader, entering stub mode", slog.Any("error", err))
		<-ctx.Done()
		return nil
	}
	c.reader = reader
	c.loadError = nil
	c.status.SetUp("http_plaintext", true)

	readLoopDone := runReadLoop(func() { c.readLoop(ctx, out) })

	// Wait for context cancellation, then for readLoop to actually stop
	// sending (5.8d) — Close() unblocks the ring buffer Read() readLoop may
	// be parked in, and Close() runs after ctx is already done.
	<-ctx.Done()
	c.logger.Info("stopping plaintext HTTP collector")
	<-readLoopDone
	return nil
}

// IsHealthy returns true if the collector loaded successfully.
func (c *HTTPCollector) IsHealthy() bool {
	return !c.enabled || c.loadError == nil
}

// LoadError returns the error from failed load, if any.
func (c *HTTPCollector) LoadError() error {
	return c.loadError
}

// IsAttached returns true if the BPF program is still attached.
func (c *HTTPCollector) IsAttached() bool {
	if c.objs == nil {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.links) > 0
}

// Close releases all eBPF resources.
func (c *HTTPCollector) Close() error {
	c.logger.Info("closing plaintext HTTP collector")
	c.cancel()

	if c.reader != nil {
		c.reader.Close()
		c.reader = nil
	}

	c.mu.Lock()
	for _, l := range c.links {
		l.Close()
	}
	c.links = nil
	c.mu.Unlock()

	if c.objs != nil {
		c.objs.Close()
		c.objs = nil
	}

	return nil
}

// loadObjects loads the eBPF objects generated by bpf2go from
// bpf/http_uprobe.bpf.c. №442: before this the function was an unconditional
// stub with discoveryLoop behind it, so an enabled http_plaintext collector
// reported collector_up=1 while producing zero events. The http_events ring
// buffer size is applied to the spec BEFORE loading, because max_entries is
// fixed at map-creation time.
func (c *HTTPCollector) loadObjects() error {
	ringSize := bpf.ComputeRingBufSize(bpf.RingBufSizeConfig{SizeBytes: c.ringBufSize})
	c.logger.Info("HTTP plaintext collector ring buffer size", slog.Int("bytes", ringSize))

	spec, err := bpf.LoadHttpUprobe()
	if err != nil {
		return fmt.Errorf("load http_uprobe spec: %w", err)
	}
	mapSpec, ok := spec.Maps["http_events"]
	if !ok || mapSpec == nil {
		return fmt.Errorf("http_uprobe spec has no http_events map")
	}
	mapSpec.MaxEntries = uint32(ringSize)

	objs := &bpf.HttpUprobeObjects{}
	if err := spec.LoadAndAssign(objs, nil); err != nil {
		return fmt.Errorf("load http_uprobe objects: %w", err)
	}

	c.objs = &httpObjects{
		HttpEvents:       objs.HttpEvents,
		HttpReadContexts: objs.HttpReadContexts,
		TraceReadEntry:   objs.TraceReadEntry,
		TraceReadRet:     objs.TraceReadRet,
		TraceRecvEntry:   objs.TraceRecvEntry,
		TraceRecvRet:     objs.TraceRecvRet,
	}
	return nil
}

// discoveryLoop periodically scans for known web-server processes and attaches uprobes.
func (c *HTTPCollector) discoveryLoop(ctx context.Context) {
	ticker := time.NewTicker(c.scanInterval)
	defer ticker.Stop()

	c.scanAndAttach()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.scanAndAttach()
		}
	}
}

// cleanupDeadPIDs periodically removes entries for processes that no longer exist.
func (c *HTTPCollector) cleanupDeadPIDs(ctx context.Context) {
	ticker := time.NewTicker(c.cleanupInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.mu.Lock()
			for pid := range c.attachedPaths {
				if _, err := os.Stat(fmt.Sprintf("/proc/%d", pid)); os.IsNotExist(err) {
					delete(c.attachedPaths, pid)
				}
			}
			httpTrackedPIDsGauge.Set(float64(len(c.attachedPaths)))
			c.mu.Unlock()
		}
	}
}

// scanAndAttach scans /proc for known web-server processes and attaches uprobes.
func (c *HTTPCollector) scanAndAttach() {
	entries, err := os.ReadDir("/proc")
	if err != nil {
		c.logger.Warn("failed to read /proc", slog.Any("error", err))
		return
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pid, err := strconv.ParseUint(entry.Name(), 10, 32)
		if err != nil {
			continue
		}

		c.mu.RLock()
		_, alreadyAttached := c.attachedPaths[uint32(pid)]
		c.mu.RUnlock()
		if alreadyAttached {
			continue
		}

		if !c.isKnownServerProcess(uint32(pid)) {
			continue
		}

		exePath := fmt.Sprintf("/proc/%d/exe", pid)
		if err := c.attachToPID(uint32(pid)); err != nil {
			if c.logger.Enabled(c.ctx, slog.LevelDebug) {
				c.logger.Debug("failed to attach uprobes",
					slog.Uint64("pid", pid),
					slog.Any("error", err))
			}
			continue
		}

		c.mu.Lock()
		c.attachedPaths[uint32(pid)] = exePath
		httpTrackedPIDsGauge.Set(float64(len(c.attachedPaths)))
		c.mu.Unlock()

		c.logger.Info("attached plaintext HTTP uprobes", slog.Uint64("pid", pid))
	}
}

// isKnownServerProcess reads /proc/PID/comm and checks it against the
// configured web-server allow-list.
func (c *HTTPCollector) isKnownServerProcess(pid uint32) bool {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/comm", pid))
	if err != nil {
		return false
	}
	comm := strings.TrimSpace(string(data))
	return c.serverComms[comm]
}

// attachToPID attaches uprobes to libc read/recv for a process's libc.so.
func (c *HTTPCollector) attachToPID(pid uint32) error {
	if c.objs == nil {
		return fmt.Errorf("eBPF objects not loaded")
	}

	libcPath := c.findLibcInPID(pid)
	if libcPath == "" {
		return fmt.Errorf("libc not found for pid %d", pid)
	}

	// Verify that the required symbols exist in libc
	f, err := elf.Open(libcPath)
	if err != nil {
		return fmt.Errorf("open elf: %w", err)
	}
	defer f.Close()

	symbols, err := f.DynamicSymbols()
	if err != nil {
		return fmt.Errorf("get symbols: %w", err)
	}

	hasRead := false
	hasRecv := false
	for _, sym := range symbols {
		if sym.Name == "read" {
			hasRead = true
		}
		if sym.Name == "recv" {
			hasRecv = true
		}
	}

	if !hasRead && !hasRecv {
		return fmt.Errorf("read and recv symbols not found in %s", libcPath)
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	// Attach read uprobes (entry + return)
	if hasRead && c.objs.TraceReadEntry != nil && c.objs.TraceReadRet != nil {
		l, err := c.attachUprobe(libcPath, "read", c.objs.TraceReadEntry)
		if err != nil {
			return fmt.Errorf("attach read entry: %w", err)
		}
		c.links = append(c.links, l)

		l, err = c.attachUretprobe(libcPath, "read", c.objs.TraceReadRet)
		if err != nil {
			return fmt.Errorf("attach read ret: %w", err)
		}
		c.links = append(c.links, l)
	}

	// Attach recv uprobes (entry + return)
	if hasRecv && c.objs.TraceRecvEntry != nil && c.objs.TraceRecvRet != nil {
		l, err := c.attachUprobe(libcPath, "recv", c.objs.TraceRecvEntry)
		if err != nil {
			return fmt.Errorf("attach recv entry: %w", err)
		}
		c.links = append(c.links, l)

		l, err = c.attachUretprobe(libcPath, "recv", c.objs.TraceRecvRet)
		if err != nil {
			return fmt.Errorf("attach recv ret: %w", err)
		}
		c.links = append(c.links, l)
	}

	return nil
}

// findLibcInPID searches for libc.so in a process's memory maps.
func (c *HTTPCollector) findLibcInPID(pid uint32) string {
	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	file, err := os.Open(mapsPath)
	if err != nil {
		return ""
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.Contains(line, "libc.so") || strings.Contains(line, "libc-") {
			parts := strings.Fields(line)
			if len(parts) >= 6 {
				path := parts[len(parts)-1]
				if strings.HasPrefix(path, "/") && !strings.Contains(path, "(deleted)") {
					return path
				}
			}
		}
	}

	return ""
}

// attachUprobe attaches a uprobe to the specified function in a shared library.
// Uses link.OpenExecutable to resolve the symbol and attach the BPF program.
func (c *HTTPCollector) attachUprobe(libPath string, symbol string, prog *ebpf.Program) (link.Link, error) {
	ex, err := link.OpenExecutable(libPath)
	if err != nil {
		return nil, fmt.Errorf("open executable %s: %w", libPath, err)
	}

	// Attach to all processes (no PID filter) - the caller is responsible for
	// ensuring the target process is in the configured allow-list.
	l, err := ex.Uprobe(symbol, prog, nil)
	if err != nil {
		return nil, fmt.Errorf("attach uprobe %s: %w", symbol, err)
	}
	return l, nil
}

// attachUretprobe attaches a uretprobe to the specified function in a shared library.
func (c *HTTPCollector) attachUretprobe(libPath string, symbol string, prog *ebpf.Program) (link.Link, error) {
	ex, err := link.OpenExecutable(libPath)
	if err != nil {
		return nil, fmt.Errorf("open executable %s: %w", libPath, err)
	}

	// Attach to all processes (no PID filter) - the caller is responsible for
	// ensuring the target process is in the configured allow-list.
	l, err := ex.Uretprobe(symbol, prog, nil)
	if err != nil {
		return nil, fmt.Errorf("attach uretprobe %s: %w", symbol, err)
	}
	return l, nil
}

// readLoop reads events from the ring buffer and sends them to the output channel.
func (c *HTTPCollector) readLoop(ctx context.Context, out chan<- types.Event) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		record, err := c.reader.Read()
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			c.logger.Error("failed to read from ringbuf", slog.Any("error", err))
			continue
		}

		event, err := c.parseEvent(record.RawSample)
		if err != nil {
			c.logger.Error("failed to parse event", slog.Any("error", err))
			exporter.RecordDropped("http_plaintext", "parse_error")
			continue
		}

		// Same W3C Trace Context extraction and sensitive-header masking as the
		// TLS collector (internal/collector/tls.go) — this data is genuine HTTP
		// header bytes, just captured before it would have hit TLS.
		if event.HTTPPlaintext != nil {
			capturedLen := c.applyMaxDataSize(event.HTTPPlaintext)
			if tc := ExtractTraceContext(event.HTTPPlaintext.Data[:capturedLen]); tc != nil {
				event.TraceContext = tc
			}
			maskSensitiveHeaders(event.HTTPPlaintext.Data[:capturedLen])
		}

		if c.logger.Enabled(ctx, slog.LevelDebug) {
			c.logger.Debug("plaintext HTTP event",
				slog.Uint64("pid", uint64(event.PID)),
				slog.Uint64("data_len", uint64(event.HTTPPlaintext.DataLen)))
		}

		sendEvent(ctx, out, *event, c.strategy, func() {
			exporter.RecordEventDrop("http_plaintext", "ringbuf_to_router", defaultEventPriority(event.Type))
			c.dropLogger.record(c.logger, "ringbuf_to_router")
			c.lostTotal.Add(1)
		})
	}
}

// LostEvents returns the total number of events lost in the BPF ring buffer
// since the collector started. Implements watchdog.DropTracker.
func (c *HTTPCollector) LostEvents() uint64 {
	return c.lostTotal.Load()
}

// parseEvent converts raw bytes from ring buffer to types.Event.
func (c *HTTPCollector) parseEvent(raw []byte) (*types.Event, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("event too short: %d bytes", len(raw))
	}

	eventType := binary.LittleEndian.Uint32(raw[0:4])
	if eventType != uint32(types.EventHTTPPlaintext) {
		return nil, fmt.Errorf("unexpected event type: %d", eventType)
	}

	if len(raw) < httpEventRawSize {
		return nil, fmt.Errorf("HTTP event too short: %d bytes (need %d)", len(raw), httpEventRawSize)
	}

	var rawEvent HTTPEventRaw
	buf := bytes.NewReader(raw)
	if err := binary.Read(buf, binary.LittleEndian, &rawEvent); err != nil {
		return nil, fmt.Errorf("parse raw event: %w", err)
	}

	result := rawEvent.ToTypesEvent()
	return &result, nil
}

// GetAttachedPIDs returns the list of PIDs that have uprobes attached.
func (c *HTTPCollector) GetAttachedPIDs() []uint32 {
	c.mu.RLock()
	defer c.mu.RUnlock()

	pids := make([]uint32, 0, len(c.attachedPaths))
	for pid := range c.attachedPaths {
		pids = append(pids, pid)
	}
	return pids
}
