// lsm.go — eBPF LSM hook collectors
//
// LSMCollector  (Sprint 22.0): loads file_open / socket_connect / task_kill
//   hooks for pre-execution enforcement.
// KmodCollector (Sprint 33.0): reads kernel_module_request / kernel_read_file
//   and cgroup_attach_task events and forwards them to the correlation engine.

package collector

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"github.com/zugolO/ebpf-guard/internal/bpf"
	"github.com/zugolO/ebpf-guard/pkg/types"
	"github.com/prometheus/client_golang/prometheus"
)

// LSMConfig holds configuration for the LSM collector.
type LSMConfig struct {
	// Enabled controls LSM hook loading:
	// "auto" - load if kernel supports (default)
	// "true" - require kernel support, fail if unavailable
	// "false" - disable LSM hooks
	Enabled string `mapstructure:"enabled"`
}

// DefaultLSMConfig returns default LSM configuration.
func DefaultLSMConfig() LSMConfig {
	return LSMConfig{
		Enabled: "auto",
	}
}

// LSMCollector manages eBPF LSM hooks for pre-execution enforcement.
type LSMCollector struct {
	config    LSMConfig
	logger    *slog.Logger
	objs      *lsmObjects
	links     []link.Link
	available bool
	mu        sync.RWMutex

	// Metrics
	blocksTotal *prometheus.CounterVec
}

// lsmObjects contains all eBPF objects for LSM hooks.
// This will be generated by bpf2go.
type lsmObjects struct {
	LsmBlocklist      *ebpf.Map `ebpf:"lsm_blocklist"`
	LsmAgentWhitelist *ebpf.Map `ebpf:"lsm_agent_whitelist"`
	LsmStats          *ebpf.Map `ebpf:"lsm_stats"`
}

// NewLSMCollector creates a new LSM collector.
func NewLSMCollector(config LSMConfig, logger *slog.Logger) (*LSMCollector, error) {
	if logger == nil {
		logger = slog.Default()
	}

	lc := &LSMCollector{
		config: config,
		logger: logger,
		links:  make([]link.Link, 0),
		blocksTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "ebpf_guard_lsm_blocks_total",
			Help: "Total number of LSM hook invocations and blocking decisions",
		}, []string{"hook", "action"}),
	}

	// Check availability
	available := lc.checkAvailability()
	lc.available = available

	if !available {
		if config.Enabled == "true" {
			return nil, fmt.Errorf("lsm: kernel does not support LSM BPF (required but disabled)")
		}
		logger.Info("lsm: kernel does not support LSM BPF, collector in stub mode")
		return lc, nil
	}

	if config.Enabled == "false" {
		logger.Info("lsm: LSM BPF disabled by configuration")
		lc.available = false
		return lc, nil
	}

	logger.Info("lsm: LSM BPF is available")
	return lc, nil
}

// checkAvailability checks if the kernel supports LSM BPF.
func (lc *LSMCollector) checkAvailability() bool {
	// Check kernel version (5.7+)
	// This is a simplified check; real implementation would parse uname
	data, err := os.ReadFile("/sys/kernel/security/lsm")
	if err != nil {
		lc.logger.Debug("lsm: cannot read /sys/kernel/security/lsm", "error", err)
		return false
	}

	lsms := string(data)
	if !strings.Contains(lsms, "bpf") {
		lc.logger.Debug("lsm: bpf not in active LSMs", "lsm", strings.TrimSpace(lsms))
		return false
	}

	return true
}

// Load loads the LSM BPF programs.
func (lc *LSMCollector) Load() error {
	if !lc.available {
		return nil
	}

	// Remove memory limit for locked memory
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("lsm: remove memlock limit: %w", err)
	}

	// TODO: Load BPF objects using bpf2go generated code
	// For now, this is a stub that will be implemented when bpf2go is run
	lc.logger.Info("lsm: BPF programs loaded (stub)")

	// Add agent PID to whitelist
	if err := lc.whitelistAgentPID(); err != nil {
		lc.logger.Warn("lsm: failed to whitelist agent PID", "error", err)
	}

	return nil
}

// whitelistAgentPID adds the current process to the agent whitelist.
func (lc *LSMCollector) whitelistAgentPID() error {
	if lc.objs == nil || lc.objs.LsmAgentWhitelist == nil {
		return nil // Stub mode
	}

	pid := os.Getpid()
	val := uint8(1)
	if err := lc.objs.LsmAgentWhitelist.Update(uint32(pid), val, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("update agent whitelist: %w", err)
	}

	lc.logger.Debug("lsm: agent PID whitelisted", "pid", pid)
	return nil
}

// AddToBlocklist adds a PID to the LSM blocklist.
func (lc *LSMCollector) AddToBlocklist(pid uint32) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmBlocklist == nil {
		return fmt.Errorf("lsm: collector not available or not loaded")
	}

	val := uint8(1)
	if err := lc.objs.LsmBlocklist.Update(pid, val, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("lsm: add to blocklist: %w", err)
	}

	lc.logger.Info("lsm: PID added to blocklist", "pid", pid)
	return nil
}

// RemoveFromBlocklist removes a PID from the LSM blocklist.
func (lc *LSMCollector) RemoveFromBlocklist(pid uint32) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmBlocklist == nil {
		return fmt.Errorf("lsm: collector not available or not loaded")
	}

	if err := lc.objs.LsmBlocklist.Delete(pid); err != nil {
		return fmt.Errorf("lsm: remove from blocklist: %w", err)
	}

	lc.logger.Info("lsm: PID removed from blocklist", "pid", pid)
	return nil
}

// IsAvailable returns true if LSM BPF is available and enabled.
func (lc *LSMCollector) IsAvailable() bool {
	lc.mu.RLock()
	defer lc.mu.RUnlock()
	return lc.available
}

// Start implements the Collector interface.
// LSM hooks are loaded once and run continuously; no event reading needed.
func (lc *LSMCollector) Start(ctx context.Context, out chan<- types.Event) error {
	if !lc.available {
		// Stub mode: just wait for context cancellation
		<-ctx.Done()
		return ctx.Err()
	}

	// LSM hooks run in kernel space; we just need to keep the BPF objects loaded
	lc.logger.Info("lsm: LSM hooks active, waiting for shutdown")

	// Periodically update metrics from BPF stats map
	ticker := lc.startStatsCollector(ctx)
	defer ticker.Stop()

	<-ctx.Done()
	return ctx.Err()
}

// startStatsCollector starts a goroutine to collect LSM stats.
func (lc *LSMCollector) startStatsCollector(ctx context.Context) *time.Ticker {
	// Stub: would read from lsm_stats map periodically
	return time.NewTicker(30 * time.Second)
}

// Name returns the collector name.
func (lc *LSMCollector) Name() string {
	return "lsm"
}

// Close unloads LSM BPF programs.
func (lc *LSMCollector) Close() error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	for _, l := range lc.links {
		l.Close()
	}
	lc.links = nil

	if lc.objs != nil {
		// Close maps
		if lc.objs.LsmBlocklist != nil {
			lc.objs.LsmBlocklist.Close()
		}
		if lc.objs.LsmAgentWhitelist != nil {
			lc.objs.LsmAgentWhitelist.Close()
		}
		if lc.objs.LsmStats != nil {
			lc.objs.LsmStats.Close()
		}
		lc.objs = nil
	}

	lc.logger.Info("lsm: LSM collector closed")
	return nil
}

// RegisterMetrics registers Prometheus metrics.
func (lc *LSMCollector) RegisterMetrics(reg prometheus.Registerer) error {
	return reg.Register(lc.blocksTotal)
}

// -----------------------------------------------------------------------
// KmodCollector — Sprint 33.0
// -----------------------------------------------------------------------

// KmodCollector reads EVENT_KMOD_LOAD and EVENT_CGROUP_ESC events from the
// lsm_events and cgroup_events ring buffers written by lsm.bpf.c and
// cgroup.bpf.c respectively. It provides a tracepoint fallback
// (sys_enter_init_module) for kernels older than 5.7.
type KmodCollector struct {
	logger     *slog.Logger
	kmodObjs   *bpf.KmodObjects
	cgroupObjs *bpf.CgroupObjects
	kmodLinks  []link.Link
	cgroupLinks []link.Link
	kmodReader  *bpf.RingbufReader
	cgroupReader *bpf.RingbufReader
	loadError  error
	dropLogger *dropLogger
	status     StatusReporter
	strategy   BackpressureStrategy
	available  bool
}

// NewKmodCollector creates a new kernel-module-load and cgroup-escape collector.
func NewKmodCollector(logger *slog.Logger) (*KmodCollector, error) {
	if logger == nil {
		logger = slog.Default()
	}
	c := &KmodCollector{
		logger:     logger.With("collector", "kmod"),
		dropLogger: newDropLogger(5 * time.Second),
		status:     NoopStatusReporter{},
		strategy:   StrategyDrop,
	}
	// Determine whether LSM BPF is available (same check as LSMCollector).
	data, err := os.ReadFile("/sys/kernel/security/lsm")
	if err == nil && strings.Contains(string(data), "bpf") {
		c.available = true
	}
	return c, nil
}

// WithStatusReporter sets the StatusReporter.
func (c *KmodCollector) WithStatusReporter(r StatusReporter) *KmodCollector {
	c.status = r
	return c
}

// WithBackpressureStrategy sets the backpressure strategy.
func (c *KmodCollector) WithBackpressureStrategy(s BackpressureStrategy) *KmodCollector {
	c.strategy = s
	return c
}

// Name returns the collector identifier.
func (c *KmodCollector) Name() string { return "kmod" }

// IsHealthy returns true if the collector loaded without error.
func (c *KmodCollector) IsHealthy() bool { return c.loadError == nil }

// Start attaches eBPF programs and begins forwarding events. Blocks until ctx is cancelled.
func (c *KmodCollector) Start(ctx context.Context, out chan<- types.Event) error {
	c.logger.Info("starting kmod collector", "lsm_available", c.available)

	if c.available {
		if err := c.loadKmod(); err != nil {
			c.logger.Warn("kmod: LSM load failed, falling back to tracepoint", "error", err)
			c.available = false
		}
	}

	if !c.available {
		if err := c.loadFallback(); err != nil {
			c.loadError = err
			c.status.SetUp("kmod", false)
			return fmt.Errorf("collector/kmod: fallback load failed: %w", err)
		}
	}

	if err := c.loadCgroup(); err != nil {
		// Cgroup escape detection is best-effort; log and continue.
		c.logger.Warn("kmod: cgroup escape collector unavailable", "error", err)
	}

	c.status.SetUp("kmod", true)

	if c.kmodReader != nil {
		go c.readLoop(ctx, out, c.kmodReader, c.parseKmodOrFallback)
	}
	if c.cgroupReader != nil {
		go c.readLoop(ctx, out, c.cgroupReader, c.parseCgroupEsc)
	}

	<-ctx.Done()
	c.logger.Info("stopping kmod collector")
	return nil
}

// Close releases all eBPF resources.
func (c *KmodCollector) Close() error {
	if c.kmodReader != nil {
		c.kmodReader.Close()
		c.kmodReader = nil
	}
	if c.cgroupReader != nil {
		c.cgroupReader.Close()
		c.cgroupReader = nil
	}
	for _, l := range c.kmodLinks {
		l.Close()
	}
	c.kmodLinks = nil
	for _, l := range c.cgroupLinks {
		l.Close()
	}
	c.cgroupLinks = nil
	if c.kmodObjs != nil {
		c.kmodObjs.Close()
		c.kmodObjs = nil
	}
	if c.cgroupObjs != nil {
		c.cgroupObjs.Close()
		c.cgroupObjs = nil
	}
	return nil
}

func (c *KmodCollector) loadKmod() error {
	c.kmodObjs = &bpf.KmodObjects{}
	if err := bpf.LoadKmodObjects(c.kmodObjs, &ebpf.CollectionOptions{}); err != nil {
		return err
	}
	// Attach LSM hooks.
	l1, err := link.AttachLSM(link.LSMOptions{Program: c.kmodObjs.LsmKernelModuleRequest})
	if err != nil {
		return fmt.Errorf("attach kernel_module_request: %w", err)
	}
	c.kmodLinks = append(c.kmodLinks, l1)

	l2, err := link.AttachLSM(link.LSMOptions{Program: c.kmodObjs.LsmKernelReadFile})
	if err != nil {
		return fmt.Errorf("attach kernel_read_file: %w", err)
	}
	c.kmodLinks = append(c.kmodLinks, l2)

	// Attach exec tracepoint for initial-cgroup recording.
	l3, err := link.Tracepoint("sched", "sched_process_exec", c.kmodObjs.TraceExecRecordCgroup, nil)
	if err != nil {
		c.logger.Warn("kmod: sched_process_exec tracepoint unavailable", "error", err)
	} else {
		c.kmodLinks = append(c.kmodLinks, l3)
	}

	reader, err := bpf.NewRingbufReader(c.kmodObjs.LsmEvents)
	if err != nil {
		return fmt.Errorf("kmod ringbuf reader: %w", err)
	}
	c.kmodReader = reader
	return nil
}

// loadFallback attaches the sys_enter_init_module tracepoint (kernel < 5.7 fallback).
func (c *KmodCollector) loadFallback() error {
	c.kmodObjs = &bpf.KmodObjects{}
	if err := bpf.LoadKmodObjects(c.kmodObjs, &ebpf.CollectionOptions{}); err != nil {
		return err
	}
	l, err := link.Tracepoint("syscalls", "sys_enter_init_module", c.kmodObjs.LsmKernelModuleRequest, nil)
	if err != nil {
		return fmt.Errorf("attach sys_enter_init_module: %w", err)
	}
	c.kmodLinks = append(c.kmodLinks, l)

	reader, err := bpf.NewRingbufReader(c.kmodObjs.LsmEvents)
	if err != nil {
		return fmt.Errorf("kmod fallback ringbuf reader: %w", err)
	}
	c.kmodReader = reader
	return nil
}

func (c *KmodCollector) loadCgroup() error {
	c.cgroupObjs = &bpf.CgroupObjects{}
	if err := bpf.LoadCgroupObjects(c.cgroupObjs, &ebpf.CollectionOptions{}); err != nil {
		return err
	}
	l, err := link.AttachLSM(link.LSMOptions{Program: c.cgroupObjs.LsmCgroupAttachTask})
	if err != nil {
		return fmt.Errorf("attach cgroup_attach_task: %w", err)
	}
	c.cgroupLinks = append(c.cgroupLinks, l)

	reader, err := bpf.NewRingbufReader(c.cgroupObjs.CgroupEvents)
	if err != nil {
		return fmt.Errorf("cgroup ringbuf reader: %w", err)
	}
	c.cgroupReader = reader
	return nil
}

type parseFunc func([]byte) (*types.Event, error)

func (c *KmodCollector) readLoop(ctx context.Context, out chan<- types.Event, reader *bpf.RingbufReader, parse parseFunc) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}
		record, err := reader.Read()
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			c.logger.Error("kmod: ringbuf read error", "error", err)
			continue
		}
		event, err := parse(record.RawSample)
		if err != nil {
			c.logger.Error("kmod: parse error", "error", err)
			continue
		}
		sendEvent(ctx, out, *event, c.strategy, func() {
			c.dropLogger.record(c.logger, "kmod")
		})
	}
}

func (c *KmodCollector) parseKmodOrFallback(raw []byte) (*types.Event, error) {
	evt, err := bpf.ParseKmodEvent(raw)
	if err != nil {
		return nil, err
	}
	result := evt.ToTypesEvent()
	return &result, nil
}

func (c *KmodCollector) parseCgroupEsc(raw []byte) (*types.Event, error) {
	evt, err := bpf.ParseCgroupEscapeEvent(raw)
	if err != nil {
		return nil, err
	}
	result := evt.ToTypesEvent()
	return &result, nil
}
