// lsm.go — eBPF LSM hook collectors
//
// LSMCollector  (Sprint 22.0): loads file_open / socket_connect / task_kill
//   hooks for pre-execution enforcement.
// KmodCollector (Sprint 33.0): reads kernel_module_request / kernel_read_file
//   and cgroup_attach_task events and forwards them to the correlation engine.

package collector

import (
	"context"
	"encoding/binary"
	"fmt"
	"hash/fnv"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"github.com/zugolO/ebpf-guard/internal/audit"
	"github.com/zugolO/ebpf-guard/internal/bpf"
	"github.com/zugolO/ebpf-guard/pkg/types"
	"github.com/prometheus/client_golang/prometheus"
)

// fnv32a returns the FNV-1a 32-bit hash of s. This must produce the same
// output as the fnv32a() BPF helper in bpf/lsm.bpf.c so that paths added
// via AddPathToBlocklist map correctly to what the kernel checks.
func fnv32a(s string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h.Sum32()
}

// lsmAuditEventRaw mirrors struct lsm_audit_event from bpf/common.h.
// The struct is __attribute__((packed)), so fields are at fixed byte offsets with no padding.
// Layout (107 bytes total):
//   type(4) + timestamp_ns(8) + pid(4) + target_pid(4) + uid(4) +
//   action(1) + hook(1) + sig(1) + comm(16) + path(64)
type lsmAuditEventRaw struct {
	Type      uint32
	Timestamp uint64
	PID       uint32
	TargetPID uint32
	UID       uint32
	Action    uint8
	Hook      uint8
	Sig       uint8
	Comm      [16]byte
	Path      [64]byte
}

const lsmAuditEventSize = 4 + 8 + 4 + 4 + 4 + 1 + 1 + 1 + 16 + 64 // 107 bytes

var lsmHookNames = [4]string{"file_open", "socket_connect", "task_kill", "bprm_check"}

// parseLSMAuditEventRaw deserialises a raw ring-buffer record into lsmAuditEventRaw.
func parseLSMAuditEventRaw(raw []byte) (lsmAuditEventRaw, error) {
	if len(raw) < lsmAuditEventSize {
		return lsmAuditEventRaw{}, fmt.Errorf("lsm_audit_event too short: %d < %d", len(raw), lsmAuditEventSize)
	}
	var e lsmAuditEventRaw
	e.Type      = binary.LittleEndian.Uint32(raw[0:4])
	e.Timestamp = binary.LittleEndian.Uint64(raw[4:12])
	e.PID       = binary.LittleEndian.Uint32(raw[12:16])
	e.TargetPID = binary.LittleEndian.Uint32(raw[16:20])
	e.UID       = binary.LittleEndian.Uint32(raw[20:24])
	e.Action    = raw[24]
	e.Hook      = raw[25]
	e.Sig       = raw[26]
	copy(e.Comm[:], raw[27:43])
	copy(e.Path[:], raw[43:107])
	return e, nil
}

// toAuditEntry converts a parsed LSM audit event into an audit.Entry for the JSONL log.
func (e lsmAuditEventRaw) toAuditEntry() audit.Entry {
	hookName := "unknown"
	if int(e.Hook) < len(lsmHookNames) {
		hookName = lsmHookNames[e.Hook]
	}
	// Action codes match LSM_ACTION_* in bpf/common.h:
	//   0 audit-only, 1 deny, 2 ai_sandbox audit, 3 ai_sandbox deny.
	action := "audit"
	rule := "lsm_audit"
	enforced := false
	switch e.Action {
	case 1:
		action, enforced = "deny", true
	case 2:
		action, rule = "sandbox_audit", "ai_sandbox"
	case 3:
		action, rule, enforced = "sandbox_deny", "ai_sandbox", true
	}
	return audit.Entry{
		TS:        time.Now(),
		Action:    action,
		PID:       e.PID,
		Rule:      rule,
		Comm:      nullTermString(e.Comm[:]),
		Enforced:  enforced,
		Hook:      hookName,
		TargetPID: e.TargetPID,
		Path:      nullTermString(e.Path[:]),
		UID:       e.UID,
	}
}

// nullTermString converts a NUL-padded byte slice to a Go string.
func nullTermString(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

// LSMConfig holds configuration for the LSM collector.
type LSMConfig struct {
	// Enabled controls LSM hook loading:
	// "auto" - load if kernel supports (default)
	// "true" - require kernel support, fail if unavailable
	// "false" - disable LSM hooks
	Enabled string `mapstructure:"enabled"`
}

// DefaultLSMConfig returns default LSM configuration.
func DefaultLSMConfig() LSMConfig {
	return LSMConfig{
		Enabled: "auto",
	}
}

// LSMCollector manages eBPF LSM hooks for pre-execution enforcement.
type LSMCollector struct {
	config    LSMConfig
	logger    *slog.Logger
	objs      *lsmObjects
	links     []link.Link
	available bool
	mu        sync.RWMutex

	// configPathKeys tracks the FNV-32a keys loaded from the config-driven
	// lsm_path_blocklist so SetPathBlocklist can remove stale entries on reload.
	configPathKeys []uint32

	// Metrics
	blocksTotal *prometheus.CounterVec
}

// lsmObjects contains all eBPF objects for LSM hooks.
// This will be generated by bpf2go; the struct is hand-maintained until
// `make generate` is re-run after bpf/lsm.bpf.c stabilises.
type lsmObjects struct {
	LsmBlocklist      *ebpf.Map `ebpf:"lsm_blocklist"`
	LsmAgentWhitelist *ebpf.Map `ebpf:"lsm_agent_whitelist"`
	LsmStats          *ebpf.Map `ebpf:"lsm_stats"`
	LsmPathBlocklist  *ebpf.Map `ebpf:"path_blocklist"` // FNV-32a hash → blocked flag
}

// NewLSMCollector creates a new LSM collector.
func NewLSMCollector(config LSMConfig, logger *slog.Logger) (*LSMCollector, error) {
	if logger == nil {
		logger = slog.Default()
	}

	lc := &LSMCollector{
		config: config,
		logger: logger,
		links:  make([]link.Link, 0),
		blocksTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "ebpf_guard_lsm_blocks_total",
			Help: "Total number of LSM hook invocations and blocking decisions",
		}, []string{"hook", "action"}),
	}

	// Pre-initialize the known label combinations to 0 so the metric is present
	// in /metrics from startup (rather than appearing only after the first block),
	// which lets dashboards and alerting rules reference it immediately.
	for _, hook := range []string{"file_open", "socket_connect", "task_kill"} {
		for _, action := range []string{"allow", "block"} {
			lc.blocksTotal.WithLabelValues(hook, action)
		}
	}

	// Check availability
	available := lc.checkAvailability()
	lc.available = available

	if !available {
		if config.Enabled == "true" {
			return nil, fmt.Errorf("lsm: kernel does not support LSM BPF (required but disabled)")
		}
		logger.Info("lsm: kernel does not support LSM BPF, collector in stub mode")
		return lc, nil
	}

	if config.Enabled == "false" {
		logger.Info("lsm: LSM BPF disabled by configuration")
		lc.available = false
		return lc, nil
	}

	logger.Info("lsm: LSM BPF is available")
	return lc, nil
}

// checkAvailability checks if the kernel supports LSM BPF.
func (lc *LSMCollector) checkAvailability() bool {
	// Check kernel version (5.7+)
	// This is a simplified check; real implementation would parse uname
	data, err := os.ReadFile("/sys/kernel/security/lsm")
	if err != nil {
		lc.logger.Debug("lsm: cannot read /sys/kernel/security/lsm", "error", err)
		return false
	}

	lsms := string(data)
	if !strings.Contains(lsms, "bpf") {
		lc.logger.Debug("lsm: bpf not in active LSMs", "lsm", strings.TrimSpace(lsms))
		return false
	}

	return true
}

// Load loads the LSM BPF programs.
func (lc *LSMCollector) Load() error {
	if !lc.available {
		return nil
	}

	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("lsm: remove memlock limit: %w", err)
	}

	// lsm_bpf_gen.go does not exist yet — run `make generate` after
	// bpf/lsm.bpf.c is finalised to produce it and replace this block
	// with the real LoadLsmObjects call + link.AttachLSM calls.
	// Until then, mark as unavailable so IsAvailable(), AddToBlocklist(),
	// and the enforcer LSM path all correctly report no enforcement active.
	lc.logger.Warn("lsm: bpf2go bindings not yet generated; LSM enforcement inactive — run `make generate`")
	lc.available = false
	return nil
}

// whitelistAgentPID adds the current process to the agent whitelist.
func (lc *LSMCollector) whitelistAgentPID() error {
	if lc.objs == nil || lc.objs.LsmAgentWhitelist == nil {
		return nil // Stub mode
	}

	pid := os.Getpid()
	val := uint8(1)
	if err := lc.objs.LsmAgentWhitelist.Update(uint32(pid), val, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("update agent whitelist: %w", err)
	}

	lc.logger.Debug("lsm: agent PID whitelisted", "pid", pid)
	return nil
}

// AddToBlocklist adds a PID to the LSM blocklist.
func (lc *LSMCollector) AddToBlocklist(pid uint32) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmBlocklist == nil {
		return fmt.Errorf("lsm: collector not available or not loaded")
	}

	val := uint8(1)
	if err := lc.objs.LsmBlocklist.Update(pid, val, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("lsm: add to blocklist: %w", err)
	}

	lc.logger.Info("lsm: PID added to blocklist", "pid", pid)
	return nil
}

// RemoveFromBlocklist removes a PID from the LSM blocklist.
func (lc *LSMCollector) RemoveFromBlocklist(pid uint32) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmBlocklist == nil {
		return fmt.Errorf("lsm: collector not available or not loaded")
	}

	if err := lc.objs.LsmBlocklist.Delete(pid); err != nil {
		return fmt.Errorf("lsm: remove from blocklist: %w", err)
	}

	lc.logger.Info("lsm: PID removed from blocklist", "pid", pid)
	return nil
}

// AddPathToBlocklist adds a path to the per-path BPF blocklist.
// The path is normalised to its absolute form before hashing so that
// "/tmp/evil", "./evil" relative to /tmp, and "/tmp//evil" all resolve
// to the same key.  The BPF hook blocks any open of a path whose FNV-32a
// hash is present in the map, regardless of which PID opens it.
func (lc *LSMCollector) AddPathToBlocklist(path string) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmPathBlocklist == nil {
		return fmt.Errorf("lsm: path blocklist not available (LSM not loaded)")
	}

	// Use filepath.Clean so the hash matches what bpf_d_path returns.
	key := fnv32a(filepath.Clean(path))
	val := uint8(1)
	if err := lc.objs.LsmPathBlocklist.Update(key, val, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("lsm: add path to blocklist %q: %w", path, err)
	}
	lc.logger.Info("lsm: path added to blocklist", "path", path, "hash", key)
	return nil
}

// RemovePathFromBlocklist removes a path from the per-path BPF blocklist.
func (lc *LSMCollector) RemovePathFromBlocklist(path string) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmPathBlocklist == nil {
		return fmt.Errorf("lsm: path blocklist not available (LSM not loaded)")
	}

	key := fnv32a(filepath.Clean(path))
	if err := lc.objs.LsmPathBlocklist.Delete(key); err != nil {
		return fmt.Errorf("lsm: remove path from blocklist %q: %w", path, err)
	}
	lc.logger.Info("lsm: path removed from blocklist", "path", path)
	return nil
}

// SetPathBlocklist atomically replaces the config-driven portion of the
// path blocklist.  It removes every key that was previously loaded from
// config (tracked in configPathKeys) and then inserts the new set.
// Dynamically blocked paths (added via AddPathToBlocklist at rule-fire
// time) are preserved.
func (lc *LSMCollector) SetPathBlocklist(paths []string) error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	if !lc.available || lc.objs == nil || lc.objs.LsmPathBlocklist == nil {
		return fmt.Errorf("lsm: path blocklist not available (LSM not loaded)")
	}

	// Remove previously configured paths.
	for _, old := range lc.configPathKeys {
		_ = lc.objs.LsmPathBlocklist.Delete(old) // best-effort; ignore ENOENT
	}

	newKeys := make([]uint32, 0, len(paths))
	val := uint8(1)
	for _, p := range paths {
		key := fnv32a(filepath.Clean(p))
		if err := lc.objs.LsmPathBlocklist.Update(key, val, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("lsm: config path blocklist %q: %w", p, err)
		}
		newKeys = append(newKeys, key)
		lc.logger.Debug("lsm: config path blocklisted", "path", p, "hash", key)
	}
	lc.configPathKeys = newKeys
	lc.logger.Info("lsm: path blocklist reloaded", "count", len(paths))
	return nil
}

// IsAvailable returns true if LSM BPF is available and enabled.
func (lc *LSMCollector) IsAvailable() bool {
	lc.mu.RLock()
	defer lc.mu.RUnlock()
	return lc.available
}

// Start implements the Collector interface.
// LSM hooks are loaded once and run continuously; no event reading needed.
func (lc *LSMCollector) Start(ctx context.Context, out chan<- types.Event) error {
	if !lc.available {
		// Stub mode: just wait for context cancellation
		<-ctx.Done()
		return ctx.Err()
	}

	// LSM hooks run in kernel space; we just need to keep the BPF objects loaded
	lc.logger.Info("lsm: LSM hooks active, waiting for shutdown")

	// Periodically update metrics from BPF stats map
	ticker := lc.startStatsCollector(ctx)
	defer ticker.Stop()

	<-ctx.Done()
	return ctx.Err()
}

// startStatsCollector starts a goroutine to collect LSM stats.
func (lc *LSMCollector) startStatsCollector(ctx context.Context) *time.Ticker {
	// Stub: would read from lsm_stats map periodically
	return time.NewTicker(30 * time.Second)
}

// Name returns the collector name.
func (lc *LSMCollector) Name() string {
	return "lsm"
}

// Close unloads LSM BPF programs.
func (lc *LSMCollector) Close() error {
	lc.mu.Lock()
	defer lc.mu.Unlock()

	for _, l := range lc.links {
		l.Close()
	}
	lc.links = nil

	if lc.objs != nil {
		if lc.objs.LsmBlocklist != nil {
			lc.objs.LsmBlocklist.Close()
		}
		if lc.objs.LsmAgentWhitelist != nil {
			lc.objs.LsmAgentWhitelist.Close()
		}
		if lc.objs.LsmStats != nil {
			lc.objs.LsmStats.Close()
		}
		if lc.objs.LsmPathBlocklist != nil {
			lc.objs.LsmPathBlocklist.Close()
		}
		lc.objs = nil
	}

	lc.logger.Info("lsm: LSM collector closed")
	return nil
}

// RegisterMetrics registers Prometheus metrics.
func (lc *LSMCollector) RegisterMetrics(reg prometheus.Registerer) error {
	return reg.Register(lc.blocksTotal)
}

// -----------------------------------------------------------------------
// KmodCollector — Sprint 33.0
// -----------------------------------------------------------------------

// KmodCollector reads EVENT_KMOD_LOAD and EVENT_CGROUP_ESC events from the
// lsm_events and cgroup_events ring buffers written by lsm.bpf.c and
// cgroup.bpf.c respectively. It provides a tracepoint fallback
// (sys_enter_init_module) for kernels older than 5.7.
type KmodCollector struct {
	logger       *slog.Logger
	kmodObjs     *bpf.KmodObjects
	cgroupObjs   *bpf.CgroupObjects
	kmodLinks    []link.Link
	cgroupLinks  []link.Link
	kmodReader   *bpf.RingbufReader
	cgroupReader *bpf.RingbufReader
	loadError    error
	dropLogger   *dropLogger
	status       StatusReporter
	strategy     BackpressureStrategy
	available    bool
	lostTotal    atomic.Uint64
	auditLogger  *audit.Logger // optional; routes LSM audit events out-of-band
}

// NewKmodCollector creates a new kernel-module-load and cgroup-escape collector.
func NewKmodCollector(logger *slog.Logger) (*KmodCollector, error) {
	if logger == nil {
		logger = slog.Default()
	}
	c := &KmodCollector{
		logger:     logger.With("collector", "kmod"),
		dropLogger: newDropLogger(5 * time.Second),
		status:     NoopStatusReporter{},
		strategy:   StrategyDrop,
	}
	// Determine whether LSM BPF is available (same check as LSMCollector).
	data, err := os.ReadFile("/sys/kernel/security/lsm")
	if err == nil && strings.Contains(string(data), "bpf") {
		c.available = true
	}
	return c, nil
}

// WithStatusReporter sets the StatusReporter.
func (c *KmodCollector) WithStatusReporter(r StatusReporter) *KmodCollector {
	c.status = r
	return c
}

// WithBackpressureStrategy sets the backpressure strategy.
func (c *KmodCollector) WithBackpressureStrategy(s BackpressureStrategy) *KmodCollector {
	c.strategy = s
	return c
}

// WithAuditLogger wires an audit.Logger so that LSM audit events (EVENT_TYPE_LSM_AUDIT)
// are written to the JSONL audit log instead of forwarded to the event channel.
func (c *KmodCollector) WithAuditLogger(l *audit.Logger) *KmodCollector {
	c.auditLogger = l
	return c
}

// Name returns the collector identifier.
func (c *KmodCollector) Name() string { return "kmod" }

// IsHealthy returns true if the collector loaded without error.
func (c *KmodCollector) IsHealthy() bool { return c.loadError == nil }

// Start attaches eBPF programs and begins forwarding events. Blocks until ctx is cancelled.
//
// There is no tracepoint-based fallback for kernel-module-load detection:
// bpf/lsm.bpf.c only defines LSM-type programs (SEC("lsm/...")), and the
// compiled "Kmod" object bundles all of them together, so even attempting to
// load it on a kernel without BPF LSM support (no CONFIG_BPF_LSM / lsm=bpf)
// fails outright — there is nothing to fall back to. When LSM is unavailable,
// skip kmod load detection entirely rather than logging a misleading error.
func (c *KmodCollector) Start(ctx context.Context, out chan<- types.Event) error {
	c.logger.Info("starting kmod collector", "lsm_available", c.available)

	if c.available {
		if err := c.loadKmod(); err != nil {
			c.logger.Warn("kmod: LSM load failed, kernel module load detection disabled", "error", err)
			c.available = false
		}
	} else {
		c.logger.Info("kmod: LSM BPF unavailable, kernel module load detection disabled (no tracepoint fallback exists)")
	}

	if err := c.loadCgroup(); err != nil {
		// Cgroup escape detection is best-effort; log and continue.
		c.logger.Warn("kmod: cgroup escape collector unavailable", "error", err)
	}

	c.status.SetUp("kmod", true)

	if c.kmodReader != nil {
		go c.readLoop(ctx, out, c.kmodReader, c.parseKmodOrFallback)
	}
	if c.cgroupReader != nil {
		go c.readLoop(ctx, out, c.cgroupReader, c.parseCgroupEsc)
	}

	<-ctx.Done()
	c.logger.Info("stopping kmod collector")
	return nil
}

// Close releases all eBPF resources.
func (c *KmodCollector) Close() error {
	if c.kmodReader != nil {
		c.kmodReader.Close()
		c.kmodReader = nil
	}
	if c.cgroupReader != nil {
		c.cgroupReader.Close()
		c.cgroupReader = nil
	}
	for _, l := range c.kmodLinks {
		l.Close()
	}
	c.kmodLinks = nil
	for _, l := range c.cgroupLinks {
		l.Close()
	}
	c.cgroupLinks = nil
	if c.kmodObjs != nil {
		c.kmodObjs.Close()
		c.kmodObjs = nil
	}
	if c.cgroupObjs != nil {
		c.cgroupObjs.Close()
		c.cgroupObjs = nil
	}
	return nil
}

func (c *KmodCollector) loadKmod() error {
	c.kmodObjs = &bpf.KmodObjects{}
	if err := bpf.LoadKmodObjects(c.kmodObjs, &ebpf.CollectionOptions{}); err != nil {
		return err
	}
	// Attach LSM hooks.
	l1, err := link.AttachLSM(link.LSMOptions{Program: c.kmodObjs.LsmKernelModuleRequest})
	if err != nil {
		return fmt.Errorf("attach kernel_module_request: %w", err)
	}
	c.kmodLinks = append(c.kmodLinks, l1)

	l2, err := link.AttachLSM(link.LSMOptions{Program: c.kmodObjs.LsmKernelReadFile})
	if err != nil {
		return fmt.Errorf("attach kernel_read_file: %w", err)
	}
	c.kmodLinks = append(c.kmodLinks, l2)

	// Attach exec tracepoint for initial-cgroup recording.
	l3, err := link.Tracepoint("sched", "sched_process_exec", c.kmodObjs.TraceExecRecordCgroup, nil)
	if err != nil {
		c.logger.Warn("kmod: sched_process_exec tracepoint unavailable", "error", err)
	} else {
		c.kmodLinks = append(c.kmodLinks, l3)
	}

	reader, err := bpf.NewRingbufReader(c.kmodObjs.LsmEvents)
	if err != nil {
		return fmt.Errorf("kmod ringbuf reader: %w", err)
	}
	c.kmodReader = reader
	return nil
}

func (c *KmodCollector) loadCgroup() error {
	c.cgroupObjs = &bpf.CgroupObjects{}
	if err := bpf.LoadCgroupObjects(c.cgroupObjs, &ebpf.CollectionOptions{}); err != nil {
		return err
	}
	l, err := link.AttachLSM(link.LSMOptions{Program: c.cgroupObjs.LsmCgroupAttachTask})
	if err != nil {
		return fmt.Errorf("attach cgroup_attach_task: %w", err)
	}
	c.cgroupLinks = append(c.cgroupLinks, l)

	reader, err := bpf.NewRingbufReader(c.cgroupObjs.CgroupEvents)
	if err != nil {
		return fmt.Errorf("cgroup ringbuf reader: %w", err)
	}
	c.cgroupReader = reader
	return nil
}

type parseFunc func([]byte) (*types.Event, error)

func (c *KmodCollector) readLoop(ctx context.Context, out chan<- types.Event, reader *bpf.RingbufReader, parse parseFunc) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}
		record, err := reader.Read()
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			c.logger.Error("kmod: ringbuf read error", "error", err)
			continue
		}
		event, err := parse(record.RawSample)
		if err != nil {
			c.logger.Error("kmod: parse error", "error", err)
			continue
		}
		if event == nil {
			// Consumed inline (e.g. LSM audit event routed to audit logger).
			continue
		}
		sendEvent(ctx, out, *event, c.strategy, func() {
			c.dropLogger.record(c.logger, "kmod")
			c.lostTotal.Add(1)
		})
	}
}

// LostEvents returns the total number of events lost in the BPF ring buffer
// since the collector started. Implements watchdog.DropTracker.
func (c *KmodCollector) LostEvents() uint64 {
	return c.lostTotal.Load()
}

func (c *KmodCollector) parseKmodOrFallback(raw []byte) (*types.Event, error) {
	if len(raw) < 4 {
		return nil, fmt.Errorf("kmod: raw event too short (%d bytes)", len(raw))
	}
	evtType := binary.LittleEndian.Uint32(raw[:4])
	if evtType == uint32(types.EventLSMAudit) {
		// LSM audit events are routed to the audit logger, not the event channel.
		if c.auditLogger != nil {
			ae, err := parseLSMAuditEventRaw(raw)
			if err != nil {
				return nil, fmt.Errorf("kmod: lsm audit event: %w", err)
			}
			if logErr := c.auditLogger.Log(ae.toAuditEntry()); logErr != nil {
				c.logger.Warn("kmod: audit log write failed", "error", logErr)
			}
		}
		return nil, nil // consumed; do not forward to the event channel
	}
	var ke bpf.KmodRawEvent
	if err := bpf.ParseKmodEventInto(raw, &ke); err != nil {
		return nil, err
	}
	result := ke.ToTypesEvent()
	return &result, nil
}

func (c *KmodCollector) parseCgroupEsc(raw []byte) (*types.Event, error) {
	var ce bpf.CgroupEscapeRawEvent
	if err := bpf.ParseCgroupEscapeEventInto(raw, &ce); err != nil {
		return nil, err
	}
	result := ce.ToTypesEvent()
	return &result, nil
}
