// Package bpf — stub types for the BpfMonitor BPF program.
//
// The real BpfMonitorObjects / LoadBpfMonitorObjects are generated by `make generate`
// (bpf2go compiles bpf/bpf_monitor.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// bpfmonitor_bpfel.go / bpfmonitor_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// BpfMonitorMaps holds the BPF maps exported by bpf/bpf_monitor.bpf.c.
type BpfMonitorMaps struct {
	BpfmonitorEvents *ebpf.Map `ebpf:"bpfmonitor_events"`
}

// BpfMonitorPrograms holds the BPF programs exported by bpf/bpf_monitor.bpf.c.
type BpfMonitorPrograms struct {
	TraceBpfEnter *ebpf.Program `ebpf:"trace_bpf_enter"`
	TraceBpfExit  *ebpf.Program `ebpf:"trace_bpf_exit"`
}

// BpfMonitorObjects contains all BPF objects after loading bpf/bpf_monitor.bpf.c.
type BpfMonitorObjects struct {
	BpfMonitorPrograms
	BpfMonitorMaps
}

// Close releases all BPF resources held by the objects.
func (o *BpfMonitorObjects) Close() error {
	var errs []error
	if o.TraceBpfEnter != nil {
		errs = append(errs, o.TraceBpfEnter.Close())
	}
	if o.TraceBpfExit != nil {
		errs = append(errs, o.TraceBpfExit.Close())
	}
	if o.BpfmonitorEvents != nil {
		errs = append(errs, o.BpfmonitorEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadBpfMonitorObjects loads the BpfMonitor BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/bpf_monitor.bpf.c.
func LoadBpfMonitorObjects(_ *BpfMonitorObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: BpfMonitor program not available (run make generate to compile BPF programs)")
}
