// Package bpf — stub types for the Cgroup BPF program.
//
// The real CgroupObjects / LoadCgroupObjects are generated by `make generate`
// (bpf2go compiles bpf/cgroup.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// cgroup_bpfel.go / cgroup_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// CgroupMaps holds the BPF maps exported by bpf/cgroup.bpf.c.
type CgroupMaps struct {
	CgroupEvents *ebpf.Map `ebpf:"cgroup_events"`
}

// CgroupPrograms holds the BPF programs exported by bpf/cgroup.bpf.c.
type CgroupPrograms struct {
	LsmCgroupAttachTask *ebpf.Program `ebpf:"lsm_cgroup_attach_task"`
}

// CgroupObjects contains all BPF objects after loading bpf/cgroup.bpf.c.
type CgroupObjects struct {
	CgroupPrograms
	CgroupMaps
}

// Close releases all BPF resources held by the objects.
func (o *CgroupObjects) Close() error {
	var errs []error
	if o.LsmCgroupAttachTask != nil {
		errs = append(errs, o.LsmCgroupAttachTask.Close())
	}
	if o.CgroupEvents != nil {
		errs = append(errs, o.CgroupEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadCgroupObjects loads the Cgroup BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/cgroup.bpf.c.
func LoadCgroupObjects(_ *CgroupObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Cgroup program not available (run make generate to compile BPF programs)")
}
