// Package bpf — stub types for the DNS BPF program.
//
// The real DNSObjects / LoadDNSObjects are generated by `make generate`
// (bpf2go compiles bpf/dns.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// dns_bpfel.go / dns_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// DNSMaps holds the BPF maps exported by bpf/dns.bpf.c.
type DNSMaps struct {
	DnsEvents *ebpf.Map `ebpf:"dns_events"`
}

// DNSPrograms holds the BPF programs exported by bpf/dns.bpf.c.
type DNSPrograms struct {
	TraceClose         *ebpf.Program `ebpf:"trace_close"`
	TraceConnect       *ebpf.Program `ebpf:"trace_connect"`
	TraceReadEnter     *ebpf.Program `ebpf:"trace_read_enter"`
	TraceReadExit      *ebpf.Program `ebpf:"trace_read_exit"`
	TraceRecvfromEnter *ebpf.Program `ebpf:"trace_recvfrom_enter"`
	TraceRecvfromExit  *ebpf.Program `ebpf:"trace_recvfrom_exit"`
	TraceRecvmsgEnter  *ebpf.Program `ebpf:"trace_recvmsg_enter"`
	TraceRecvmsgExit   *ebpf.Program `ebpf:"trace_recvmsg_exit"`
	TraceSendmmsg      *ebpf.Program `ebpf:"trace_sendmmsg"`
	TraceSendmsg       *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSendto        *ebpf.Program `ebpf:"trace_sendto"`
	TraceWrite         *ebpf.Program `ebpf:"trace_write"`
	TraceWritev        *ebpf.Program `ebpf:"trace_writev"`
}

// DNSObjects contains all BPF objects after loading bpf/dns.bpf.c.
type DNSObjects struct {
	DNSPrograms
	DNSMaps
}

// Close releases all BPF resources held by the objects.
func (o *DNSObjects) Close() error {
	var errs []error
	if o.TraceClose != nil {
		errs = append(errs, o.TraceClose.Close())
	}
	if o.TraceConnect != nil {
		errs = append(errs, o.TraceConnect.Close())
	}
	if o.TraceReadEnter != nil {
		errs = append(errs, o.TraceReadEnter.Close())
	}
	if o.TraceReadExit != nil {
		errs = append(errs, o.TraceReadExit.Close())
	}
	if o.TraceRecvfromEnter != nil {
		errs = append(errs, o.TraceRecvfromEnter.Close())
	}
	if o.TraceRecvfromExit != nil {
		errs = append(errs, o.TraceRecvfromExit.Close())
	}
	if o.TraceRecvmsgEnter != nil {
		errs = append(errs, o.TraceRecvmsgEnter.Close())
	}
	if o.TraceRecvmsgExit != nil {
		errs = append(errs, o.TraceRecvmsgExit.Close())
	}
	if o.TraceSendmmsg != nil {
		errs = append(errs, o.TraceSendmmsg.Close())
	}
	if o.TraceSendmsg != nil {
		errs = append(errs, o.TraceSendmsg.Close())
	}
	if o.TraceSendto != nil {
		errs = append(errs, o.TraceSendto.Close())
	}
	if o.TraceWrite != nil {
		errs = append(errs, o.TraceWrite.Close())
	}
	if o.TraceWritev != nil {
		errs = append(errs, o.TraceWritev.Close())
	}
	if o.DnsEvents != nil {
		errs = append(errs, o.DnsEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadDNSObjects loads the DNS BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/dns.bpf.c.
func LoadDNSObjects(_ *DNSObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: DNS program not available (run make generate to compile BPF programs)")
}
