// Package bpf provides Go bindings and event parsing for ebpf-guard's BPF programs.
// Event struct types and parsers live here; BPF object types and loaders are
// generated by bpf2go (see generate.go) and regenerated with `make generate`.

package bpf

import (
	"encoding/binary"
	"fmt"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/zugolO/ebpf-guard/pkg/types"
)

// SyscallEvent matches the C struct event from common.h
// Layout matches packed C struct exactly
type SyscallEvent struct {
	Type      uint32
	Timestamp uint64
	PID       uint32
	TGID      uint32
	UID       uint32
	Comm      [16]byte
	// Union payload - syscall specific
	Nr   int64
	Ret  int64
	Args [6]uint64
}

// NetworkEvent matches the C struct event for network events.
// Wire layout (packed, little-endian):
//
//	[0  ] type         uint32   (4)
//	[4  ] timestamp    uint64   (8)
//	[12 ] pid          uint32   (4)
//	[16 ] tgid         uint32   (4)
//	[20 ] ppid         uint32   (4)
//	[24 ] uid          uint32   (4)
//	[28 ] comm         [16]byte (16)
//	[44 ] parent_comm  [16]byte (16)
//	[60 ] saddr        [16]byte (16)
//	[76 ] daddr        [16]byte (16)
//	[92 ] sport        uint16   (2)
//	[94 ] dport        uint16   (2)
//	[96 ] proto        uint8    (1)
//	[97 ] family       uint8    (1)
type NetworkEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	// Union payload - network specific
	Saddr  [16]byte
	Daddr  [16]byte
	Sport  uint16
	Dport  uint16
	Proto  uint8
	Family uint8 // Address family: 2=AF_INET, 10=AF_INET6
}

// FileaccessEvent matches the C struct event for file events.
// Wire layout (packed, little-endian):
//
//	[0  ] type              uint32  (4)
//	[4  ] timestamp         uint64  (8)
//	[12 ] pid               uint32  (4)
//	[16 ] tgid              uint32  (4)
//	[20 ] ppid              uint32  (4)
//	[24 ] uid               uint32  (4)
//	[28 ] comm              [16]byte (16)
//	[44 ] parent_comm       [16]byte (16)
//	[60 ] filename          [256]byte (256)
//	[316] flags             int32   (4)
//	[320] mode              uint32  (4)
//	[324] op                uint8   (1)
//	[325] fd_path_truncated uint8   (1)   — 1 if filename was truncated at 256 bytes
type FileaccessEvent struct {
	Type        uint32
	Timestamp   uint64
	PID         uint32
	TGID        uint32
	PPID        uint32
	UID         uint32
	Comm        [16]byte
	ParentComm  [16]byte
	Filename    [256]byte
	Flags       int32
	Mode        uint32
	Op          uint8
	FDTruncated uint8
}

// PrivescRawEvent is the wire-format event for EVENT_TYPE_PRIVESC.
// old_caps is in args[0], new_caps in args[1] (reusing the syscall union).
type PrivescRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	OldCaps    uint64 // args[0]
	NewCaps    uint64 // args[1]
}

// NetworkCloseRawEvent is the wire-format event for EVENT_TYPE_NET_CLOSE.
// Duration (ns) is encoded in args[0] of the syscall union.
type NetworkCloseRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	// Network tuple (from network union)
	Saddr      [16]byte
	Daddr      [16]byte
	Sport      uint16
	Dport      uint16
	Proto      uint8
	Family     uint8
	DurationNs uint64 // encoded in syscall.args[0]
}

// KmodRawEvent is the wire-format event for EVENT_TYPE_KMOD_LOAD.
// Wire layout (packed):
//
//	[0 ] type        uint32 (4)
//	[4 ] timestamp   uint64 (8)
//	[12] pid         uint32 (4)
//	[16] uid         uint32 (4)
//	[20] comm        [16]byte (16)
//	[36] parent_comm [16]byte (16)
//	[52] ppid        uint32  (4)
//	[56] mod_name    [64]byte (64)
//	[120] from_tmpfs uint8 (1)
type KmodRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	PPID       uint32
	ModName    [64]byte
	FromTmpfs  uint8
}

// CgroupEscapeRawEvent is the wire-format event for EVENT_TYPE_CGROUP_ESC.
// Wire layout (packed):
//
//	[0 ] type          uint32 (4)
//	[4 ] timestamp     uint64 (8)
//	[12] pid           uint32 (4)
//	[16] uid           uint32 (4)
//	[20] comm          [16]byte (16)
//	[36] parent_comm   [16]byte (16)
//	[52] ppid          uint32  (4)
//	[56] init_cgroup_id uint64 (8)
//	[64] new_cgroup_id  uint64 (8)
type CgroupEscapeRawEvent struct {
	Type         uint32
	Timestamp    uint64
	PID          uint32
	UID          uint32
	Comm         [16]byte
	ParentComm   [16]byte
	PPID         uint32
	InitCgroupID uint64
	NewCgroupID  uint64
}

// IOUringRawEvent is the wire-format event for EVENT_TYPE_IO_URING.
// Wire layout (packed, little-endian):
//
//	[0 ] type        uint32   (4)
//	[4 ] timestamp   uint64   (8)
//	[12] pid         uint32   (4)
//	[16] tgid        uint32   (4)
//	[20] ppid        uint32   (4)
//	[24] uid         uint32   (4)
//	[28] comm        [16]byte (16)
//	[44] parent_comm [16]byte (16)
//	[60] op          uint8    (1)
//	[61] flags       uint32   (4)
//	[65] fd          int32    (4)
//	[69] to_submit   uint32   (4)
//
// Total: 73 bytes
type IOUringRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	Op         uint8
	Flags      uint32
	Fd         int32
	ToSubmit   uint32
}

// BpfMonitorRawEvent is the wire-format event for EVENT_TYPE_BPF_PROGRAM.
// Wire layout (packed, little-endian):
//
//	[0 ] type        uint32   (4)
//	[4 ] timestamp   uint64   (8)
//	[12] pid         uint32   (4)
//	[16] tgid        uint32   (4)
//	[20] ppid        uint32   (4)
//	[24] uid         uint32   (4)
//	[28] comm        [16]byte (16)
//	[44] parent_comm [16]byte (16)
//	[60] cmd         uint32   (4)
//	[64] prog_type   uint32   (4)
//	[68] ret         int32    (4)
//
// Total: 72 bytes
type BpfMonitorRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	Cmd        uint32
	ProgType   uint32
	Ret        int32
}

// TlsClientHelloRawEvent is the wire-format event for captured ClientHello data.
// Wire layout (packed, little-endian):
//
//	[0  ] type          uint32    (4)
//	[4  ] timestamp     uint64    (8)
//	[12 ] pid           uint32    (4)
//	[16 ] tgid          uint32    (4)
//	[20 ] ppid          uint32    (4)
//	[24 ] uid           uint32    (4)
//	[28 ] comm          [16]byte  (16)
//	[44 ] parent_comm   [16]byte  (16)
//	[60 ] dport         uint16    (2)
//	[62 ] captured_len  uint16    (2)
//	[64 ] original_len  uint32    (4)
//	[68 ] data          [512]byte (512)
//
// Total: 580 bytes
type TlsClientHelloRawEvent struct {
	Type        uint32
	Timestamp   uint64
	PID         uint32
	TGID        uint32
	PPID        uint32
	UID         uint32
	Comm        [16]byte
	ParentComm  [16]byte
	Dport       uint16
	CapturedLen uint16
	OriginalLen uint32
	Data        [512]byte
}

// -----------------------------------------------------------------------
// RingbufReader
// -----------------------------------------------------------------------

// RingbufReader wraps ringbuf.Reader for type-safe event reading.
type RingbufReader struct {
	reader *ringbuf.Reader
}

// NewRingbufReader creates a new ring buffer reader from an eBPF map.
func NewRingbufReader(events *ebpf.Map) (*RingbufReader, error) {
	reader, err := ringbuf.NewReader(events)
	if err != nil {
		return nil, err
	}
	return &RingbufReader{reader: reader}, nil
}

// Close closes the ring buffer reader.
func (r *RingbufReader) Close() error {
	if r.reader != nil {
		return r.reader.Close()
	}
	return nil
}

// Read reads the next event from the ring buffer.
func (r *RingbufReader) Read() (ringbuf.Record, error) {
	return r.reader.Read()
}

// -----------------------------------------------------------------------
// Parse functions
// -----------------------------------------------------------------------

// ParseSyscallEventInto parses raw bytes into an existing SyscallEvent,
// avoiding a heap allocation on the hot path. Prefer this over ParseSyscallEvent
// when the caller can provide a stack-allocated or pooled struct.
func ParseSyscallEventInto(raw []byte, out *SyscallEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 16 + 8 + 8 + 48 // 104 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	offset := 0
	out.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	out.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(out.Comm[:], raw[offset:offset+16])
	offset += 16
	out.Nr = int64(binary.LittleEndian.Uint64(raw[offset:]))  /* #nosec G115 */
	offset += 8
	out.Ret = int64(binary.LittleEndian.Uint64(raw[offset:])) /* #nosec G115 */
	offset += 8
	for i := 0; i < 6; i++ {
		out.Args[i] = binary.LittleEndian.Uint64(raw[offset:])
		offset += 8
	}
	return nil
}

// ParseSyscallEvent parses raw bytes into a SyscallEvent.
// Uses manual parsing to match packed C struct layout.
// For the allocation-free hot path, use ParseSyscallEventInto instead.
func ParseSyscallEvent(raw []byte) (*SyscallEvent, error) {
	out := new(SyscallEvent)
	return out, ParseSyscallEventInto(raw, out)
}

// ParseNetworkEventInto parses raw bytes into an existing NetworkEvent,
// avoiding a heap allocation on the hot path.
func ParseNetworkEventInto(raw []byte, out *NetworkEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 16 + 16 + 2 + 2 + 1 + 1 // 98 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	offset := 0
	out.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	out.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.PPID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(out.Comm[:], raw[offset:offset+16])
	offset += 16
	copy(out.ParentComm[:], raw[offset:offset+16])
	offset += 16
	copy(out.Saddr[:], raw[offset:offset+16])
	offset += 16
	copy(out.Daddr[:], raw[offset:offset+16])
	offset += 16
	out.Sport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	out.Dport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	out.Proto = raw[offset]
	offset++
	out.Family = raw[offset]
	return nil
}

// ParseNetworkEvent parses raw bytes into a NetworkEvent.
// For the allocation-free hot path, use ParseNetworkEventInto instead.
func ParseNetworkEvent(raw []byte) (*NetworkEvent, error) {
	out := new(NetworkEvent)
	return out, ParseNetworkEventInto(raw, out)
}

// ParseFileaccessEventInto parses raw bytes into an existing FileaccessEvent,
// avoiding a heap allocation on the hot path.
// Wire layout: type(4) ts(8) pid(4) tgid(4) ppid(4) uid(4) comm(16)
// parent_comm(16) filename(256) flags(4) mode(4) op(1) fd_path_truncated(1) = 326 bytes.
func ParseFileaccessEventInto(raw []byte, out *FileaccessEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 256 + 4 + 4 + 1 + 1 // 326 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	copy(out.Filename[:], raw[off:off+256])
	off += 256
	out.Flags = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	off += 4
	out.Mode = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Op = raw[off]
	off++
	out.FDTruncated = raw[off]
	return nil
}

// ParseFileaccessEvent parses raw bytes into a FileaccessEvent.
// For the allocation-free hot path, use ParseFileaccessEventInto instead.
func ParseFileaccessEvent(raw []byte) (*FileaccessEvent, error) {
	out := new(FileaccessEvent)
	return out, ParseFileaccessEventInto(raw, out)
}

// ParsePrivescEventInto parses a raw ring-buffer sample into an existing PrivescRawEvent,
// avoiding a heap allocation on the hot path.
// Wire layout (packed): type(4) ts(8) pid(4) tgid(4) ppid(4) uid(4) comm(16)
//
//	parent_comm(16) nr(8) ret(8) args[0](8)=old_caps args[1](8)=new_caps ...
func ParsePrivescEventInto(raw []byte, out *PrivescRawEvent) error {
	// header: 4+8+4+4+4+4+16+16 = 60 bytes; then syscall union: 8+8+8+8 = 32 bytes minimum
	const minSize = 60 + 8 + 8 + 8 + 8
	if len(raw) < minSize {
		return fmt.Errorf("privesc raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	// skip nr(8) and ret(8)
	off += 16
	out.OldCaps = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.NewCaps = binary.LittleEndian.Uint64(raw[off:])
	return nil
}

// ParsePrivescEvent parses a raw ring-buffer sample into a PrivescRawEvent.
// For the allocation-free hot path, use ParsePrivescEventInto instead.
func ParsePrivescEvent(raw []byte) (*PrivescRawEvent, error) {
	out := new(PrivescRawEvent)
	return out, ParsePrivescEventInto(raw, out)
}

// ParseNetworkCloseEvent parses a raw ring-buffer sample for EVENT_NET_CLOSE.
// The BPF program writes the network tuple in the network union fields and
// then overlays duration_ns into the first 8 bytes of the syscall args
// (args[0]). Because the C struct union shares the same memory, we read
// the network fields from their fixed offsets and duration from the syscall
// args[0] offset.
//
// Wire layout (packed, little-endian):
//
//	[0 ]  type        uint32   (4)
//	[4 ]  timestamp   uint64   (8)
//	[12]  pid         uint32   (4)
//	[16]  tgid        uint32   (4)
//	[20]  ppid        uint32   (4)
//	[24]  uid         uint32   (4)
//	[28]  comm        [16]byte (16)
//	[44]  parent_comm [16]byte (16)
//	[60]  union start — network layout:
//	      saddr [16], daddr [16], sport u16, dport u16, proto u8, family u8
//	[60]  union start — syscall layout (same offset):
//	      nr s64(8), ret s64(8), args[0] u64(8) = duration_ns
//
// We read the network fields first (saddr starts at 60), then read
// duration_ns from offset 60+8+8 = 76 (args[0] in the syscall layout).
// ParseNetworkCloseEventInto parses a raw ring-buffer sample into an existing
// NetworkCloseRawEvent, avoiding a heap allocation on the hot path.
func ParseNetworkCloseEventInto(raw []byte, out *NetworkCloseRawEvent) error {
	const networkUnionOffset = 60
	const durationOffset = networkUnionOffset + 8 + 8 // skip nr + ret
	const minSize = durationOffset + 8
	if len(raw) < minSize {
		return fmt.Errorf("net_close raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	// off == 60 == networkUnionOffset
	copy(out.Saddr[:], raw[off:off+16])
	off += 16
	copy(out.Daddr[:], raw[off:off+16])
	off += 16
	out.Sport = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.Dport = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.Proto = raw[off]
	off++
	out.Family = raw[off]
	// Read duration_ns from syscall union args[0] offset.
	out.DurationNs = binary.LittleEndian.Uint64(raw[durationOffset:])
	return nil
}

// ParseNetworkCloseEvent parses a raw ring-buffer sample for EVENT_NET_CLOSE.
// For the allocation-free hot path, use ParseNetworkCloseEventInto instead.
func ParseNetworkCloseEvent(raw []byte) (*NetworkCloseRawEvent, error) {
	out := new(NetworkCloseRawEvent)
	return out, ParseNetworkCloseEventInto(raw, out)
}

// ParseKmodEventInto parses a raw ring-buffer sample into an existing KmodRawEvent,
// avoiding a heap allocation on the hot path.
func ParseKmodEventInto(raw []byte, out *KmodRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 16 + 16 + 4 + 64 + 1 // 121 bytes
	if len(raw) < minSize {
		return fmt.Errorf("kmod raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.ModName[:], raw[off:off+64])
	off += 64
	out.FromTmpfs = raw[off]
	return nil
}

// ParseKmodEvent parses a raw ring-buffer sample for EVENT_TYPE_KMOD_LOAD.
// For the allocation-free hot path, use ParseKmodEventInto instead.
func ParseKmodEvent(raw []byte) (*KmodRawEvent, error) {
	out := new(KmodRawEvent)
	return out, ParseKmodEventInto(raw, out)
}

// ParseCgroupEscapeEventInto parses a raw ring-buffer sample into an existing
// CgroupEscapeRawEvent, avoiding a heap allocation on the hot path.
func ParseCgroupEscapeEventInto(raw []byte, out *CgroupEscapeRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 16 + 16 + 4 + 8 + 8 // 72 bytes
	if len(raw) < minSize {
		return fmt.Errorf("cgroup_esc raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.InitCgroupID = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.NewCgroupID = binary.LittleEndian.Uint64(raw[off:])
	return nil
}

// ParseCgroupEscapeEvent parses a raw ring-buffer sample for EVENT_TYPE_CGROUP_ESC.
// For the allocation-free hot path, use ParseCgroupEscapeEventInto instead.
func ParseCgroupEscapeEvent(raw []byte) (*CgroupEscapeRawEvent, error) {
	out := new(CgroupEscapeRawEvent)
	return out, ParseCgroupEscapeEventInto(raw, out)
}

// ParseIOUringEventInto parses a raw ring-buffer sample into an existing IOUringRawEvent,
// avoiding a heap allocation on the hot path.
func ParseIOUringEventInto(raw []byte, out *IOUringRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 1 + 4 + 4 + 4 // 73 bytes
	if len(raw) < minSize {
		return fmt.Errorf("iouring raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Op = raw[off]
	off++
	out.Flags = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Fd = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	off += 4
	out.ToSubmit = binary.LittleEndian.Uint32(raw[off:])
	return nil
}

// ParseIOUringEvent parses a raw ring-buffer sample for EVENT_TYPE_IO_URING.
// For the allocation-free hot path, use ParseIOUringEventInto instead.
func ParseIOUringEvent(raw []byte) (*IOUringRawEvent, error) {
	out := new(IOUringRawEvent)
	return out, ParseIOUringEventInto(raw, out)
}

// ParseBpfMonitorEventInto parses a raw ring-buffer sample into an existing
// BpfMonitorRawEvent, avoiding a heap allocation on the hot path.
func ParseBpfMonitorEventInto(raw []byte, out *BpfMonitorRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 4 + 4 + 4 // 72 bytes
	if len(raw) < minSize {
		return fmt.Errorf("bpf_monitor raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Cmd = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.ProgType = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Ret = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	return nil
}

// ParseBpfMonitorEvent parses a raw ring-buffer sample for EVENT_TYPE_BPF_PROGRAM.
// For the allocation-free hot path, use ParseBpfMonitorEventInto instead.
func ParseBpfMonitorEvent(raw []byte) (*BpfMonitorRawEvent, error) {
	out := new(BpfMonitorRawEvent)
	return out, ParseBpfMonitorEventInto(raw, out)
}

// ParseTlsClientHelloEventInto parses a raw ring-buffer sample into an existing
// TlsClientHelloRawEvent, avoiding a heap allocation on the hot path.
func ParseTlsClientHelloEventInto(raw []byte, out *TlsClientHelloRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 2 + 2 + 4 + 1 // 69 bytes min
	if len(raw) < minSize {
		return fmt.Errorf("tls_clienthello raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Dport = binary.BigEndian.Uint16(raw[off:])
	off += 2 // network byte order
	out.CapturedLen = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.OriginalLen = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	if out.CapturedLen > 512 {
		out.CapturedLen = 512
	}
	copy(out.Data[:], raw[off:off+int(out.CapturedLen)])
	return nil
}

// ParseTlsClientHelloEvent parses a raw ring-buffer sample for a ClientHello event.
// For the allocation-free hot path, use ParseTlsClientHelloEventInto instead.
func ParseTlsClientHelloEvent(raw []byte) (*TlsClientHelloRawEvent, error) {
	out := new(TlsClientHelloRawEvent)
	return out, ParseTlsClientHelloEventInto(raw, out)
}

// -----------------------------------------------------------------------
// ToTypesEvent converters
// -----------------------------------------------------------------------

// ToTypesEvent converts a SyscallEvent to types.Event.
func (e *SyscallEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:      types.EventSyscall,
		Timestamp: e.Timestamp,
		PID:       e.PID,
		TGID:      e.TGID,
		UID:       e.UID,
		Comm:      e.Comm,
		Syscall: &types.SyscallEvent{
			Nr:   e.Nr,
			Ret:  e.Ret,
			Args: e.Args,
		},
	}
}

// ToTypesEvent converts a NetworkEvent to types.Event.
func (e *NetworkEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventTCPConnect,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Network: &types.NetworkEvent{
			Saddr:  e.Saddr,
			Daddr:  e.Daddr,
			Sport:  e.Sport,
			Dport:  e.Dport,
			Proto:  e.Proto,
			Family: types.AddressFamily(e.Family),
		},
	}
}

// ToTypesEvent converts a FileaccessEvent to types.Event.
// FDPath is populated for all ops: for open events it mirrors Filename; for
// read/write events the BPF program resolved it via the fd→path map.
func (e *FileaccessEvent) ToTypesEvent() types.Event {
	fdPath := nullTerminatedString(e.Filename[:])
	return types.Event{
		Type:       types.EventFileAccess,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		File: &types.FileEvent{
			Filename:        e.Filename,
			Flags:           e.Flags,
			Mode:            e.Mode,
			Op:              e.Op,
			FDPath:          fdPath,
			FDPathTruncated: e.FDTruncated != 0,
		},
	}
}

// ToTypesEvent converts a PrivescRawEvent to types.Event.
func (e *PrivescRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventPrivesc,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Privesc: &types.PrivescEvent{
			OldCaps: e.OldCaps,
			NewCaps: e.NewCaps,
		},
	}
}

// ToTypesEvent converts a NetworkCloseRawEvent to types.Event.
func (e *NetworkCloseRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventNetClose,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		NetClose: &types.NetworkCloseEvent{
			Saddr:    e.Saddr,
			Daddr:    e.Daddr,
			Sport:    e.Sport,
			Dport:    e.Dport,
			Family:   types.AddressFamily(e.Family),
			Duration: time.Duration(e.DurationNs),
		},
	}
}

// ToTypesEvent converts a KmodRawEvent to types.Event.
func (e *KmodRawEvent) ToTypesEvent() types.Event {
	// Trim null bytes from mod name.
	name := e.ModName[:]
	for i, b := range name {
		if b == 0 {
			name = e.ModName[:i]
			break
		}
	}
	return types.Event{
		Type:       types.EventKmodLoad,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		UID:        e.UID,
		PPID:       e.PPID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Kmod: &types.KmodEvent{
			ModName:   string(name),
			FromTmpfs: e.FromTmpfs != 0,
		},
	}
}

// ToTypesEvent converts a CgroupEscapeRawEvent to types.Event.
func (e *CgroupEscapeRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventCgroupEsc,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		UID:        e.UID,
		PPID:       e.PPID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		CgroupEsc: &types.CgroupEscapeEvent{
			InitCgroupID: e.InitCgroupID,
			NewCgroupID:  e.NewCgroupID,
		},
	}
}

// ToTypesEvent converts an IOUringRawEvent to types.Event.
func (e *IOUringRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventIOUring,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		IOUring: &types.IOUringEvent{
			Op:       e.Op,
			Flags:    e.Flags,
			Fd:       e.Fd,
			ToSubmit: e.ToSubmit,
		},
	}
}

// ToTypesEvent converts a BpfMonitorRawEvent to types.Event.
func (e *BpfMonitorRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventBPFProgram,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		BPFProgram: &types.BPFProgramEvent{
			Cmd:      e.Cmd,
			ProgType: e.ProgType,
			Ret:      e.Ret,
		},
	}
}

// ToTypesEvent converts a TlsClientHelloRawEvent to types.Event.
// The JA3/JA4/JA3S fields are left empty here; they are computed by the
// collector after parsing to avoid circular imports from the ja3 package.
func (e *TlsClientHelloRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventTLS,
		Timestamp:  e.Timestamp,
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		TLS: &types.TLSEvent{
			DataLen: e.OriginalLen,
		},
	}
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

// nullTerminatedString converts a byte slice to a Go string, stopping at the
// first NUL byte. Used to convert fixed-size C string arrays.
func nullTerminatedString(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}
