// Package bpf provides Go bindings and event parsing for ebpf-guard's BPF programs.
// Event struct types and parsers live here; BPF object types and loaders are
// generated by bpf2go (see generate.go) and regenerated with `make generate`.

package bpf

import (
	"encoding/binary"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/zugolO/ebpf-guard/pkg/types"
)

// EventTypeSyscall mirrors EVENT_TYPE_SYSCALL from bpf/common.h. Wave 5.9.2c
// (finding #40): the syscall ring buffer is meant to carry only this type —
// nothing else reserves an event on it in bpf/syscall.bpf.c — so a record
// whose own Type field disagrees is evidence of a wire-format problem, not a
// legitimate event to hand to the correlator.
const EventTypeSyscall uint32 = 1

// EventCgroupIDOffset is offsetof(struct event, cgroup_id) in bpf/common.h: the
// 60-byte header plus the 272-byte union (its 266-byte file payload is padded
// to 268 and the union aligned to 8 — measured with offsetof, not summed from
// the field list; the parsers' 326-byte minimum is a read bound, not this
// offset). cgroup_id (item 10 wave 6.6) is the 8 bytes AT it; a record shorter
// than EventCgroupIDOffset+8 comes from an older BPF object and yields 0.
const EventCgroupIDOffset = 332

// Wave 6.6 revision item 8: the same trailing cgroup_id, appended to the event
// structs that struct event's item 10 did not cover, so kmod, DNS and both TLS
// producers stop going past the pid->pod recovery in internal/k8s/enricher.go.
// Each offset is a LITERAL measured with offsetof on host clang against the
// struct in bpf/, and each has a _Static_assert on the C side: a moved field and
// a moved constant here cannot agree by construction.
const (
	// KmodEventCgroupIDOffset is offsetof(struct kmod_event, cgroup_id)
	// (bpf/common.h); sizeof(struct kmod_event) = 129.
	KmodEventCgroupIDOffset = 121
	// DNSEventCgroupIDOffset is offsetof(struct dns_event, cgroup_id)
	// (bpf/dns.bpf.c); sizeof(struct dns_event) = 327.
	DNSEventCgroupIDOffset = 319
	// TLSEventCgroupIDOffset is offsetof(struct tls_event, cgroup_id)
	// (bpf/tls_uprobe.bpf.c); sizeof(struct tls_event) = 370.
	TLSEventCgroupIDOffset = 362
	// TLSClientHelloCgroupIDOffset is
	// offsetof(struct tls_clienthello_event, cgroup_id)
	// (bpf/tls_clienthello.bpf.c); sizeof = 588. Finding №488: that struct was
	// the only event struct in bpf/ missing __attribute__((packed)) while this
	// package's parser always walked packed offsets — the attribute is now
	// there, and the offsets are asserted in C rather than described in a
	// comment.
	TLSClientHelloCgroupIDOffset = 580
	// HTTPEventCgroupIDOffset is offsetof(struct http_event, cgroup_id)
	// (bpf/http_uprobe.bpf.c); sizeof(struct http_event) = 333. Task 1 of the
	// wave 6.6 revision follow-up list: item 8 named kmod/dns/tls but not this
	// collector's own struct. Without it an HTTP event whose process has exited
	// before /proc/<pid>/cgroup is read loses its container identity.
	HTTPEventCgroupIDOffset = 325
	// LSMAuditEventCgroupIDOffset is offsetof(struct lsm_audit_event, cgroup_id)
	// (bpf/common.h); sizeof = 115. The id is the CURRENT task's — the pid the
	// record names (on task_kill the signal SENDER, not target_pid).
	LSMAuditEventCgroupIDOffset = 107
)

// cgroupIDTail reads the trailing in-kernel cgroup id, 0 if the record lacks it.
func cgroupIDTail(raw []byte) uint64 {
	return cgroupIDTailAt(raw, EventCgroupIDOffset)
}

// DNSCgroupIDFromRecord reads the trailing in-kernel cgroup id of a raw
// struct dns_event record (wave 6.6 revision item 8), 0 if the record is from a
// BPF object built before it. The DNS collector decodes its records itself
// rather than through a RawEvent mirror, so the read is exported here — the
// offset stays in one place, next to the offsets it is asserted against in C.
func DNSCgroupIDFromRecord(raw []byte) uint64 {
	return cgroupIDTailAt(raw, DNSEventCgroupIDOffset)
}

// TLSCgroupIDFromRecord reads the trailing in-kernel cgroup id of a raw
// struct tls_event record (wave 6.6 revision item 8), 0 if absent.
func TLSCgroupIDFromRecord(raw []byte) uint64 {
	return cgroupIDTailAt(raw, TLSEventCgroupIDOffset)
}

// HTTPCgroupIDFromRecord reads the trailing in-kernel cgroup id of a raw
// struct http_event record (wave 6.6 revision follow-up, task 1), 0 if the
// record is from a BPF object built before it. Read by offset rather than
// added to HTTPEventRaw on purpose, exactly as TLSCgroupIDFromRecord is kept
// out of TLSEventRaw: httpEventRawSize is derived from that mirror and gates
// binary.Read in HTTPCollector.parseEvent, so a new mirror field would make a
// record from an older BPF object fail to parse at all instead of simply
// carrying no cgroup id.
func HTTPCgroupIDFromRecord(raw []byte) uint64 {
	return cgroupIDTailAt(raw, HTTPEventCgroupIDOffset)
}

// LSMAuditCgroupIDFromRecord reads the trailing in-kernel cgroup id of a raw
// struct lsm_audit_event record, 0 if the record is from a BPF object built
// before it. Read by offset for the same reason as HTTPCgroupIDFromRecord:
// lsmAuditEventSize (internal/collector) is derived from its mirror and gates
// the parse, so a mirror field would make a 107-byte record unparseable.
func LSMAuditCgroupIDFromRecord(raw []byte) uint64 {
	return cgroupIDTailAt(raw, LSMAuditEventCgroupIDOffset)
}

// cgroupIDTailAt reads a trailing in-kernel cgroup id at a given offset. A record
// shorter than off+8 comes from an older BPF object and yields 0 — which is why
// every caller treats 0 as "this record carries no cgroup id", never as "cgroup
// zero": the recovery path in internal/k8s/enricher.go skips 0 explicitly.
func cgroupIDTailAt(raw []byte, off int) uint64 {
	if len(raw) < off+8 {
		return 0
	}
	return binary.LittleEndian.Uint64(raw[off:])
}

// SyscallEvent matches the C struct event from common.h
// Layout matches packed C struct exactly
// SyscallEvent matches the C struct event for syscall events.
// Wire layout (packed, little-endian) — verified against offsetof() on the
// compiled struct, not against this Go struct:
//
//	[0  ] type         uint32   (4)
//	[4  ] timestamp    uint64   (8)
//	[12 ] pid          uint32   (4)
//	[16 ] tgid         uint32   (4)
//	[20 ] ppid         uint32   (4)
//	[24 ] uid          uint32   (4)
//	[28 ] comm         [16]byte
//	[44 ] parent_comm  [16]byte
//	[60 ] nr           int64    (8)   ← union payload starts here
//	[68 ] ret          int64    (8)
//	[76 ] args         [6]uint64 (48)
type SyscallEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	// Union payload - syscall specific
	Nr   int64
	Ret  int64
	Args [6]uint64
	// CgroupID is the record's trailing cgroup_id (offset EventCgroupIDOffset).
	CgroupID uint64
}

// NetworkEvent matches the C struct event for network events.
// Wire layout (packed, little-endian):
//
//	[0  ] type         uint32   (4)
//	[4  ] timestamp    uint64   (8)
//	[12 ] pid          uint32   (4)
//	[16 ] tgid         uint32   (4)
//	[20 ] ppid         uint32   (4)
//	[24 ] uid          uint32   (4)
//	[28 ] comm         [16]byte (16)
//	[44 ] parent_comm  [16]byte (16)
//	[60 ] saddr        [16]byte (16)
//	[76 ] daddr        [16]byte (16)
//	[92 ] sport        uint16   (2)
//	[94 ] dport        uint16   (2)
//	[96 ] proto        uint8    (1)
//	[97 ] family       uint8    (1)
type NetworkEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	// Union payload - network specific
	Saddr  [16]byte
	Daddr  [16]byte
	Sport  uint16
	Dport  uint16
	Proto  uint8
	Family uint8 // Address family: 2=AF_INET, 10=AF_INET6
	// CgroupID is the record's trailing cgroup_id (offset EventCgroupIDOffset).
	CgroupID uint64
}

// FileaccessEvent matches the C struct event for file events.
// Wire layout (packed, little-endian):
//
//	[0  ] type              uint32  (4)
//	[4  ] timestamp         uint64  (8)
//	[12 ] pid               uint32  (4)
//	[16 ] tgid              uint32  (4)
//	[20 ] ppid              uint32  (4)
//	[24 ] uid               uint32  (4)
//	[28 ] comm              [16]byte (16)
//	[44 ] parent_comm       [16]byte (16)
//	[60 ] filename          [256]byte (256)
//	[316] flags             int32   (4)
//	[320] mode              uint32  (4)
//	[324] op                uint8   (1)
//	[325] fd_path_truncated uint8   (1)   — 1 if filename was truncated at 256 bytes
type FileaccessEvent struct {
	Type        uint32
	Timestamp   uint64
	PID         uint32
	TGID        uint32
	PPID        uint32
	UID         uint32
	Comm        [16]byte
	ParentComm  [16]byte
	Filename    [256]byte
	Flags       int32
	Mode        uint32
	Op          uint8
	FDTruncated uint8
	CgroupID    uint64 // trailing cgroup_id (offset EventCgroupIDOffset)
}

// PrivescRawEvent is the wire-format event for EVENT_TYPE_PRIVESC.
// old_caps is in args[0], new_caps in args[1] (reusing the syscall union).
type PrivescRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	OldCaps    uint64 // args[0]
	NewCaps    uint64 // args[1]
}

// NetworkCloseRawEvent is the wire-format event for EVENT_TYPE_NET_CLOSE.
// Duration (ns) is encoded in args[0] of the syscall union.
type NetworkCloseRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	// Network tuple (from network union)
	Saddr      [16]byte
	Daddr      [16]byte
	Sport      uint16
	Dport      uint16
	Proto      uint8
	Family     uint8
	DurationNs uint64 // encoded in syscall.args[0]
}

// KmodRawEvent is the wire-format event for EVENT_TYPE_KMOD_LOAD.
// Wire layout (packed):
//
//	[0 ] type        uint32 (4)
//	[4 ] timestamp   uint64 (8)
//	[12] pid         uint32 (4)
//	[16] uid         uint32 (4)
//	[20] comm        [16]byte (16)
//	[36] parent_comm [16]byte (16)
//	[52] ppid        uint32  (4)
//	[56] mod_name    [64]byte (64)
//	[120] from_tmpfs uint8 (1)
type KmodRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	PPID       uint32
	ModName    [64]byte
	FromTmpfs  uint8
	// CgroupID is the trailing cgroup_id (offset KmodEventCgroupIDOffset),
	// 0 on a record from a BPF object built before wave 6.6 revision item 8.
	CgroupID uint64
}

// CgroupEscapeRawEvent is the wire-format event for EVENT_TYPE_CGROUP_ESC.
// Wire layout (packed):
//
//	[0 ] type          uint32 (4)
//	[4 ] timestamp     uint64 (8)
//	[12] pid           uint32 (4)
//	[16] uid           uint32 (4)
//	[20] comm          [16]byte (16)
//	[36] parent_comm   [16]byte (16)
//	[52] ppid          uint32  (4)
//	[56] init_cgroup_id uint64 (8)
//	[64] new_cgroup_id  uint64 (8)
type CgroupEscapeRawEvent struct {
	Type         uint32
	Timestamp    uint64
	PID          uint32
	UID          uint32
	Comm         [16]byte
	ParentComm   [16]byte
	PPID         uint32
	InitCgroupID uint64
	NewCgroupID  uint64
}

// IOUringRawEvent is the wire-format event for EVENT_TYPE_IO_URING.
// Wire layout (packed, little-endian):
//
//	[0 ] type        uint32   (4)
//	[4 ] timestamp   uint64   (8)
//	[12] pid         uint32   (4)
//	[16] tgid        uint32   (4)
//	[20] ppid        uint32   (4)
//	[24] uid         uint32   (4)
//	[28] comm        [16]byte (16)
//	[44] parent_comm [16]byte (16)
//	[60] op          uint8    (1)
//	[61] flags       uint32   (4)
//	[65] fd          int32    (4)
//	[69] to_submit   uint32   (4)
//
// Total: 73 bytes
type IOUringRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	Op         uint8
	Flags      uint32
	Fd         int32
	ToSubmit   uint32
}

// BpfMonitorRawEvent is the wire-format event for EVENT_TYPE_BPF_PROGRAM.
// Wire layout (packed, little-endian):
//
//	[0 ] type        uint32   (4)
//	[4 ] timestamp   uint64   (8)
//	[12] pid         uint32   (4)
//	[16] tgid        uint32   (4)
//	[20] ppid        uint32   (4)
//	[24] uid         uint32   (4)
//	[28] comm        [16]byte (16)
//	[44] parent_comm [16]byte (16)
//	[60] cmd         uint32   (4)
//	[64] prog_type   uint32   (4)
//	[68] ret         int32    (4)
//
// Total: 72 bytes
type BpfMonitorRawEvent struct {
	Type       uint32
	Timestamp  uint64
	PID        uint32
	TGID       uint32
	PPID       uint32
	UID        uint32
	Comm       [16]byte
	ParentComm [16]byte
	Cmd        uint32
	ProgType   uint32
	Ret        int32
}

// TlsClientHelloRawEvent is the wire-format event for captured ClientHello data.
// Wire layout (packed, little-endian):
//
//	[0  ] type          uint32    (4)
//	[4  ] timestamp     uint64    (8)
//	[12 ] pid           uint32    (4)
//	[16 ] tgid          uint32    (4)
//	[20 ] ppid          uint32    (4)
//	[24 ] uid           uint32    (4)
//	[28 ] comm          [16]byte  (16)
//	[44 ] parent_comm   [16]byte  (16)
//	[60 ] dport         uint16    (2)
//	[62 ] captured_len  uint16    (2)
//	[64 ] original_len  uint32    (4)
//	[68 ] data          [512]byte (512)
//
// Total: 580 bytes
type TlsClientHelloRawEvent struct {
	Type        uint32
	Timestamp   uint64
	PID         uint32
	TGID        uint32
	PPID        uint32
	UID         uint32
	Comm        [16]byte
	ParentComm  [16]byte
	Dport       uint16
	CapturedLen uint16
	OriginalLen uint32
	Data        [512]byte
	// CgroupID is the trailing cgroup_id (offset TLSClientHelloCgroupIDOffset),
	// 0 on a record from a BPF object built before wave 6.6 revision item 8.
	CgroupID uint64
}

// -----------------------------------------------------------------------
// RingbufReader
// -----------------------------------------------------------------------

// RingbufReader wraps ringbuf.Reader for type-safe event reading.
type RingbufReader struct {
	reader ringbufCore

	// wait is non-nil only on the netpoll path (wave 8.1 item 6); see
	// ringbuf_netpoll.go. nil means the plain blocking ringbuf.Reader, which is
	// the default and the control branch of the A/B.
	wait ringWaiter
	name string
	// onWait/onFallback report to /metrics. They are injected rather than
	// called directly because internal/bpf must not import internal/exporter:
	// exporter imports correlator, and correlator's in-package tests import
	// internal/bpf, which would close an import cycle in that test binary.
	onWait     func()
	onFallback func(reason, detail string)

	// ReadInto/Read are called from one goroutine per reader (the collector's
	// readLoop), so the downgrade below needs no lock — same contract
	// ringbuf.Reader's own buffer reuse already relies on.
	fellBack bool
}

// RingbufReaderOptions configures a reader. The zero value is the blocking
// reader this package has always returned.
type RingbufReaderOptions struct {
	// Name is the collector label used in logs and metrics.
	Name string
	// Netpoll asks for the netpoll wait path (wave 8.1 item 6). A platform or
	// an fd that cannot support it is NOT an error: the reader downgrades to
	// the blocking path and says so through OnFallback.
	Netpoll bool
	// OnWait is called once per park on the netpoll path.
	OnWait func()
	// OnFallback is called once if the netpoll path is refused or abandoned,
	// with one of RingbufFallback* as reason and the full error text as detail.
	OnFallback func(reason, detail string)
}

// NewRingbufReader creates a new ring buffer reader from an eBPF map, waiting
// for samples in a blocking epoll_wait inside cilium/ebpf.
func NewRingbufReader(events *ebpf.Map) (*RingbufReader, error) {
	return NewRingbufReaderWithOptions(events, RingbufReaderOptions{})
}

// NewRingbufReaderWithOptions creates a reader and, if asked, puts its wait on
// the Go runtime netpoller instead of a blocking syscall.
func NewRingbufReaderWithOptions(events *ebpf.Map, opts RingbufReaderOptions) (*RingbufReader, error) {
	reader, err := ringbuf.NewReader(events)
	if err != nil {
		return nil, err
	}

	return newRingbufReader(reader, events.FD(), opts, newRingWaiter), nil
}

// newRingbufReader assembles a reader around an already-open ring. The waiter
// factory is a parameter so the park loop and its downgrade can be tested
// without a kernel: nothing on a developer machine can produce a real
// ringbuf.Reader, and this loop is the one piece of the event path the fix
// moves ([[self-test-fixtures-miss-live-log-shape]] — a fixture elsewhere
// proves nothing about it).
func newRingbufReader(core ringbufCore, fd int, opts RingbufReaderOptions, newWaiter func(int) (ringWaiter, error)) *RingbufReader {
	r := &RingbufReader{
		reader:     core,
		name:       opts.Name,
		onWait:     opts.OnWait,
		onFallback: opts.OnFallback,
	}
	if !opts.Netpoll {
		return r
	}

	waiter, werr := newWaiter(fd)
	if werr != nil {
		// Not fatal: the stream matters more than the optimisation.
		r.reportFallback(RingbufFallbackUnsupported, werr.Error())
		return r
	}
	r.wait = waiter
	r.reader.SetDeadline(ringNoBlockDeadline)
	return r
}

// Mode reports which wait path this reader actually runs, so a reading of the
// toggle comes from the runtime and not from the config file
// ([[entry-guard-must-read-runtime-not-config]]).
func (r *RingbufReader) Mode() string {
	if r.wait != nil {
		return RingbufWaitModeNetpoll
	}
	return RingbufWaitModeBlocking
}

// Close closes the ring buffer reader. On the netpoll path it also closes the
// poller file, which is what interrupts a parked ReadInto — closing only the
// cilium reader would leave the collector's readLoop parked forever.
func (r *RingbufReader) Close() error {
	var waitErr error
	if r.wait != nil {
		waitErr = r.wait.Close()
	}
	var readErr error
	if r.reader != nil {
		readErr = r.reader.Close()
	}
	if readErr != nil {
		return readErr
	}
	return waitErr
}

// Read reads the next event from the ring buffer.
func (r *RingbufReader) Read() (ringbuf.Record, error) {
	if r.wait == nil {
		return r.reader.Read()
	}
	var rec ringbuf.Record
	return rec, r.ReadInto(&rec)
}

// ReadInto reads the next event into rec, reusing rec's RawSample buffer
// (wave 8.1 item 12). Read allocates a fresh Record, and so a fresh RawSample,
// per ring-buffer record; at ~1300 events/s that was 2.5% of allocated bytes.
// The caller must finish with rec.RawSample — parse it, copying everything that
// outlives the call — before the next ReadInto overwrites it.
//
// On the netpoll path the reader holds a deadline in the past, so the inner
// ReadInto drains the mmap'd ring and then reports os.ErrDeadlineExceeded
// instead of blocking; that is the signal to park on the poller (wave 8.1
// item 6). os.ErrDeadlineExceeded is therefore never returned to the caller
// from this path.
func (r *RingbufReader) ReadInto(rec *ringbuf.Record) error {
	if r.wait == nil {
		return r.reader.ReadInto(rec)
	}

	for {
		err := r.reader.ReadInto(rec)
		if !errors.Is(err, os.ErrDeadlineExceeded) {
			return err
		}

		if werr := r.wait.Wait(); werr != nil {
			if errors.Is(werr, os.ErrClosed) {
				return werr
			}
			// Unsupported fd, or any other wait failure: give the stream back
			// to the blocking path for the rest of the process's life.
			r.downgrade(werr.Error())
			return r.reader.ReadInto(rec)
		}
		if r.onWait != nil {
			r.onWait()
		}
	}
}

// downgrade abandons the netpoll path permanently and restores the blocking
// reader (deadline cleared, poller file closed).
func (r *RingbufReader) downgrade(reason string) {
	if r.wait == nil {
		return
	}
	_ = r.wait.Close()
	r.wait = nil
	r.reader.SetDeadline(time.Time{})
	r.reportFallback(RingbufFallbackWaitError, reason)
}

func (r *RingbufReader) reportFallback(reason, detail string) {
	if r.fellBack {
		return
	}
	r.fellBack = true
	if r.onFallback != nil {
		r.onFallback(reason, detail)
	}
}

// -----------------------------------------------------------------------
// Parse functions
// -----------------------------------------------------------------------

// ParseSyscallEventInto parses raw bytes into an existing SyscallEvent,
// avoiding a heap allocation on the hot path. Prefer this over ParseSyscallEvent
// when the caller can provide a stack-allocated or pooled struct.
// The two fields this parser used to skip — ppid (4 bytes) and parent_comm
// (16 bytes) — sat between uid and the union in the C struct all along. Every
// other struct-event parser here counts them (see ParseNetworkEventInto and
// ParseFileEventInto's minSize); this one did not, so it read comm 4 bytes
// early and nr/ret/args 20 bytes early. Live evidence from the stand
// (2026-08-19): a record whose comm is "sshd" decoded as "\x00\x00\x00\x00sshd"
// — empty for every uid=0 process, which is finding #40's 13 empty-comm
// alerts — while nr decoded from the tail of comm plus the head of
// parent_comm, i.e. never a real syscall number, which is why
// ebpf_guard_events_malformed_total{reason="nr_not_monitored"} counted 3140
// records the in-kernel allowlist had already guaranteed were monitored.
func ParseSyscallEventInto(raw []byte, out *SyscallEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 8 + 8 + 48 // 124 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	offset := 0
	out.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	out.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.PPID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(out.Comm[:], raw[offset:offset+16])
	offset += 16
	copy(out.ParentComm[:], raw[offset:offset+16])
	offset += 16
	out.Nr = int64(binary.LittleEndian.Uint64(raw[offset:])) /* #nosec G115 */
	offset += 8
	out.Ret = int64(binary.LittleEndian.Uint64(raw[offset:])) /* #nosec G115 */
	offset += 8
	for i := 0; i < 6; i++ {
		out.Args[i] = binary.LittleEndian.Uint64(raw[offset:])
		offset += 8
	}
	out.CgroupID = cgroupIDTail(raw)
	return nil
}

// ParseSyscallEvent parses raw bytes into a SyscallEvent.
// Uses manual parsing to match packed C struct layout.
// For the allocation-free hot path, use ParseSyscallEventInto instead.
func ParseSyscallEvent(raw []byte) (*SyscallEvent, error) {
	out := new(SyscallEvent)
	return out, ParseSyscallEventInto(raw, out)
}

// ParseNetworkEventInto parses raw bytes into an existing NetworkEvent,
// avoiding a heap allocation on the hot path.
func ParseNetworkEventInto(raw []byte, out *NetworkEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 16 + 16 + 2 + 2 + 1 + 1 // 98 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	offset := 0
	out.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	out.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.PPID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	out.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(out.Comm[:], raw[offset:offset+16])
	offset += 16
	copy(out.ParentComm[:], raw[offset:offset+16])
	offset += 16
	copy(out.Saddr[:], raw[offset:offset+16])
	offset += 16
	copy(out.Daddr[:], raw[offset:offset+16])
	offset += 16
	out.Sport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	out.Dport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	out.Proto = raw[offset]
	offset++
	out.Family = raw[offset]
	out.CgroupID = cgroupIDTail(raw)
	return nil
}

// ParseNetworkEvent parses raw bytes into a NetworkEvent.
// For the allocation-free hot path, use ParseNetworkEventInto instead.
func ParseNetworkEvent(raw []byte) (*NetworkEvent, error) {
	out := new(NetworkEvent)
	return out, ParseNetworkEventInto(raw, out)
}

// ParseFileaccessEventInto parses raw bytes into an existing FileaccessEvent,
// avoiding a heap allocation on the hot path.
// Wire layout: type(4) ts(8) pid(4) tgid(4) ppid(4) uid(4) comm(16)
// parent_comm(16) filename(256) flags(4) mode(4) op(1) fd_path_truncated(1) = 326 bytes.
func ParseFileaccessEventInto(raw []byte, out *FileaccessEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 256 + 4 + 4 + 1 + 1 // 326 bytes
	if len(raw) < minSize {
		return fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	copy(out.Filename[:], raw[off:off+256])
	off += 256
	out.Flags = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	off += 4
	out.Mode = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Op = raw[off]
	off++
	out.FDTruncated = raw[off]
	out.CgroupID = cgroupIDTail(raw)
	return nil
}

// ParseFileaccessEvent parses raw bytes into a FileaccessEvent.
// For the allocation-free hot path, use ParseFileaccessEventInto instead.
func ParseFileaccessEvent(raw []byte) (*FileaccessEvent, error) {
	out := new(FileaccessEvent)
	return out, ParseFileaccessEventInto(raw, out)
}

// ParsePrivescEventInto parses a raw ring-buffer sample into an existing PrivescRawEvent,
// avoiding a heap allocation on the hot path.
// Wire layout (packed): type(4) ts(8) pid(4) tgid(4) ppid(4) uid(4) comm(16)
//
//	parent_comm(16) nr(8) ret(8) args[0](8)=old_caps args[1](8)=new_caps ...
func ParsePrivescEventInto(raw []byte, out *PrivescRawEvent) error {
	// header: 4+8+4+4+4+4+16+16 = 60 bytes; then syscall union: 8+8+8+8 = 32 bytes minimum
	const minSize = 60 + 8 + 8 + 8 + 8
	if len(raw) < minSize {
		return fmt.Errorf("privesc raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	// skip nr(8) and ret(8)
	off += 16
	out.OldCaps = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.NewCaps = binary.LittleEndian.Uint64(raw[off:])
	return nil
}

// ParsePrivescEvent parses a raw ring-buffer sample into a PrivescRawEvent.
// For the allocation-free hot path, use ParsePrivescEventInto instead.
func ParsePrivescEvent(raw []byte) (*PrivescRawEvent, error) {
	out := new(PrivescRawEvent)
	return out, ParsePrivescEventInto(raw, out)
}

// ParseNetworkCloseEvent parses a raw ring-buffer sample for EVENT_NET_CLOSE.
// The BPF program writes the network tuple in the network union fields and
// then overlays duration_ns into the first 8 bytes of the syscall args
// (args[0]). Because the C struct union shares the same memory, we read
// the network fields from their fixed offsets and duration from the syscall
// args[0] offset.
//
// Wire layout (packed, little-endian):
//
//	[0 ]  type        uint32   (4)
//	[4 ]  timestamp   uint64   (8)
//	[12]  pid         uint32   (4)
//	[16]  tgid        uint32   (4)
//	[20]  ppid        uint32   (4)
//	[24]  uid         uint32   (4)
//	[28]  comm        [16]byte (16)
//	[44]  parent_comm [16]byte (16)
//	[60]  union start — network layout:
//	      saddr [16], daddr [16], sport u16, dport u16, proto u8, family u8
//	[60]  union start — syscall layout (same offset):
//	      nr s64(8), ret s64(8), args[0] u64(8) = duration_ns
//
// We read the network fields first (saddr starts at 60), then read
// duration_ns from offset 60+8+8 = 76 (args[0] in the syscall layout).
// ParseNetworkCloseEventInto parses a raw ring-buffer sample into an existing
// NetworkCloseRawEvent, avoiding a heap allocation on the hot path.
func ParseNetworkCloseEventInto(raw []byte, out *NetworkCloseRawEvent) error {
	const networkUnionOffset = 60
	const durationOffset = networkUnionOffset + 8 + 8 // skip nr + ret
	const minSize = durationOffset + 8
	if len(raw) < minSize {
		return fmt.Errorf("net_close raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	// off == 60 == networkUnionOffset
	copy(out.Saddr[:], raw[off:off+16])
	off += 16
	copy(out.Daddr[:], raw[off:off+16])
	off += 16
	out.Sport = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.Dport = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.Proto = raw[off]
	off++
	out.Family = raw[off]
	// Read duration_ns from syscall union args[0] offset.
	out.DurationNs = binary.LittleEndian.Uint64(raw[durationOffset:])
	return nil
}

// ParseNetworkCloseEvent parses a raw ring-buffer sample for EVENT_NET_CLOSE.
// For the allocation-free hot path, use ParseNetworkCloseEventInto instead.
func ParseNetworkCloseEvent(raw []byte) (*NetworkCloseRawEvent, error) {
	out := new(NetworkCloseRawEvent)
	return out, ParseNetworkCloseEventInto(raw, out)
}

// ParseKmodEventInto parses a raw ring-buffer sample into an existing KmodRawEvent,
// avoiding a heap allocation on the hot path.
func ParseKmodEventInto(raw []byte, out *KmodRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 16 + 16 + 4 + 64 + 1 // 121 bytes
	if len(raw) < minSize {
		return fmt.Errorf("kmod raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.ModName[:], raw[off:off+64])
	off += 64
	out.FromTmpfs = raw[off]
	out.CgroupID = cgroupIDTailAt(raw, KmodEventCgroupIDOffset)
	return nil
}

// ParseKmodEvent parses a raw ring-buffer sample for EVENT_TYPE_KMOD_LOAD.
// For the allocation-free hot path, use ParseKmodEventInto instead.
func ParseKmodEvent(raw []byte) (*KmodRawEvent, error) {
	out := new(KmodRawEvent)
	return out, ParseKmodEventInto(raw, out)
}

// ParseCgroupEscapeEventInto parses a raw ring-buffer sample into an existing
// CgroupEscapeRawEvent, avoiding a heap allocation on the hot path.
func ParseCgroupEscapeEventInto(raw []byte, out *CgroupEscapeRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 16 + 16 + 4 + 8 + 8 // 72 bytes
	if len(raw) < minSize {
		return fmt.Errorf("cgroup_esc raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.InitCgroupID = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.NewCgroupID = binary.LittleEndian.Uint64(raw[off:])
	return nil
}

// ParseCgroupEscapeEvent parses a raw ring-buffer sample for EVENT_TYPE_CGROUP_ESC.
// For the allocation-free hot path, use ParseCgroupEscapeEventInto instead.
func ParseCgroupEscapeEvent(raw []byte) (*CgroupEscapeRawEvent, error) {
	out := new(CgroupEscapeRawEvent)
	return out, ParseCgroupEscapeEventInto(raw, out)
}

// ParseIOUringEventInto parses a raw ring-buffer sample into an existing IOUringRawEvent,
// avoiding a heap allocation on the hot path.
func ParseIOUringEventInto(raw []byte, out *IOUringRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 1 + 4 + 4 + 4 // 73 bytes
	if len(raw) < minSize {
		return fmt.Errorf("iouring raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Op = raw[off]
	off++
	out.Flags = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Fd = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	off += 4
	out.ToSubmit = binary.LittleEndian.Uint32(raw[off:])
	return nil
}

// ParseIOUringEvent parses a raw ring-buffer sample for EVENT_TYPE_IO_URING.
// For the allocation-free hot path, use ParseIOUringEventInto instead.
func ParseIOUringEvent(raw []byte) (*IOUringRawEvent, error) {
	out := new(IOUringRawEvent)
	return out, ParseIOUringEventInto(raw, out)
}

// ParseBpfMonitorEventInto parses a raw ring-buffer sample into an existing
// BpfMonitorRawEvent, avoiding a heap allocation on the hot path.
func ParseBpfMonitorEventInto(raw []byte, out *BpfMonitorRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 4 + 4 + 4 // 72 bytes
	if len(raw) < minSize {
		return fmt.Errorf("bpf_monitor raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Cmd = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.ProgType = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Ret = int32(binary.LittleEndian.Uint32(raw[off:])) /* #nosec G115 */
	return nil
}

// ParseBpfMonitorEvent parses a raw ring-buffer sample for EVENT_TYPE_BPF_PROGRAM.
// For the allocation-free hot path, use ParseBpfMonitorEventInto instead.
func ParseBpfMonitorEvent(raw []byte) (*BpfMonitorRawEvent, error) {
	out := new(BpfMonitorRawEvent)
	return out, ParseBpfMonitorEventInto(raw, out)
}

// ParseTlsClientHelloEventInto parses a raw ring-buffer sample into an existing
// TlsClientHelloRawEvent, avoiding a heap allocation on the hot path.
func ParseTlsClientHelloEventInto(raw []byte, out *TlsClientHelloRawEvent) error {
	const minSize = 4 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 2 + 2 + 4 + 1 // 69 bytes min
	if len(raw) < minSize {
		return fmt.Errorf("tls_clienthello raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}
	off := 0
	out.Type = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.Timestamp = binary.LittleEndian.Uint64(raw[off:])
	off += 8
	out.PID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.TGID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.PPID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	out.UID = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	copy(out.Comm[:], raw[off:off+16])
	off += 16
	copy(out.ParentComm[:], raw[off:off+16])
	off += 16
	out.Dport = binary.BigEndian.Uint16(raw[off:])
	off += 2 // network byte order
	out.CapturedLen = binary.LittleEndian.Uint16(raw[off:])
	off += 2
	out.OriginalLen = binary.LittleEndian.Uint32(raw[off:])
	off += 4
	if out.CapturedLen > 512 {
		out.CapturedLen = 512
	}
	copy(out.Data[:], raw[off:off+int(out.CapturedLen)])
	out.CgroupID = cgroupIDTailAt(raw, TLSClientHelloCgroupIDOffset)
	return nil
}

// ParseTlsClientHelloEvent parses a raw ring-buffer sample for a ClientHello event.
// For the allocation-free hot path, use ParseTlsClientHelloEventInto instead.
func ParseTlsClientHelloEvent(raw []byte) (*TlsClientHelloRawEvent, error) {
	out := new(TlsClientHelloRawEvent)
	return out, ParseTlsClientHelloEventInto(raw, out)
}

// -----------------------------------------------------------------------
// ToTypesEvent converters
// -----------------------------------------------------------------------

// ToTypesEvent converts a SyscallEvent to types.Event.
func (e *SyscallEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventSyscall,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		CgroupID:   e.CgroupID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Syscall: &types.SyscallEvent{
			Nr:   e.Nr,
			Ret:  e.Ret,
			Args: e.Args,
		},
	}
}

// ToTypesEvent converts a NetworkEvent to types.Event.
func (e *NetworkEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventTCPConnect,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		CgroupID:   e.CgroupID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Network: &types.NetworkEvent{
			Saddr:  e.Saddr,
			Daddr:  e.Daddr,
			Sport:  e.Sport,
			Dport:  e.Dport,
			Proto:  e.Proto,
			Family: types.AddressFamily(e.Family),
		},
	}
}

// ToTypesEvent converts a FileaccessEvent to types.Event.
// FDPath is populated for all ops: for open events it mirrors Filename; for
// read/write events the BPF program resolved it via the fd→path map.
func (e *FileaccessEvent) ToTypesEvent() types.Event {
	fdPath := nullTerminatedString(e.Filename[:])
	return types.Event{
		Type:       types.EventFileAccess,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		CgroupID:   e.CgroupID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		File: &types.FileEvent{
			Filename:        e.Filename,
			Flags:           e.Flags,
			Mode:            e.Mode,
			Op:              e.Op,
			FDPath:          fdPath,
			FDPathTruncated: e.FDTruncated != 0,
		},
	}
}

// ToTypesEvent converts a PrivescRawEvent to types.Event.
func (e *PrivescRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventPrivesc,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Privesc: &types.PrivescEvent{
			OldCaps: e.OldCaps,
			NewCaps: e.NewCaps,
		},
	}
}

// ToTypesEvent converts a NetworkCloseRawEvent to types.Event.
func (e *NetworkCloseRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventNetClose,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		NetClose: &types.NetworkCloseEvent{
			Saddr:    e.Saddr,
			Daddr:    e.Daddr,
			Sport:    e.Sport,
			Dport:    e.Dport,
			Family:   types.AddressFamily(e.Family),
			Duration: time.Duration(e.DurationNs),
		},
	}
}

// ToTypesEvent converts a KmodRawEvent to types.Event.
func (e *KmodRawEvent) ToTypesEvent() types.Event {
	// Trim null bytes from mod name.
	name := e.ModName[:]
	for i, b := range name {
		if b == 0 {
			name = e.ModName[:i]
			break
		}
	}
	return types.Event{
		Type:       types.EventKmodLoad,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		UID:        e.UID,
		PPID:       e.PPID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		Kmod: &types.KmodEvent{
			ModName:   string(name),
			FromTmpfs: e.FromTmpfs != 0,
		},
		// Wave 6.6 revision item 8: in-kernel cgroup id, 0 if the record came
		// from a BPF object built before it. A module load is exactly the
		// short-lived event whose pid is gone before /proc/<pid>/cgroup is
		// read, so this is the field that makes its container recoverable.
		CgroupID: e.CgroupID,
	}
}

// ToTypesEvent converts a CgroupEscapeRawEvent to types.Event.
//
// 5.9.1f (пустой comm на cgroup-escape пути, а НЕ находка №40): bpf/cgroup.bpf.c
// читает comm через BPF_CORE_READ(leader, comm) — чужой task, не текущий, без
// синхронизации — тот же класс torn-read, что 5.9h разобрала для parent_comm,
// только здесь задет leaf-поле Comm самого события (то, что попадает в
// Alert.Comm). cgroup_attach_task срабатывает у самого рождения процесса
// (clone3(CLONE_INTO_CGROUP)), гоняясь с инициализацией comm той же задачи,
// поэтому Comm может прийти полностью пустым, не просто искажённым. Это
// реальный, самостоятельный дефект этого пути — но 5.9.2c (находка №40,
// plan.md) установила прогоном, что 13 пустых comm на замере №2.9.1 (11
// anomaly_detection + 2 mitre_arp_spoof_raw_socket) были все на syscall-пути,
// который CgroupEscapeRawEvent никогда не затрагивает (ноль cgroup-escape
// алертов в том прогоне вообще); эта заплатка их не объясняет и не закрывает.
// BPF-фикс требует make generate (clang+linux-headers), недоступного в этой
// сессии (macOS) — см. TODO у BPF_CORE_READ(leader, comm) в
// bpf/cgroup.bpf.c. Здесь — userspace-заплатка: если ядро вернуло пустой
// Comm, подтягиваем его из /proc/<pid>/comm; best-effort — если /proc
// недоступен (не-Linux, процесс уже завершился), Comm остаётся пустым, как
// раньше, без ошибки.
func (e *CgroupEscapeRawEvent) ToTypesEvent() types.Event {
	comm := e.Comm
	if IsEmptyComm(comm) {
		if resolved, ok := readProcComm(e.PID); ok {
			comm = resolved
		}
	}
	return types.Event{
		Type:       types.EventCgroupEsc,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		UID:        e.UID,
		PPID:       e.PPID,
		Comm:       comm,
		ParentComm: e.ParentComm,
		CgroupEsc: &types.CgroupEscapeEvent{
			InitCgroupID: e.InitCgroupID,
			NewCgroupID:  e.NewCgroupID,
		},
		// Wave 6.6 revision item 8, finding №487: this event carries NO
		// bpf_get_current_cgroup_id() and must not. Its hook is
		// cgroup_attach_task, where the current task is the one PERFORMING the
		// attach (a shell writing cgroup.procs), not the task being migrated —
		// the current cgroup there would name the attacker's container, not the
		// victim's. NewCgroupID is the migrating leader's destination cgroup,
		// read from dst_cgrp->kn->id in the same units, so the pid->pod
		// recovery is fed from IT.
		CgroupID: e.NewCgroupID,
	}
}

// IsEmptyComm reports whether comm is a torn/unfilled read (leading NUL)
// rather than a legitimately short name padded with NULs.
func IsEmptyComm(comm [16]byte) bool {
	return comm[0] == 0
}

// readProcComm resolves a process's command name via /proc/<pid>/comm,
// truncated to the kernel's 16-byte TASK_COMM_LEN. ok=false when /proc is
// unavailable or the process has already exited — callers must leave the
// original (possibly empty) Comm untouched in that case.
func readProcComm(pid uint32) (comm [16]byte, ok bool) {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/comm", pid))
	if err != nil {
		return comm, false
	}
	name := strings.TrimSuffix(string(data), "\n")
	if name == "" {
		return comm, false
	}
	copy(comm[:], name)
	return comm, true
}

// ToTypesEvent converts an IOUringRawEvent to types.Event.
func (e *IOUringRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventIOUring,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		IOUring: &types.IOUringEvent{
			Op:       e.Op,
			Flags:    e.Flags,
			Fd:       e.Fd,
			ToSubmit: e.ToSubmit,
		},
	}
}

// ToTypesEvent converts a BpfMonitorRawEvent to types.Event.
func (e *BpfMonitorRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventBPFProgram,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		BPFProgram: &types.BPFProgramEvent{
			Cmd:      e.Cmd,
			ProgType: e.ProgType,
			Ret:      e.Ret,
		},
	}
}

// ToTypesEvent converts a TlsClientHelloRawEvent to types.Event.
// The JA3/JA4/JA3S fields are left empty here; they are computed by the
// collector after parsing to avoid circular imports from the ja3 package.
func (e *TlsClientHelloRawEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:       types.EventTLS,
		Timestamp:  types.KtimeToEpoch(e.Timestamp),
		PID:        e.PID,
		TGID:       e.TGID,
		PPID:       e.PPID,
		UID:        e.UID,
		Comm:       e.Comm,
		ParentComm: e.ParentComm,
		TLS: &types.TLSEvent{
			DataLen: e.OriginalLen,
		},
		// Wave 6.6 revision item 8: in-kernel cgroup id, 0 if the record came
		// from a BPF object built before it.
		CgroupID: e.CgroupID,
	}
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

// nullTerminatedString converts a byte slice to a Go string, stopping at the
// first NUL byte. Used to convert fixed-size C string arrays.
func nullTerminatedString(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}
