// Package bpf — stub types for the Fileaccess BPF program.
//
// The real FileaccessObjects / LoadFileaccessObjects are generated by `make generate`
// (bpf2go compiles bpf/fileaccess.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// fileaccess_bpfel.go / fileaccess_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// FileaccessMaps holds the BPF maps exported by bpf/fileaccess.bpf.c.
type FileaccessMaps struct {
	AgentPidMap            *ebpf.Map `ebpf:"agent_pid_map"`
	CommFilterMap          *ebpf.Map `ebpf:"comm_filter_map"`
	Events                 *ebpf.Map `ebpf:"events"`
	KernelFilterConfig     *ebpf.Map `ebpf:"kernel_filter_config"`
	PathFilterDropCounters *ebpf.Map `ebpf:"path_filter_drop_counters"`
	PathFilterMap          *ebpf.Map `ebpf:"path_filter_map"`
	SamplingConfig         *ebpf.Map `ebpf:"sampling_config"`
	SyscallFilterMap       *ebpf.Map `ebpf:"syscall_filter_map"`
}

// FileaccessPrograms holds the BPF programs exported by bpf/fileaccess.bpf.c.
type FileaccessPrograms struct {
	TraceClose       *ebpf.Program `ebpf:"trace_close"`
	TraceOpen        *ebpf.Program `ebpf:"trace_open"`
	TraceOpenExit    *ebpf.Program `ebpf:"trace_open_exit"`
	TraceOpenat2Exit *ebpf.Program `ebpf:"trace_openat2_exit"`
	TraceRead        *ebpf.Program `ebpf:"trace_read"`
	TraceWrite       *ebpf.Program `ebpf:"trace_write"`
}

// FileaccessObjects contains all BPF objects after loading bpf/fileaccess.bpf.c.
type FileaccessObjects struct {
	FileaccessPrograms
	FileaccessMaps
}

// Close releases all BPF resources held by the objects.
func (o *FileaccessObjects) Close() error {
	var errs []error
	if o.TraceClose != nil {
		errs = append(errs, o.TraceClose.Close())
	}
	if o.TraceOpen != nil {
		errs = append(errs, o.TraceOpen.Close())
	}
	if o.TraceOpenExit != nil {
		errs = append(errs, o.TraceOpenExit.Close())
	}
	if o.TraceOpenat2Exit != nil {
		errs = append(errs, o.TraceOpenat2Exit.Close())
	}
	if o.TraceRead != nil {
		errs = append(errs, o.TraceRead.Close())
	}
	if o.TraceWrite != nil {
		errs = append(errs, o.TraceWrite.Close())
	}
	if o.AgentPidMap != nil {
		errs = append(errs, o.AgentPidMap.Close())
	}
	if o.CommFilterMap != nil {
		errs = append(errs, o.CommFilterMap.Close())
	}
	if o.Events != nil {
		errs = append(errs, o.Events.Close())
	}
	if o.KernelFilterConfig != nil {
		errs = append(errs, o.KernelFilterConfig.Close())
	}
	if o.PathFilterDropCounters != nil {
		errs = append(errs, o.PathFilterDropCounters.Close())
	}
	if o.PathFilterMap != nil {
		errs = append(errs, o.PathFilterMap.Close())
	}
	if o.SamplingConfig != nil {
		errs = append(errs, o.SamplingConfig.Close())
	}
	if o.SyscallFilterMap != nil {
		errs = append(errs, o.SyscallFilterMap.Close())
	}
	return errors.Join(errs...)
}

// LoadFileaccessObjects loads the Fileaccess BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/fileaccess.bpf.c.
func LoadFileaccessObjects(_ *FileaccessObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Fileaccess program not available (run make generate to compile BPF programs)")
}
