// Package bpf — stub types for the HiddenProcess BPF program.
//
// The real HiddenProcessObjects / LoadHiddenProcessObjects are generated by `make generate`
// (bpf2go compiles bpf/hidden_process.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// hiddenprocess_bpfel.go / hiddenprocess_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// HiddenProcessMaps holds the BPF maps exported by bpf/hidden_process.bpf.c.
type HiddenProcessMaps struct {
	// no maps referenced by userspace for this program
}

// HiddenProcessPrograms holds the BPF programs exported by bpf/hidden_process.bpf.c.
type HiddenProcessPrograms struct {
	DumpTask *ebpf.Program `ebpf:"dump_task"`
}

// HiddenProcessObjects contains all BPF objects after loading bpf/hidden_process.bpf.c.
type HiddenProcessObjects struct {
	HiddenProcessPrograms
	HiddenProcessMaps
}

// Close releases all BPF resources held by the objects.
func (o *HiddenProcessObjects) Close() error {
	var errs []error
	if o.DumpTask != nil {
		errs = append(errs, o.DumpTask.Close())
	}
	return errors.Join(errs...)
}

// LoadHiddenProcessObjects loads the HiddenProcess BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/hidden_process.bpf.c.
func LoadHiddenProcessObjects(_ *HiddenProcessObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: HiddenProcess program not available (run make generate to compile BPF programs)")
}
