// Package bpf — stub types for the plaintext HTTP uprobe BPF program.
//
// The real HttpUprobeObjects / LoadHttpUprobeObjects / LoadHttpUprobe are
// generated by `make generate` (bpf2go compiles bpf/http_uprobe.bpf.c and
// emits Go bindings). This stub provides the same exported API so packages
// that import internal/bpf can be compiled and tested without a
// clang/kernel-headers toolchain — notably on macOS, where clang has no BPF
// backend at all.
//
// In a production build, run `make generate` first; the generated
// httpuprobe_bpfel.go / httpuprobe_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// HttpUprobeMaps holds the BPF maps exported by bpf/http_uprobe.bpf.c.
type HttpUprobeMaps struct {
	HttpEvents       *ebpf.Map `ebpf:"http_events"`
	HttpReadContexts *ebpf.Map `ebpf:"http_read_contexts"`
}

// HttpUprobePrograms holds the BPF programs exported by bpf/http_uprobe.bpf.c.
type HttpUprobePrograms struct {
	TraceReadEntry *ebpf.Program `ebpf:"trace_read_entry"`
	TraceReadRet   *ebpf.Program `ebpf:"trace_read_ret"`
	TraceRecvEntry *ebpf.Program `ebpf:"trace_recv_entry"`
	TraceRecvRet   *ebpf.Program `ebpf:"trace_recv_ret"`
}

// HttpUprobeObjects contains all BPF objects after loading bpf/http_uprobe.bpf.c.
type HttpUprobeObjects struct {
	HttpUprobePrograms
	HttpUprobeMaps
}

// Close releases all BPF resources held by the objects.
func (o *HttpUprobeObjects) Close() error {
	var errs []error
	if o.TraceReadEntry != nil {
		errs = append(errs, o.TraceReadEntry.Close())
	}
	if o.TraceReadRet != nil {
		errs = append(errs, o.TraceReadRet.Close())
	}
	if o.TraceRecvEntry != nil {
		errs = append(errs, o.TraceRecvEntry.Close())
	}
	if o.TraceRecvRet != nil {
		errs = append(errs, o.TraceRecvRet.Close())
	}
	if o.HttpEvents != nil {
		errs = append(errs, o.HttpEvents.Close())
	}
	if o.HttpReadContexts != nil {
		errs = append(errs, o.HttpReadContexts.Close())
	}
	return errors.Join(errs...)
}

// LoadHttpUprobe returns the embedded CollectionSpec for HttpUprobe.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/http_uprobe.bpf.c.
func LoadHttpUprobe() (*ebpf.CollectionSpec, error) {
	return nil, fmt.Errorf("bpf: HttpUprobe program not available (run make generate to compile BPF programs)")
}

// LoadHttpUprobeObjects loads the HttpUprobe BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/http_uprobe.bpf.c.
func LoadHttpUprobeObjects(_ *HttpUprobeObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: HttpUprobe program not available (run make generate to compile BPF programs)")
}
