// Package bpf — stub types for the Iouring BPF program.
//
// The real IouringObjects / LoadIouringObjects are generated by `make generate`
// (bpf2go compiles bpf/iouring.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// iouring_bpfel.go / iouring_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// IouringMaps holds the BPF maps exported by bpf/iouring.bpf.c.
type IouringMaps struct {
	IouringEvents *ebpf.Map `ebpf:"iouring_events"`
}

// IouringPrograms holds the BPF programs exported by bpf/iouring.bpf.c.
type IouringPrograms struct {
	TraceIoUringEnter *ebpf.Program `ebpf:"trace_io_uring_enter"`
	TraceIoUringSetup *ebpf.Program `ebpf:"trace_io_uring_setup"`
}

// IouringObjects contains all BPF objects after loading bpf/iouring.bpf.c.
type IouringObjects struct {
	IouringPrograms
	IouringMaps
}

// Close releases all BPF resources held by the objects.
func (o *IouringObjects) Close() error {
	var errs []error
	if o.TraceIoUringEnter != nil {
		errs = append(errs, o.TraceIoUringEnter.Close())
	}
	if o.TraceIoUringSetup != nil {
		errs = append(errs, o.TraceIoUringSetup.Close())
	}
	if o.IouringEvents != nil {
		errs = append(errs, o.IouringEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadIouringObjects loads the Iouring BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/iouring.bpf.c.
func LoadIouringObjects(_ *IouringObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Iouring program not available (run make generate to compile BPF programs)")
}
