// Package bpf — stub types for the Kmod BPF program.
//
// The real KmodObjects / LoadKmodObjects are generated by `make generate`
// (bpf2go compiles bpf/lsm.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// kmod_bpfel.go / kmod_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// KmodMaps holds the BPF maps exported by bpf/lsm.bpf.c.
type KmodMaps struct {
	LsmEvents *ebpf.Map `ebpf:"lsm_events"`
}

// KmodPrograms holds the BPF programs exported by bpf/lsm.bpf.c.
type KmodPrograms struct {
	LsmKernelModuleRequest *ebpf.Program `ebpf:"lsm_kernel_module_request"`
	LsmKernelReadFile      *ebpf.Program `ebpf:"lsm_kernel_read_file"`
	TraceExecRecordCgroup  *ebpf.Program `ebpf:"trace_exec_record_cgroup"`
}

// KmodObjects contains all BPF objects after loading bpf/lsm.bpf.c.
type KmodObjects struct {
	KmodPrograms
	KmodMaps
}

// Close releases all BPF resources held by the objects.
func (o *KmodObjects) Close() error {
	var errs []error
	if o.LsmKernelModuleRequest != nil {
		errs = append(errs, o.LsmKernelModuleRequest.Close())
	}
	if o.LsmKernelReadFile != nil {
		errs = append(errs, o.LsmKernelReadFile.Close())
	}
	if o.TraceExecRecordCgroup != nil {
		errs = append(errs, o.TraceExecRecordCgroup.Close())
	}
	if o.LsmEvents != nil {
		errs = append(errs, o.LsmEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadKmodObjects loads the Kmod BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/lsm.bpf.c.
func LoadKmodObjects(_ *KmodObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Kmod program not available (run make generate to compile BPF programs)")
}
