// Package bpf — stub types for the Network BPF program.
//
// The real NetworkObjects / LoadNetworkObjects are generated by `make generate`
// (bpf2go compiles bpf/network.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// network_bpfel.go / network_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// NetworkMaps holds the BPF maps exported by bpf/network.bpf.c.
type NetworkMaps struct {
	Events                   *ebpf.Map `ebpf:"events"`
	MapFullCounters          *ebpf.Map `ebpf:"map_full_counters"`
	ObserverExcludedCounters *ebpf.Map `ebpf:"observer_excluded_counters"`
	ObserverRootPid          *ebpf.Map `ebpf:"observer_root_pid"`
	ObserverTreeCache        *ebpf.Map `ebpf:"observer_tree_cache"`
	SamplingConfig           *ebpf.Map `ebpf:"sampling_config"`
}

// NetworkPrograms holds the BPF programs exported by bpf/network.bpf.c.
type NetworkPrograms struct {
	TraceTcpClose   *ebpf.Program `ebpf:"trace_tcp_close"`
	TraceTcpConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
}

// NetworkObjects contains all BPF objects after loading bpf/network.bpf.c.
type NetworkObjects struct {
	NetworkPrograms
	NetworkMaps
}

// Close releases all BPF resources held by the objects.
func (o *NetworkObjects) Close() error {
	var errs []error
	if o.TraceTcpClose != nil {
		errs = append(errs, o.TraceTcpClose.Close())
	}
	if o.TraceTcpConnect != nil {
		errs = append(errs, o.TraceTcpConnect.Close())
	}
	if o.Events != nil {
		errs = append(errs, o.Events.Close())
	}
	if o.MapFullCounters != nil {
		errs = append(errs, o.MapFullCounters.Close())
	}
	if o.SamplingConfig != nil {
		errs = append(errs, o.SamplingConfig.Close())
	}
	if o.ObserverExcludedCounters != nil {
		errs = append(errs, o.ObserverExcludedCounters.Close())
	}
	if o.ObserverRootPid != nil {
		errs = append(errs, o.ObserverRootPid.Close())
	}
	if o.ObserverTreeCache != nil {
		errs = append(errs, o.ObserverTreeCache.Close())
	}
	return errors.Join(errs...)
}

// LoadNetworkObjects loads the Network BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/network.bpf.c.
func LoadNetworkObjects(_ *NetworkObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Network program not available (run make generate to compile BPF programs)")
}
