// Package bpf — stub types for the Privesc BPF program.
//
// The real PrivescObjects / LoadPrivescObjects are generated by `make generate`
// (bpf2go compiles bpf/privesc.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// privesc_bpfel.go / privesc_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// PrivescMaps holds the BPF maps exported by bpf/privesc.bpf.c.
type PrivescMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

// PrivescPrograms holds the BPF programs exported by bpf/privesc.bpf.c.
type PrivescPrograms struct {
	TraceCapset      *ebpf.Program `ebpf:"trace_capset"`
	TraceCommitCreds *ebpf.Program `ebpf:"trace_commit_creds"`
}

// PrivescObjects contains all BPF objects after loading bpf/privesc.bpf.c.
type PrivescObjects struct {
	PrivescPrograms
	PrivescMaps
}

// Close releases all BPF resources held by the objects.
func (o *PrivescObjects) Close() error {
	var errs []error
	if o.TraceCapset != nil {
		errs = append(errs, o.TraceCapset.Close())
	}
	if o.TraceCommitCreds != nil {
		errs = append(errs, o.TraceCommitCreds.Close())
	}
	if o.Events != nil {
		errs = append(errs, o.Events.Close())
	}
	return errors.Join(errs...)
}

// LoadPrivescObjects loads the Privesc BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/privesc.bpf.c.
func LoadPrivescObjects(_ *PrivescObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Privesc program not available (run make generate to compile BPF programs)")
}
