// Code generated by bpf2go; DO NOT EDIT.
// This is a stub - run 'make generate' with clang installed to regenerate.

package bpf

import (
	"encoding/binary"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/ebpf-guard/ebpf-guard/pkg/types"
)

// SyscallEvent matches the C struct event from common.h
// Layout matches packed C struct exactly
type SyscallEvent struct {
	Type      uint32
	Timestamp uint64
	PID       uint32
	TGID      uint32
	UID       uint32
	Comm      [16]byte
	// Union payload - syscall specific
	Nr   int64
	Ret  int64
	Args [6]uint64
}

// NetworkEvent matches the C struct event for network events
type NetworkEvent struct {
	Type      uint32
	Timestamp uint64
	PID       uint32
	TGID      uint32
	UID       uint32
	Comm      [16]byte
	// Union payload - network specific
	Saddr  [16]byte
	Daddr  [16]byte
	Sport  uint16
	Dport  uint16
	Proto  uint8
	Family uint8 // Address family: 2=AF_INET, 10=AF_INET6
	// No padding - C struct is packed
}

// FileaccessEvent matches the C struct event for file events
type FileaccessEvent struct {
	Type      uint32
	Timestamp uint64
	PID       uint32
	TGID      uint32
	UID       uint32
	Comm      [16]byte
	// Union payload - file specific
	Filename [256]byte
	Flags    int32
	Mode     uint32
	Op       uint8
	// No padding - C struct is packed
}

// SyscallObjects contains all eBPF objects for syscall collection.
type SyscallObjects struct {
	TraceSysEnter *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit  *ebpf.Program `ebpf:"trace_sys_exit"`
	Events        *ebpf.Map     `ebpf:"events"`
	SyscallArgs   *ebpf.Map     `ebpf:"syscall_args"`
}

// NetworkObjects contains all eBPF objects for network collection.
type NetworkObjects struct {
	TraceTCPConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
	Events          *ebpf.Map     `ebpf:"events"`
}

// FileaccessObjects contains all eBPF objects for file access collection.
type FileaccessObjects struct {
	TraceOpen  *ebpf.Program `ebpf:"trace_open"`
	TraceRead  *ebpf.Program `ebpf:"trace_read"`
	TraceWrite *ebpf.Program `ebpf:"trace_write"`
	Events     *ebpf.Map     `ebpf:"events"`
}

// LoadSyscallObjects loads syscall eBPF objects from embedded bytecode.
func LoadSyscallObjects(obj *SyscallObjects, opts *ebpf.CollectionOptions) error {
	// Stub implementation - bpf2go would generate the real loading code
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// LoadNetworkObjects loads network eBPF objects from embedded bytecode.
func LoadNetworkObjects(obj *NetworkObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// LoadFileaccessObjects loads fileaccess eBPF objects from embedded bytecode.
func LoadFileaccessObjects(obj *FileaccessObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// Close closes all eBPF objects.
func (o *SyscallObjects) Close() error {
	if o.TraceSysEnter != nil {
		o.TraceSysEnter.Close()
	}
	if o.TraceSysExit != nil {
		o.TraceSysExit.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
	if o.SyscallArgs != nil {
		o.SyscallArgs.Close()
	}
	return nil
}

// Close closes all eBPF objects.
func (o *NetworkObjects) Close() error {
	if o.TraceTCPConnect != nil {
		o.TraceTCPConnect.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
	return nil
}

// Close closes all eBPF objects.
func (o *FileaccessObjects) Close() error {
	if o.TraceOpen != nil {
		o.TraceOpen.Close()
	}
	if o.TraceRead != nil {
		o.TraceRead.Close()
	}
	if o.TraceWrite != nil {
		o.TraceWrite.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
	return nil
}

// RingbufReader wraps ringbuf.Reader for type-safe event reading.
type RingbufReader struct {
	reader *ringbuf.Reader
}

// NewRingbufReader creates a new ring buffer reader from an eBPF map.
func NewRingbufReader(events *ebpf.Map) (*RingbufReader, error) {
	reader, err := ringbuf.NewReader(events)
	if err != nil {
		return nil, err
	}
	return &RingbufReader{reader: reader}, nil
}

// Close closes the ring buffer reader.
func (r *RingbufReader) Close() error {
	if r.reader != nil {
		return r.reader.Close()
	}
	return nil
}

// Read reads the next event from the ring buffer.
func (r *RingbufReader) Read() (ringbuf.Record, error) {
	return r.reader.Read()
}

// ParseSyscallEvent parses raw bytes into a SyscallEvent.
// Uses manual parsing to match packed C struct layout.
func ParseSyscallEvent(raw []byte) (*SyscallEvent, error) {
	const minSize = 4 + 8 + 4 + 4 + 4 + 16 + 8 + 8 + 48 // 104 bytes
	if len(raw) < minSize {
		return nil, fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}

	evt := &SyscallEvent{}
	offset := 0

	evt.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	evt.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(evt.Comm[:], raw[offset:offset+16])
	offset += 16
	evt.Nr = int64(binary.LittleEndian.Uint64(raw[offset:]))
	offset += 8
	evt.Ret = int64(binary.LittleEndian.Uint64(raw[offset:]))
	offset += 8
	for i := 0; i < 6; i++ {
		evt.Args[i] = binary.LittleEndian.Uint64(raw[offset:])
		offset += 8
	}

	return evt, nil
}

// ParseNetworkEvent parses raw bytes into a NetworkEvent.
func ParseNetworkEvent(raw []byte) (*NetworkEvent, error) {
	const minSize = 4 + 8 + 4 + 4 + 4 + 16 + 16 + 16 + 2 + 2 + 1 + 1 // 78 bytes
	if len(raw) < minSize {
		return nil, fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}

	evt := &NetworkEvent{}
	offset := 0

	evt.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	evt.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(evt.Comm[:], raw[offset:offset+16])
	offset += 16
	copy(evt.Saddr[:], raw[offset:offset+16])
	offset += 16
	copy(evt.Daddr[:], raw[offset:offset+16])
	offset += 16
	evt.Sport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	evt.Dport = binary.LittleEndian.Uint16(raw[offset:])
	offset += 2
	evt.Proto = raw[offset]
	offset += 1
	evt.Family = raw[offset]

	return evt, nil
}

// ParseFileaccessEvent parses raw bytes into a FileaccessEvent.
func ParseFileaccessEvent(raw []byte) (*FileaccessEvent, error) {
	const minSize = 4 + 8 + 4 + 4 + 4 + 16 + 256 + 4 + 4 + 1 // 305 bytes
	if len(raw) < minSize {
		return nil, fmt.Errorf("raw sample too small: %d bytes (need %d)", len(raw), minSize)
	}

	evt := &FileaccessEvent{}
	offset := 0

	evt.Type = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.Timestamp = binary.LittleEndian.Uint64(raw[offset:])
	offset += 8
	evt.PID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.TGID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.UID = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	copy(evt.Comm[:], raw[offset:offset+16])
	offset += 16
	copy(evt.Filename[:], raw[offset:offset+256])
	offset += 256
	evt.Flags = int32(binary.LittleEndian.Uint32(raw[offset:]))
	offset += 4
	evt.Mode = binary.LittleEndian.Uint32(raw[offset:])
	offset += 4
	evt.Op = raw[offset]

	return evt, nil
}

// ToTypesEvent converts a SyscallEvent to types.Event.
func (e *SyscallEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:      types.EventSyscall,
		Timestamp: e.Timestamp,
		PID:       e.PID,
		TGID:      e.TGID,
		UID:       e.UID,
		Comm:      e.Comm,
		Syscall: &types.SyscallEvent{
			Nr:   e.Nr,
			Ret:  e.Ret,
			Args: e.Args,
		},
	}
}

// ToTypesEvent converts a NetworkEvent to types.Event.
func (e *NetworkEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:      types.EventTCPConnect,
		Timestamp: e.Timestamp,
		PID:       e.PID,
		TGID:      e.TGID,
		UID:       e.UID,
		Comm:      e.Comm,
		Network: &types.NetworkEvent{
			Saddr:  e.Saddr,
			Daddr:  e.Daddr,
			Sport:  e.Sport,
			Dport:  e.Dport,
			Proto:  e.Proto,
			Family: types.AddressFamily(e.Family),
		},
	}
}

// ToTypesEvent converts a FileaccessEvent to types.Event.
func (e *FileaccessEvent) ToTypesEvent() types.Event {
	return types.Event{
		Type:      types.EventFileAccess,
		Timestamp: e.Timestamp,
		PID:       e.PID,
		TGID:      e.TGID,
		UID:       e.UID,
		Comm:      e.Comm,
		File: &types.FileEvent{
			Filename: e.Filename,
			Flags:    e.Flags,
			Mode:     e.Mode,
			Op:       e.Op,
		},
	}
}
