// Package bpf — stub types for the Syscall BPF program.
//
// The real SyscallObjects / LoadSyscallObjects are generated by `make generate`
// (bpf2go compiles bpf/syscall.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// syscall_bpfel.go / syscall_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// SyscallMaps holds the BPF maps exported by bpf/syscall.bpf.c.
type SyscallMaps struct {
	AgentPidMap              *ebpf.Map `ebpf:"agent_pid_map"`
	CommFilterMap            *ebpf.Map `ebpf:"comm_filter_map"`
	Events                   *ebpf.Map `ebpf:"events"`
	KernelFilterConfig       *ebpf.Map `ebpf:"kernel_filter_config"`
	MapFullCounters          *ebpf.Map `ebpf:"map_full_counters"`
	ObserverExcludedCounters *ebpf.Map `ebpf:"observer_excluded_counters"`
	ObserverRootPid          *ebpf.Map `ebpf:"observer_root_pid"`
	ObserverTreeCache        *ebpf.Map `ebpf:"observer_tree_cache"`
	SamplingConfig           *ebpf.Map `ebpf:"sampling_config"`
	SyscallFilterMap         *ebpf.Map `ebpf:"syscall_filter_map"`
}

// SyscallPrograms holds the BPF programs exported by bpf/syscall.bpf.c.
type SyscallPrograms struct {
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSysEnter         *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit          *ebpf.Program `ebpf:"trace_sys_exit"`
}

// SyscallObjects contains all BPF objects after loading bpf/syscall.bpf.c.
type SyscallObjects struct {
	SyscallPrograms
	SyscallMaps
}

// Close releases all BPF resources held by the objects.
func (o *SyscallObjects) Close() error {
	var errs []error
	if o.TraceSchedProcessExec != nil {
		errs = append(errs, o.TraceSchedProcessExec.Close())
	}
	if o.TraceSysEnter != nil {
		errs = append(errs, o.TraceSysEnter.Close())
	}
	if o.TraceSysExit != nil {
		errs = append(errs, o.TraceSysExit.Close())
	}
	if o.AgentPidMap != nil {
		errs = append(errs, o.AgentPidMap.Close())
	}
	if o.CommFilterMap != nil {
		errs = append(errs, o.CommFilterMap.Close())
	}
	if o.Events != nil {
		errs = append(errs, o.Events.Close())
	}
	if o.KernelFilterConfig != nil {
		errs = append(errs, o.KernelFilterConfig.Close())
	}
	if o.MapFullCounters != nil {
		errs = append(errs, o.MapFullCounters.Close())
	}
	if o.SamplingConfig != nil {
		errs = append(errs, o.SamplingConfig.Close())
	}
	if o.SyscallFilterMap != nil {
		errs = append(errs, o.SyscallFilterMap.Close())
	}
	if o.ObserverExcludedCounters != nil {
		errs = append(errs, o.ObserverExcludedCounters.Close())
	}
	if o.ObserverRootPid != nil {
		errs = append(errs, o.ObserverRootPid.Close())
	}
	if o.ObserverTreeCache != nil {
		errs = append(errs, o.ObserverTreeCache.Close())
	}
	return errors.Join(errs...)
}

// LoadSyscallObjects loads the Syscall BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/syscall.bpf.c.
func LoadSyscallObjects(_ *SyscallObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: Syscall program not available (run make generate to compile BPF programs)")
}
