// Stub BPF object definitions for ebpf-guard.
// This file provides XxxObjects types and LoadXxx stub functions that return
// errors until `make generate` is run with clang installed to produce real
// bpf2go-generated bindings.
//
// Event types, parse functions, and RingbufReader live in events.go and are
// NOT regenerated by bpf2go — they are hand-written to match the packed C
// struct layouts in bpf/common.h.
//
// When bpf2go generates real files (e.g. syscall_bpfeb.go / syscall_bpfel.go),
// delete this file and remove the stub object types so the generated ones take
// over.

package bpf

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// ---------------------------------------------------------------------------
// Syscall
// ---------------------------------------------------------------------------

// SyscallObjects contains all eBPF objects for syscall collection.
type SyscallObjects struct {
	TraceSysEnter         *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit          *ebpf.Program `ebpf:"trace_sys_exit"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	Events                *ebpf.Map     `ebpf:"events"`
	SyscallArgs           *ebpf.Map     `ebpf:"syscall_args"`
	// ProcArgsMap is the per-TGID LRU cache of command-line arguments populated
	// by the sched_process_exec hook. Accessible from Go for userspace lookups.
	ProcArgsMap *ebpf.Map `ebpf:"proc_args_map"`
	// MapFullCounters is the PERCPU_ARRAY drained by the watchdog to export
	// ebpf_guard_bpf_map_full_total. Shared across all BPF programs via common.h.
	MapFullCounters *ebpf.Map `ebpf:"map_full_counters"`
}

// Close closes all eBPF objects.
func (o *SyscallObjects) Close() error {
	for _, p := range []*ebpf.Program{
		o.TraceSysEnter, o.TraceSysExit, o.TraceSchedProcessExec,
	} {
		if p != nil {
			p.Close()
		}
	}
	for _, m := range []*ebpf.Map{o.Events, o.SyscallArgs, o.ProcArgsMap, o.MapFullCounters} {
		if m != nil {
			m.Close()
		}
	}
	return nil
}

// LoadSyscallObjects loads syscall eBPF objects from embedded bytecode.
func LoadSyscallObjects(obj *SyscallObjects, opts *ebpf.CollectionOptions) error {
	// Stub implementation - bpf2go would generate the real loading code
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Network
// ---------------------------------------------------------------------------

// NetworkObjects contains all eBPF objects for network collection.
type NetworkObjects struct {
	TraceTcpConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
	TraceTcpClose   *ebpf.Program `ebpf:"trace_tcp_close"`
	Events          *ebpf.Map     `ebpf:"events"`
	ConnStartMap    *ebpf.Map     `ebpf:"conn_start_map"`
	ConnMetaMap     *ebpf.Map     `ebpf:"conn_meta_map"`
	MapFullCounters *ebpf.Map     `ebpf:"map_full_counters"`
}

// Close closes all eBPF objects.
func (o *NetworkObjects) Close() error {
	if o.TraceTcpConnect != nil {
		o.TraceTcpConnect.Close()
	}
	if o.TraceTcpClose != nil {
		o.TraceTcpClose.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
	if o.ConnStartMap != nil {
		o.ConnStartMap.Close()
	}
	if o.ConnMetaMap != nil {
		o.ConnMetaMap.Close()
	}
	if o.MapFullCounters != nil {
		o.MapFullCounters.Close()
	}
	return nil
}

// LoadNetworkObjects loads network eBPF objects from embedded bytecode.
func LoadNetworkObjects(obj *NetworkObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Fileaccess
// ---------------------------------------------------------------------------

// FileaccessObjects contains all eBPF objects for file access collection.
// Field names and ebpf tags must match the BPF program/map names in fileaccess.bpf.c.
// After `make generate`, bpf2go produces the real struct; this stub keeps the
// build valid when clang is unavailable.
type FileaccessObjects struct {
	TraceOpen        *ebpf.Program `ebpf:"trace_open"`
	TraceRead        *ebpf.Program `ebpf:"trace_read"`
	TraceWrite       *ebpf.Program `ebpf:"trace_write"`
	TraceClose       *ebpf.Program `ebpf:"trace_close"`
	TraceOpenExit    *ebpf.Program `ebpf:"trace_open_exit"`
	TraceOpenat2Exit *ebpf.Program `ebpf:"trace_openat2_exit"`
	Events           *ebpf.Map     `ebpf:"events"`
	FdPathMap        *ebpf.Map     `ebpf:"fd_path_map"`
	FdScratchMap     *ebpf.Map     `ebpf:"fd_scratch_map"`
}

// Close closes all eBPF objects.
func (o *FileaccessObjects) Close() error {
	for _, p := range []*ebpf.Program{
		o.TraceOpen, o.TraceRead, o.TraceWrite,
		o.TraceClose, o.TraceOpenExit, o.TraceOpenat2Exit,
	} {
		if p != nil {
			p.Close()
		}
	}
	for _, m := range []*ebpf.Map{o.Events, o.FdPathMap, o.FdScratchMap} {
		if m != nil {
			m.Close()
		}
	}
	return nil
}

// LoadFileaccessObjects loads fileaccess eBPF objects from embedded bytecode.
func LoadFileaccessObjects(obj *FileaccessObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Privesc
// ---------------------------------------------------------------------------

// PrivescObjects contains all eBPF objects for privilege escalation detection.
type PrivescObjects struct {
	TraceCapset      *ebpf.Program `ebpf:"tracepoint__sys_enter_capset"`
	TraceCommitCreds *ebpf.Program `ebpf:"kprobe__commit_creds"`
	Events           *ebpf.Map     `ebpf:"events"`
	PidCaps          *ebpf.Map     `ebpf:"pid_caps"`
}

// Close closes all eBPF objects.
func (o *PrivescObjects) Close() error {
	if o.TraceCapset != nil {
		o.TraceCapset.Close()
	}
	if o.TraceCommitCreds != nil {
		o.TraceCommitCreds.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
	if o.PidCaps != nil {
		o.PidCaps.Close()
	}
	return nil
}

// LoadPrivescObjects loads privesc eBPF objects from embedded bytecode.
func LoadPrivescObjects(obj *PrivescObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Kmod (kernel module load + cgroup escape — combined BPF object)
// ---------------------------------------------------------------------------

// KmodObjects contains all eBPF objects for kernel module load detection.
type KmodObjects struct {
	LsmKernelModuleRequest *ebpf.Program `ebpf:"lsm_kernel_module_request"`
	LsmKernelReadFile      *ebpf.Program `ebpf:"lsm_kernel_read_file"`
	TraceExecRecordCgroup  *ebpf.Program `ebpf:"trace_exec_record_cgroup"`
	LsmEvents              *ebpf.Map     `ebpf:"lsm_events"`
	PidInitialCgroup       *ebpf.Map     `ebpf:"pid_initial_cgroup"`
}

// Close closes all eBPF objects.
func (o *KmodObjects) Close() error {
	for _, p := range []*ebpf.Program{
		o.LsmKernelModuleRequest,
		o.LsmKernelReadFile,
		o.TraceExecRecordCgroup,
	} {
		if p != nil {
			p.Close()
		}
	}
	for _, m := range []*ebpf.Map{o.LsmEvents, o.PidInitialCgroup} {
		if m != nil {
			m.Close()
		}
	}
	return nil
}

// LoadKmodObjects loads kmod eBPF objects from embedded bytecode.
func LoadKmodObjects(obj *KmodObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Cgroup
// ---------------------------------------------------------------------------

// CgroupObjects contains all eBPF objects for cgroup escape detection.
type CgroupObjects struct {
	LsmCgroupAttachTask *ebpf.Program `ebpf:"lsm_cgroup_attach_task"`
	CgroupEvents        *ebpf.Map     `ebpf:"cgroup_events"`
	PidInitialCgroup    *ebpf.Map     `ebpf:"pid_initial_cgroup"`
}

// Close closes all eBPF objects.
func (o *CgroupObjects) Close() error {
	if o.LsmCgroupAttachTask != nil {
		o.LsmCgroupAttachTask.Close()
	}
	for _, m := range []*ebpf.Map{o.CgroupEvents, o.PidInitialCgroup} {
		if m != nil {
			m.Close()
		}
	}
	return nil
}

// LoadCgroupObjects loads cgroup eBPF objects from embedded bytecode.
func LoadCgroupObjects(obj *CgroupObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// Iouring
// ---------------------------------------------------------------------------

// IouringObjects contains all eBPF objects for io_uring collection.
type IouringObjects struct {
	TraceIoUringSetup *ebpf.Program `ebpf:"trace_io_uring_setup"`
	TraceIoUringEnter *ebpf.Program `ebpf:"trace_io_uring_enter"`
	IouringEvents     *ebpf.Map     `ebpf:"iouring_events"`
}

// Close closes all eBPF objects.
func (o *IouringObjects) Close() error {
	for _, p := range []*ebpf.Program{
		o.TraceIoUringSetup, o.TraceIoUringEnter,
	} {
		if p != nil {
			p.Close()
		}
	}
	if o.IouringEvents != nil {
		o.IouringEvents.Close()
	}
	return nil
}

// LoadIouringObjects loads io_uring eBPF objects from embedded bytecode.
func LoadIouringObjects(obj *IouringObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// BpfMonitor
// ---------------------------------------------------------------------------

// BpfMonitorObjects contains all eBPF objects for bpf() syscall monitoring.
type BpfMonitorObjects struct {
	TraceBpfEnter    *ebpf.Program `ebpf:"trace_bpf_enter"`
	TraceBpfExit     *ebpf.Program `ebpf:"trace_bpf_exit"`
	BpfmonitorEvents *ebpf.Map     `ebpf:"bpfmonitor_events"`
	BpfEntryMap      *ebpf.Map     `ebpf:"bpf_entry_map"`
}

// Close closes all eBPF objects.
func (o *BpfMonitorObjects) Close() error {
	for _, p := range []*ebpf.Program{
		o.TraceBpfEnter, o.TraceBpfExit,
	} {
		if p != nil {
			p.Close()
		}
	}
	if o.BpfmonitorEvents != nil {
		o.BpfmonitorEvents.Close()
	}
	if o.BpfEntryMap != nil {
		o.BpfEntryMap.Close()
	}
	return nil
}

// LoadBpfMonitorObjects loads bpf monitor eBPF objects from embedded bytecode.
func LoadBpfMonitorObjects(obj *BpfMonitorObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// HiddenProcess
// ---------------------------------------------------------------------------

// HiddenProcessObjects contains the BPF task iterator program.
type HiddenProcessObjects struct {
	DumpTask *ebpf.Program `ebpf:"dump_task"`
}

// Close closes the BPF program.
func (o *HiddenProcessObjects) Close() error {
	if o.DumpTask != nil {
		return o.DumpTask.Close()
	}
	return nil
}

// LoadHiddenProcessObjects loads hidden process BPF objects from embedded bytecode.
func LoadHiddenProcessObjects(obj *HiddenProcessObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// DNS
// ---------------------------------------------------------------------------

// DNSObjects contains all eBPF objects for DNS monitoring.
// The BPF programs attach to sys_enter_sendmsg and sys_enter_sendto tracepoints
// and write events into the dedicated dns_events ring buffer.
type DNSObjects struct {
	TraceSendmsg *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSendto  *ebpf.Program `ebpf:"trace_sendto"`
	DnsEvents    *ebpf.Map     `ebpf:"dns_events"`
}

// Close closes all eBPF objects.
func (o *DNSObjects) Close() error {
	for _, p := range []*ebpf.Program{o.TraceSendmsg, o.TraceSendto} {
		if p != nil {
			p.Close()
		}
	}
	if o.DnsEvents != nil {
		o.DnsEvents.Close()
	}
	return nil
}

// LoadDNSObjects loads DNS eBPF objects from embedded bytecode.
func LoadDNSObjects(obj *DNSObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// ---------------------------------------------------------------------------
// TlsClientHello
// ---------------------------------------------------------------------------

// TlsClientHelloObjects contains all eBPF objects for TLS ClientHello capture.
type TlsClientHelloObjects struct {
	TraceSendto          *ebpf.Program `ebpf:"trace_sendto"`
	TlsClienthelloEvents *ebpf.Map     `ebpf:"tls_clienthello_events"`
}

// Close closes all eBPF objects.
func (o *TlsClientHelloObjects) Close() error {
	if o.TraceSendto != nil {
		o.TraceSendto.Close()
	}
	if o.TlsClienthelloEvents != nil {
		o.TlsClienthelloEvents.Close()
	}
	return nil
}

// LoadTlsClientHelloObjects loads TLS ClientHello eBPF objects from embedded bytecode.
func LoadTlsClientHelloObjects(obj *TlsClientHelloObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}
