// Package bpf — stub types for the TlsClientHello BPF program.
//
// The real TlsClientHelloObjects / LoadTlsClientHelloObjects are generated by `make generate`
// (bpf2go compiles bpf/tls_clienthello.bpf.c and emits Go bindings). This stub provides the
// same exported API so packages that import internal/bpf can be compiled and
// tested without a clang/kernel-headers toolchain — notably on macOS, where
// clang has no BPF backend at all.
//
// In a production build, run `make generate` first; the generated
// tlsclienthello_bpfel.go / tlsclienthello_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// TlsClientHelloMaps holds the BPF maps exported by bpf/tls_clienthello.bpf.c.
type TlsClientHelloMaps struct {
	TlsClienthelloEvents *ebpf.Map `ebpf:"tls_clienthello_events"`
}

// TlsClientHelloPrograms holds the BPF programs exported by bpf/tls_clienthello.bpf.c.
type TlsClientHelloPrograms struct {
	TraceSendto *ebpf.Program `ebpf:"trace_sendto"`
}

// TlsClientHelloObjects contains all BPF objects after loading bpf/tls_clienthello.bpf.c.
type TlsClientHelloObjects struct {
	TlsClientHelloPrograms
	TlsClientHelloMaps
}

// Close releases all BPF resources held by the objects.
func (o *TlsClientHelloObjects) Close() error {
	var errs []error
	if o.TraceSendto != nil {
		errs = append(errs, o.TraceSendto.Close())
	}
	if o.TlsClienthelloEvents != nil {
		errs = append(errs, o.TlsClienthelloEvents.Close())
	}
	return errors.Join(errs...)
}

// LoadTlsClientHelloObjects loads the TlsClientHello BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/tls_clienthello.bpf.c.
func LoadTlsClientHelloObjects(_ *TlsClientHelloObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: TlsClientHello program not available (run make generate to compile BPF programs)")
}
