// Package bpf — stub types for the TLS uprobe BPF program.
//
// The real TlsUprobeObjects / LoadTlsUprobeObjects / LoadTlsUprobe are
// generated by `make generate` (bpf2go compiles bpf/tls_uprobe.bpf.c and emits
// Go bindings). This stub provides the same exported API so packages that
// import internal/bpf can be compiled and tested without a
// clang/kernel-headers toolchain — notably on macOS, where clang has no BPF
// backend at all.
//
// In a production build, run `make generate` first; the generated
// tlsuprobe_bpfel.go / tlsuprobe_bpfeb.go files replace this stub, which
// `make generate` deletes.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// TlsUprobeMaps holds the BPF maps exported by bpf/tls_uprobe.bpf.c.
type TlsUprobeMaps struct {
	TlsEvents       *ebpf.Map `ebpf:"tls_events"`
	SslReadContexts *ebpf.Map `ebpf:"ssl_read_contexts"`
}

// TlsUprobePrograms holds the BPF programs exported by bpf/tls_uprobe.bpf.c.
type TlsUprobePrograms struct {
	TraceSslWrite       *ebpf.Program `ebpf:"trace_ssl_write"`
	TraceSslReadEntry   *ebpf.Program `ebpf:"trace_ssl_read_entry"`
	TraceSslReadRetFull *ebpf.Program `ebpf:"trace_ssl_read_ret_full"`
}

// TlsUprobeObjects contains all BPF objects after loading bpf/tls_uprobe.bpf.c.
type TlsUprobeObjects struct {
	TlsUprobePrograms
	TlsUprobeMaps
}

// Close releases all BPF resources held by the objects.
func (o *TlsUprobeObjects) Close() error {
	var errs []error
	if o.TraceSslWrite != nil {
		errs = append(errs, o.TraceSslWrite.Close())
	}
	if o.TraceSslReadEntry != nil {
		errs = append(errs, o.TraceSslReadEntry.Close())
	}
	if o.TraceSslReadRetFull != nil {
		errs = append(errs, o.TraceSslReadRetFull.Close())
	}
	if o.TlsEvents != nil {
		errs = append(errs, o.TlsEvents.Close())
	}
	if o.SslReadContexts != nil {
		errs = append(errs, o.SslReadContexts.Close())
	}
	return errors.Join(errs...)
}

// LoadTlsUprobe returns the embedded CollectionSpec for TlsUprobe.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/tls_uprobe.bpf.c.
func LoadTlsUprobe() (*ebpf.CollectionSpec, error) {
	return nil, fmt.Errorf("bpf: TlsUprobe program not available (run make generate to compile BPF programs)")
}

// LoadTlsUprobeObjects loads the TlsUprobe BPF programs and maps.
// This stub always returns an error — run `make generate` to produce the real
// implementation from bpf/tls_uprobe.bpf.c.
func LoadTlsUprobeObjects(_ *TlsUprobeObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: TlsUprobe program not available (run make generate to compile BPF programs)")
}
