// Package bpf — stub types for the XDP BPF program.
//
// The real XDPObjects / LoadXDPObjects are generated by `make generate`
// (bpf2go compiles bpf/xdp_block.bpf.c and emits Go bindings).  This stub
// provides the same exported API so packages that import internal/bpf can be
// compiled and tested without a clang/kernel-headers toolchain.
//
// In a production build, run `make generate` first; the generated
// xdp_bpfel.go / xdp_bpfeb.go files will replace this stub.

package bpf

import (
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
)

// XDPMaps holds the BPF maps exported by xdp_block.bpf.c.
// xdp_stats_map is BPF_MAP_TYPE_PERCPU_ARRAY; userspace aggregates
// per-CPU values via ReadXDPStats before exporting to Prometheus.
type XDPMaps struct {
	XdpBlockedIps   *ebpf.Map `ebpf:"xdp_blocked_ips"`
	XdpBlockedPorts *ebpf.Map `ebpf:"xdp_blocked_ports"`
	XdpStatsMap     *ebpf.Map `ebpf:"xdp_stats_map"`
}

// XDPPrograms holds the BPF programs exported by xdp_block.bpf.c.
type XDPPrograms struct {
	XdpBlockFn *ebpf.Program `ebpf:"xdp_block_fn"`
}

// XDPObjects contains all BPF objects after loading xdp_block.bpf.c.
type XDPObjects struct {
	XDPPrograms
	XDPMaps
}

// Close releases all BPF resources held by the objects.
func (o *XDPObjects) Close() error {
	var errs []error
	if o.XdpBlockedIps != nil {
		errs = append(errs, o.XdpBlockedIps.Close())
	}
	if o.XdpBlockedPorts != nil {
		errs = append(errs, o.XdpBlockedPorts.Close())
	}
	if o.XdpStatsMap != nil {
		errs = append(errs, o.XdpStatsMap.Close())
	}
	if o.XdpBlockFn != nil {
		errs = append(errs, o.XdpBlockFn.Close())
	}
	return errors.Join(errs...)
}

// LoadXDPObjects loads the XDP BPF program and maps.
// This stub always returns an error — run `make generate` to produce the
// real implementation from bpf/xdp_block.bpf.c.
func LoadXDPObjects(o *XDPObjects, _ *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf: XDP program not available (run make generate to compile BPF programs)")
}
