// Code generated by bpf2go; DO NOT EDIT.
// This is a stub — run 'make generate' with clang installed to regenerate.

package bpf

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// XDPStats mirrors the BPF xdp_stats struct for Prometheus scraping.
type XDPStats struct {
	Dropped uint64
	Passed  uint64
}

// XDPObjects contains all eBPF objects for XDP packet filtering.
type XDPObjects struct {
	// XdpBlockFn is the XDP program attached to the network interface.
	XdpBlockFn *ebpf.Program `ebpf:"xdp_block_fn"`
	// XdpBlockedIPs is an LRU hash map keyed by 16-byte IP address (network byte order).
	// IPv4 addresses occupy the first 4 bytes; IPv6 uses all 16.
	XdpBlockedIPs *ebpf.Map `ebpf:"xdp_blocked_ips"`
	// XdpBlockedPorts is an LRU hash map keyed by destination port (host byte order).
	XdpBlockedPorts *ebpf.Map `ebpf:"xdp_blocked_ports"`
	// XdpStatsMap is a single-entry array map holding drop/pass counters.
	XdpStatsMap *ebpf.Map `ebpf:"xdp_stats_map"`
}

// LoadXDPObjects loads XDP eBPF objects from embedded bytecode.
// Stub implementation — real code is produced by 'make generate'.
func LoadXDPObjects(obj *XDPObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf2go generated code not available: run 'make generate' with clang installed")
}

// Close releases all XDP eBPF object handles.
func (o *XDPObjects) Close() error {
	if o.XdpBlockFn != nil {
		o.XdpBlockFn.Close()
	}
	if o.XdpBlockedIPs != nil {
		o.XdpBlockedIPs.Close()
	}
	if o.XdpBlockedPorts != nil {
		o.XdpBlockedPorts.Close()
	}
	if o.XdpStatsMap != nil {
		o.XdpStatsMap.Close()
	}
	return nil
}
